### ISSUE TITLE
Créer un lieu (back) - pas d'affichage des statuts

### ISSUE THREAD

**Issue by Mathieu-CdlT** [chemins-de-la-transition/semapps#100]
Dans la création d'un lieu, dans l'onglet relation > statut, problème d'affichage et de complétion (pas d'affichage des différents statuts, liste vide s'ouvre). Possibilité de corriger ?

**Comment by srosset81** [comment]
Il suffit d'ajouter un ou plusieurs PlaceStatus ici:
https://admin.lescheminsdelatransition.org/Status

A noter que le statut n'est pas visible sur l'interface front. C'est donc juste un indicateur à utiliser en interne, dans le backoffice. Si ça peut porter à confusion, je peux aussi le supprimer.
