### ISSUE TITLE
Création de lieu (back/Front) - données personnelles

### ISSUE THREAD

**Issue by Mathieu-CdlT** [chemins-de-la-transition/semapps#102]
A-t-on la possibilité de permettre aux orgas de choisir si elles souhaitent faire apparaitre leurs coordonnées (Adresse, num tel, mail, site web) sur le front (ou si les contacter via formulaire de contact) ? Case à cocher ? 

J'anticipe le fait que certaines ne voudront pas afficher leur num de tel en public (et nous leur num de tel nous interesse en gestion relation partenariale)

**Comment by srosset81** [comment]
Le téléphone est un champ facultatif (pas d'étoile à côté), mais on peut peut-être ajouter une petite note (en-dessous) pour avertir que le numéro de téléphone sera visible sur l'interface ?

Concernant l'adresse, cela semble difficile à éviter puisque ce sont des lieux et qu'ils doivent s'afficher sur la carte, non ? Un lieu peut donner une adresse approximative (p.ex. le nom de la ville) mais cela empêche les personnes de le trouver, ce qui est un peu contraire à la philosophie des CDLT, non?

**Comment by srosset81** [comment]
Ajouter "Téléphone" et "Site web"

Décalage visible sur Firefox

**Comment by srosset81** [comment]
Fixé
