### ISSUE TITLE
Création lieu - Affichage champs texte sur le front

### ISSUE THREAD

**Issue by Mathieu-CdlT** [chemins-de-la-transition/semapps#103]
Les sauts de ligne (partie a propos du lieux par exemple) qui sont bien pris en compte sur la prévisualisation dans le back ne sont pas repris sur la version front. Du coup ca fait un gros paté pas agréable à lire (cf CDLT Tlse). Possible de corriger ca?

**Comment by srosset81** [comment]
OK je m'occupe d'ajouter un peu de marges entre les paragraphes !
