### ISSUE TITLE
Afficher les LEP de manière intégrée suite à modif moteur de recherche

### ISSUE THREAD

**Issue by GuillaumeAV** [chemins-de-la-transition/semapps#106]
Sur la carte utiliser 3 pictos différents pour distinguer Lieux, Parcours, Evenements
Ce serait pas mal je crois, bien que non urgent ni nécessaire :) 

On pourrait généraliser demander à Lilian et Boris d'en créer des custom ... Facile à intégrer des pictos custom ?

**Comment by srosset81** [comment]
Apparemment ça peut se faire en fournissant un PNG:
https://leafletjs.com/reference-1.7.1.html#icon

**Comment by GuillaumeAV** [comment]
## Contexte
C’est une conséquence de la modification du moteur de recherche. Le résultat qui sortira de l’intersection modalités / régions / catégories mixera des Chemins, des Lieux, des Événements et des Parcours

## Objectif
Différencier des CLEPs sur les différentes interfaces …
* Carte : 3 pictos différents … (on les a et ils sont beaux)
* Liste : 4 onglets différents ? Comme sur SemApps v1 ;)

**Comment by GuillaumeAV** [comment]
to @AudreyCDLT 

J'ai regardé le figma c'est génial ... Une petite remarque à propos du moteur de recherche ... On a jugé qu'il serait pertinent de pouvoir sélectionner en critère 1 de la barre de recherche la modalité de parcours (découverte, apprentissage, immersion, compagnonage) ... Ce qui débouche sur la création d'une page de résultats telle que décrite plus haut dans cette issue ... 

- Tu pourrais intégrer le critère modalité dans le moteur de recherche et réfléchir à un affichage intégré des LEPs ?

**Comment by GuillaumeAV** [comment]
from @AudreyCDLT 

Affichage pictos différents pour les CLEP sur la carte, on parle de quelle carte, celle des parcours? Si c'est le cas, pour moi il n'y a que 2 pictos possible (événement et lieu) en sachant qu'un point peut avoir les 2 en même temps.
C'est lié à ce qui est mentionné au dessus et plus haut : L'intégration du critère modalité / type de parcours dans le moteur de recherche .. 

Réponse Guillaume : 
Il manque un picto ... Ok c'est un petit problème qu'on peut envisager de résoudre ! J'y songe dans les jours qui viennent !

**Comment by srosset81** [comment]
Pour l'instant on avait en effet choisi de ne pas afficher les parcours sur les cartes, car ça pouvait impliquer de nombreux problèmes techniques et UX.

**Comment by GuillaumeAV** [comment]
Après concertation avec Audrey, on peut envisager de se passer de cette fonctionnalité : 

* En changeant le comportement du moteur de recherche (obligation de spécifier chacun des champs ou alors champs sélectionnés par défaut)
* En designant les pages chemins comme sur la slide 10 [de ce doc](https://docs.google.com/presentation/d/19ii_FFsOINBWUHqegMFtU6xwbaAIkZRI7p_vA4ChOU4/edit?usp=sharing)

**Comment by GuillaumeAV** [comment]
Cette issue est fonction du choix qu'on fera sur la #158

**Comment by VincentFarcy** [comment]
@GuillaumeAV Choix non déterminé. A déplacer dans un autre milestone ?

**Comment by GuillaumeAV** [comment]
On part sur un affichage des résultats en onglets !

**Comment by srosset81** [comment]
- Affichage en onglet à la place des vues (seulement vue liste)
- Pas de bouton ajouter sur cette page recherche
- Sur formulaire de recherche, permettre de sélectionner aucun type

**Comment by srosset81** [comment]
Fait https://github.com/chemins-de-la-transition/semapps/pull/223

Temps facturé: 6H
