### ISSUE TITLE
Enlever les thématiques du menu horizontal en haut

### ISSUE THREAD

**Issue by GuillaumeAV** [chemins-de-la-transition/semapps#108]
[Comme dans ce cas](https://app.lescheminsdelatransition.org/Place/https%3A%2F%2Fdata.lescheminsdelatransition.org%2Fplaces%2Fle-wip/show), il peut y en avoir beaucoup ... Je priviligérait du coup un affichage uniquement dans le menu de droite ...

**Comment by GuillaumeAV** [comment]
Par ailleurs, je me dis que les compétences pourraient également avoir toute leur place dans le menu de droite plutôt que dans le corps de la page... 
Qu'en pensez vous @AudreyCDLT & @Mathieu-CdlT

**Comment by srosset81** [comment]
Le design d'Audrey n'est pas prévu pour mettre autant de thématique, comme on le voit sur la homepage:

![Capture d’écran de 2021-09-23 23-28-47](https://user-images.githubusercontent.com/17931931/134586703-74a762a6-d814-4e9e-92dc-a607bef72209.png)

**Comment by GuillaumeAV** [comment]
Cette problématique sera résolue avec la refonte du design, voir #121
