### ISSUE TITLE
Héberger ce repo (semapps) dans le repo plateforme 

### ISSUE THREAD

**Issue by GuillaumeAV** [chemins-de-la-transition/semapps#11]
Ce serait cohérent non ?

**Comment by bouviermullerp** [comment]
Coucou @GuillaumeAV as tu été visiter le repo plateforme avant de créer cette issue ? :)
Si tu m'assignes à une issue, peux-tu être plus explicite ? Sinon, je préfère que tu me mentionnes, si ce n'est pas clair c'est plus confortable pour moi de s'envoyer des messages avant.
Je me désassigne en attendant, jusqu'a ce que je prenne vraiment l'acion.

**Comment by GuillaumeAV** [comment]
Yop ! 
Euuh oui j'y suis allé... Mais tu veux dire que c'est pas pertinent c'est ca ?

**Comment by bouviermullerp** [comment]
Je n'en sais rien :) à mes yeux ça a peu de valeur ajoutée, mais peut être pas aux tiens.
En tout cas, il y a déjà le code de la plateforme YEsWiki qui y est stocké... On ne va pas mettre les 2 codes dans le même répertoire.

**Comment by srosset81** [comment]
Mettre le code dans les 2 répertoires serait possible techniquement mais ce qui me semble problématique c'est surtout les dizaines d'issues qui concernent YesWiki. Ca va rendre difficile la lisibilité.

**Comment by srosset81** [comment]
A noter que si des issues concernent SemApps, elles peuvent être transférées ici assez facilement.

**Comment by GuillaumeAV** [comment]
Ok sorry je n'avais pas conscientisé certaines choses ... Peut être alors juste renommer le repo "Plateforme" en "Yes Wiki CdlT" ?
