### ISSUE TITLE
L'espace disque se remplit rapidement

### ISSUE THREAD

**Issue by Mathieu-CdlT** [chemins-de-la-transition/semapps#110]
Hier (22/09) gros bug sur app.cdlt - plus d'affichage des images ni, filtres, résultat de recherche, parcours, lieux et événements... à partir du milieu d'aprem. C'est con, le soir on avait une présentation de la plateforme au CA. Mais on les a bien alléchés qd même. Peut être on a modifié qq données dans le back, peut être c'est un bug extérieur dû à une intervention sur SemApps, je ne sais pas la source de cette plantade, mais c'est un beau cas/test de stabilité. 
Est ce qu'il est possible de regarder et de remettre la plateforme fonctionnelle / corriger source bug - stabilité si possible ?

**Comment by srosset81** [comment]
Le disque est plein et Fuseki est tombé. Je regarde pourquoi.

**Comment by srosset81** [comment]
![Capture d’écran de 2021-09-23 11-17-15](https://user-images.githubusercontent.com/17931931/134484044-172adf6e-a740-4f0d-8ba7-bad10ce22188.png)

30Gb sont utilisés par Fuseki, alors que seulement 3000 triples sont stockés. Sur le SemApps de l'AV, on a plus de triples et seulement 100Mb sont utilisés pour les mêmes fichiers. Je comprends pas.

**Comment by srosset81** [comment]
Je peux tout virer et remettre des données propres (sans qu'on perde rien), mais je vais encore explorer un peu pour essayer de comprendre ce qui s'est passé, et empêcher que ça se reproduise.

**Comment by srosset81** [comment]
Apparement ces fichiers permettent de maintenir un index:

> If you look in the TDB directory, you will see files like SPO.idn and
SPO.dat. That's the SPO clustered index. For triples the indexes are
SPO, POS and OSP. More indexes for quads (named graphs).
> 
> TDB has total coverage (every triple order can be answered by an index).
> https://users.jena.apache.narkive.com/1g520ze8/fuseki-tdb-indexing#post3

SPO = subject predicate object
POS = predicate object subject
OSP = object subject predicate

Pourquoi 5 Gb pour indexer 3000 triples, je n'en sais rien.

**Comment by Mathieu-CdlT** [comment]
Yes, merci, en effet c'est préoccupant si le disque est déjà plein alors qu'on a pas commencé à mettre des données dessus... Cool que ça arrive maintenant plutot que plus tard ;)! Merci Seb d'être là :)

**Comment by srosset81** [comment]
Niko, un des devs SemApps, a trouvé la solution. C'était un problème de données qu'il faut régulièrement compacter sinon elles peuvent commencer à prendre trop de place. Je copie-colle sa solution temporaire:

> aller dans le shell du docker fuseki, modifier le fichier /jena-fuseki/fuseki-server en commentant la ligne 107 et decommentant la ligne 108
puis sortir su shell
faire un docker stop fuseki
docker start fuseki
le compact est fait
retourner dans le shell
faire l óperation inverse pour les lignes 107 et 108
sortir du shell
docker stop fuseki
docker start fuseki

Le serveur est reparti. Il y a toujours le problème des lieux qui n'apparaissent pas sur la homepage, rapporté par Guillaume. J'essaie de regarder ça demain, sinon lundi.

**Comment by nikoPLP** [comment]
sortir *du shell

**Comment by srosset81** [comment]
Grâce à l'éclairage de @nikoPLP je crois que le problème avec la base de donnée qui grossit vient de là:
https://github.com/chemins-de-la-transition/semapps/blob/master/middleware/services/event-status.service.js
Ce service met à jour le statut des événements toutes les minutes (ça devrait être toutes les 5 minutes)
Chaque fois qu'on efface et rajoute des triples, ça fait augmenter le fichier, et à un moment il faut compresser. Mais sachant cela (j'en avais aucune idée), je vais optimiser le code pour mettre à jour les événements seulement quand le statut change.

**Comment by srosset81** [comment]
Pour le moment je vais régler le problème en ne mettant à jour le statut toutes les 3 heures
https://github.com/chemins-de-la-transition/semapps/commit/2995ecbe0953401a98268307c12666326f42dd51
Ca va remplir l'espace 200 fois plus lentement.

**Comment by simonLouvet** [comment]
coucou @srosset81 , comment aller dans le shell du docker fuseki quand on le peut plus démarrer le docker par ce que le disque est plein?

**Comment by nikoPLP** [comment]
> coucou @srosset81 @nikoPLP, comment aller dans le shell du docker fuseki quand on ne peut plus démarrer le docker par ce que le disque est plein?

supprimer quelques fichiers de log ?
augmenter la taille du volume depuis l'exterieur du docker?

**Comment by simonLouvet** [comment]
@nikoPLP effectivement, supprimer les log m'a permis de retrouver 2G pour redémarrer les docker. Comment arrêter fuseki une fois dans le container fuseki?

**Comment by nikoPLP** [comment]
> @nikoPLP effectivement, supprimer les log m'a permis de retrouver 2G pour redémarrer les docker. Comment arrêter fuseki une fois dans le container fuseki? Image que j'utilise sur cette instance : stain/jena-fuseki:3.10.0. pour info; supprimer les log docker : sudo find /var/lib/docker/containers/ -type f -name "*.log" -delete

Il me semble que l'arret de fuseki se fait depuis l'exterieur du docker, c'est a dire juste dans ta session ssh, avec la commande `docker stop fuseki`.
Au prealable tu as trouvé la ligne 108 dans le fichier `/jena-fuseki/fuseki-server` (depuis le shell docker) ?
je pesne qu'il va te manquer la ligne 108 de toute facon.
Je la cherche !!!

**Comment by simonLouvet** [comment]
@nikoPLP et @srosset81  mon fichier fuseki-server ne fait que 95 lignes. Pouvez vous décrire les ligne qu'il faut commenter-decommenter svp

**Comment by srosset81** [comment]
Le compact via l'API ne fonctionne pas

**Comment by nikoPLP** [comment]
@simonLouvet @srosset81 la solution est là :
https://github.com/assemblee-virtuelle/semapps/pull/886

**Comment by nikoPLP** [comment]
> @nikoPLP et @srosset81 mon fichier fuseki-server ne fait que 95 lignes. Pouvez vous décrire les ligne qu'il faut commenter-decommenter svp

en fait les instructions sont invalides, car tout avait été fait a la va vite. il n'y a pas de ligne 108 dans le code source... bref, au final, La solution est dans la merge request ci-dessus

**Comment by nikoPLP** [comment]
@Mathieu-CdlT @srosset81 cette issue pourrait etre fermée dès que vous aurez fait la mise a jour sur CDLT

**Comment by srosset81** [comment]
Presque fini. Je dois juste comprendre pourquoi le cron qui est censé lancer un compactage chaque nuit ne marche pas.

**Comment by srosset81** [comment]
Fixé ! https://github.com/chemins-de-la-transition/deployment/commit/a71a217c5dce2bbf05a89cf392bd1892ff08d774

**Comment by simonLouvet** [comment]
l'URL de déploiement me retourne une 404 @srosset81 . Tu peux expliquer comment tu as fait en quelques mots ?

**Comment by srosset81** [comment]
@simonLouvet 

```bash
#!/bin/bash

# To call this script every night at 4am, call "crontab -e" and enter this line :
# 0 4 * * * /home/ubuntu/deployment/cleanup.sh >> /home/ubuntu/cron.log 2>&1

# Add /usr/local/bin directory where docker-compose is installed
PATH=/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/bin

cd ~/deployment

# On each restart, Fuseki will compact its databases
docker-compose down
docker-compose up -d
# Wait for the compacting to be executed
sleep 5

# Delete the old datasets
sudo find ./data/fuseki/databases/localData -iname 'Data*' ! -wholename $(find ./data/fuseki/databases/localData -iname 'Data*' -type d | sort -n | tail -n 1)  -type d  -exec rm -rf {} +

echo "Cron job finished at" $(date)
```

**Comment by srosset81** [comment]
Ca peut être simplifié comme ça, en supprimant fuseki-compact du docker-compose, et en laissant l'entrypoint s'occupe de l'effaçage des données:

```bash
#!/bin/bash

# To call this script every night at 4am, call "crontab -e" and enter this line :
# 0 4 * * * /home/ubuntu/deployment/cleanup.sh >> /home/ubuntu/cron.log 2>&1

# Add /usr/local/bin directory where docker-compose is installed
PATH=/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/bin

# Stop all containers including Fuseki
docker-compose down

# Build and tag image
docker build -t fuseki-compact ./fuseki-compact

# Run fuseki-compact with same data as prod
docker run --volume="$(pwd)"/data/fuseki:/fuseki --entrypoint=/docker-compact-entrypoint.sh fuseki-compact

docker-compose up -d

echo "Cron job finished at" $(date)
```
