### ISSUE TITLE
Problème quand on invite une personne à rejoindre la plateforme en tant qu'acteur 

### ISSUE THREAD

**Issue by GuillaumeAV** [chemins-de-la-transition/semapps#112]
- Sur admin.cdlt, je crée une nouvelle personne avec un mail jamais utilisé auparavant : Elément créé, élement mis à jour. 
- Dans un autre navigateur, j'ouvre ma boite mail, je clique sur le mail, puis sur le lien ui me bascule sur le login des communs. 
- Quand je clique sur le bouton, le message suivant apparait : Aucun compte trouvé avec cette adresse mail (l'url est : https://app.lescheminsdelatransition.org/login?login=true&error=registration.not-allowed)

**Comment by srosset81** [comment]
Vu avec @GuillaumeAV , il faut aller sur https://login.lescommuns.org, se déconnecter et se reconnecter.

C'est un cas particulier, la grande majorité des utilisateurs n'ayant qu'un seul compte sur les communs.

**Comment by GuillaumeAV** [comment]
Je confirme, ca marche ;)
