### ISSUE TITLE
FRONT - HP : Classement par odre alphabétique des thématiques

### ISSUE THREAD

**Issue by Mathieu-CdlT** [chemins-de-la-transition/semapps#113]
Front end - Home Page : dans la barre de recherche et tous les filtres thématiques, l'affichage des thématiques se fait dans un ordre "bizarre", pas forcément logique. 
Est il possible de faire apparaitre les thématiques par ordre alphabétique ?

**Comment by srosset81** [comment]
Fait https://github.com/chemins-de-la-transition/semapps/commit/b73b3b9c1eaed0bdb04177a20799418ea7aa5062
