### ISSUE TITLE
FRONT - RESULTATS LIEUX - Affichage des régions

### ISSUE THREAD

**Issue by Mathieu-CdlT** [chemins-de-la-transition/semapps#117]
Sur la page résultat lieux, en mode affichage liste, apparaissent les régions comme des lieux. A enlever de cet affichage, car c'est confusing et on ne comprend pas ce que ca fait là.   

Voir capture d'écran sur : 
https://docs.google.com/document/d/1SpnaGHlT1KkbL_YHnunGblhGzyC4UWe7/edit

**Comment by srosset81** [comment]
Oui problème identifié. Il sera réglé dès qu'on sortira une nouvelle version de SemApps.

**Comment by srosset81** [comment]
@GuillaumeAV ce bug est encore là car effectivement j'ai pas mis à jour SemApps. Je m'en occupe aujourd'hui ou demain.

**Comment by srosset81** [comment]
C'est bon les régions n'apparaissent plus dans la liste
