### ISSUE TITLE
FRONT - Affichage résultat événements

### ISSUE THREAD

**Issue by Mathieu-CdlT** [chemins-de-la-transition/semapps#119]
Est-il possible lorsqu'on clique dans le menu sur événements, d'arriver par défaut (affichage résultat événements) sur une vue Liste plutôt que calendrier ? 

(tout en gardant les boutons vue calendrier / carte / liste)

Ce serait beaucoup plus sympa me semble-t-il - d'autant que par exemple aujourd'hui, pas d'événements programmés sur Octobre donc affichage de résultat = 0

**Comment by srosset81** [comment]
Complétement possible... et déjà fait :-)
