### ISSUE TITLE
Créer dans le repo plateforme un repo Ontologie et héberger l'ontologie

### ISSUE THREAD

**Issue by GuillaumeAV** [chemins-de-la-transition/semapps#12]
Après une discussion avec Thomas Francart, on se dit qu'il est pertinent d'héberger l'ontologie sur le github CdlT, d'où cette proposition. 
Voici le dossier dans lequel se trouve l'ontologie ;) 
Une fois que l'ontologie sera hébergée on pourra la faire évoluer via git et donc avoir le controle de version :)

**Comment by bouviermullerp** [comment]
@GuillaumeAV manque le lien du dossier.

**Comment by GuillaumeAV** [comment]
Ah oui en effet c'est embêtant :)
Et voila cher @bouviermullerp ! https://drive.google.com/drive/folders/1QF45J_aNzfQhsdUwCSEh3MDod4UXSbe5?usp=sharing

**Comment by bouviermullerp** [comment]
C'est fait ;)

**Comment by srosset81** [comment]
@bouviermullerp Guillaume l'avait déjà mis dans le repo dédié à l'ontologie:
https://github.com/chemins-de-la-transition/ontology

Je pense qu'on peut enlever celui que tu as ajouté ici:
https://github.com/chemins-de-la-transition/semapps/blob/master/ontology/ontology_cdlt_v0.1.owl
L'ontologie n'est pas spécifique à la plateforme SemApps et pourrait être utilisé dans d'autres projets.

**Comment by bouviermullerp** [comment]
ça serait si pratique de fermer les issues quand elles sont terminées
