### ISSUE TITLE
FRONT - Affichage d'un parcours - bandeau haut

### ISSUE THREAD

**Issue by Mathieu-CdlT** [chemins-de-la-transition/semapps#121]
Possibilité de réorganiser l’affichage du bandeau du haut ? si bcp de thématiques, elles ne s’affichent pas en totalité et la date et la durée disparaissent. 

- Peut être intervertir l’ordre (passer date et durée avant thématiques) ?
- Affichage sur 2 lignes ? 

(ex: tournée tiers lieux - rencontres citoyennes de la Convention citoyenne pour le Climat)

Voir Capture d'écran dans (issue 121): 
https://docs.google.com/document/d/1SpnaGHlT1KkbL_YHnunGblhGzyC4UWe7/edit

**Comment by srosset81** [comment]
Le design de @AudreyCDLT ne prévoyait pas du tout des thématiques aussi longues et nombreuses. Cela a un impact à de nombreux endroits sur le site.

C'est un problème de design avant tout, je ne suis pas en capacité de le régler seul. En tout cas ça sort du scope de la première prestation puisque je me suis basé sur un design qui avait été validé.

**Comment by GuillaumeAV** [comment]
Ce problème devrait être résolu suite à la prestation d'Audrey sur la refonte et l'amélioration du design, voir notamment les quelques [premières préconisations sur ce doc](https://docs.google.com/presentation/d/19ii_FFsOINBWUHqegMFtU6xwbaAIkZRI7p_vA4ChOU4/edit#slide=id.p)

**Comment by AudreyCDLT** [comment]
@GuillaumeAV @Mathieu-CdlT  je viens de voir que vous aviez fait un doc rassemblant tous les retours commentaires / bugs sur la plateforme. J'ai traité l'ensemble des retours design à l'exception de ceux pour le mobile. Peux tu créer des bugs pour cette partie que l'on puisse le suivre et le traiter. merci


De manière général, pourrait-on prendre le réflexe de créer des bug dans le kanban pour traquer tous les bugs. Beaucoup plus simple à traiter pour designers / développeurs. Merci d'avance. **Process : création d'un bug (éviter les mutli bugs dans un ticket) avec preuve à l'appui pour retrouver le contexte (photo + description).** 

JE PASSE CETTE US EN OK DESIGN, Pour les bugs design, ça sera fait dans une autre issues

**Comment by GuillaumeAV** [comment]
Proposition : Ne mettre dans le bandeau haut que les éléments suivants : 
Région (1) - Thèmes principaux (1-3) - Modalités (1-4)

Se synchroniser avec moi au début du sprint.

**Comment by VincentFarcy** [comment]
Ajouter également une limite au nombre de personnes / organisateurs en lien au travers des relations
- Place : proposedBy (hôte du lieu)
- Event/Course : hasMentor (mentor ou intervenant) et organizedBy (organisé par)

**Comment by VincentFarcy** [comment]
Rq : le pb du nb d'éléments maxi se pose également pour les vignettes. A traiter dans la même issue ?

**Comment by GuillaumeAV** [comment]
Merci @VincentFarcy pour le travail ! Mon point de vue, on pourrait n'afficher que les informations clé la haut .. On en discute demain !

**Comment by VincentFarcy** [comment]
A clôre @GuillaumeAV ?

**Comment by GuillaumeAV** [comment]
Yop ! oui en effet on peut la clore : Je suis en train de faire un travail important de mise en cohérence des différents fronts, que je vais ensuite transmettre à Audrey .. ([Début du travail ici](https://docs.google.com/spreadsheets/d/17Osh5uKbRi0B9kbT6COpyJ_andr2vLfdDLkqyZe9GN4/edit#gid=1809350170))

On fera une nouvelle issue !
