### ISSUE TITLE
FRONT : Zoom / Scroll Cartes

### ISSUE THREAD

**Issue by Mathieu-CdlT** [chemins-de-la-transition/semapps#122]
Cartes : quelle possibilité de désactiver le zoom / dézoom et de juste garder le +/- pour affichage carte sur un affichage d'un parcours d'un lieu ou d'un événement (ou alors faire un zoom à 2 doigts)? 

Qd on scrole vers le bas / haut pour naviguer sur la page et qu’on passe sur la carte, ca zoome / dézoome la carte et on a du mal à passer à la suite en naviguant. 

C’est pénible (obligés de passer sur le coté de la carte ce qui n’est pas toujours évident / intuitif). Autant sur un affichage de la totalité des résultats (lieux, événements, parcours) c’est utile, autant sur les pages d'UN lieu, d'UN événement ou d'UN parcours c’est pas nécessaire. 

Pourrait-on dans le back office, régler le niveau de zoom à afficher et si on veut bouger sur l’affichage d’un parcours, juste faire avec les boutons +/- ? 

Si mes explications ne sont pas claires, me demander.

**Comment by srosset81** [comment]
J'ai désactivé le zoom par scroll sur les pages événements / lieux / parcours.

> Pourrait-on dans le back office, régler le niveau de zoom à afficher.

Ce serait une prestation en plus. Pour les parcours le niveau de zoom s'adapte aux points. Pour le reste, j'utilise un zoom par défaut qui peut être changé si besoin. Si on met ce paramètre au niveau du backoffice, il faut penser que les acteurs devront comprendre de quoi il s'agit lorsqu'ils créent leur événement ou lieu. Je suis pas sûr que ce sera intuitif.

**Comment by Mathieu-CdlT** [comment]
Super ! 
Par contre le pb subsiste sur la version mobile. 
Possible de l'enlever là aussi (sur les pages événements / lieux / parcours juste) ?
