### ISSUE TITLE
FRONT - Gestion des données

### ISSUE THREAD

**Issue by Mathieu-CdlT** [chemins-de-la-transition/semapps#123]
Question de l’affichage des droits, collecte de cookies… 
Comment ca se passe ? 
Il faudrait au moins qu'on ait un Pop-up accepter / refuser non…  ? 
Y-a-t-il des modèles existants qu'on puisse plugger sur le site ?
Il me semble qu'il y a une obligation légale à avoir ça non ? 

Est ce que quelqu'un sait / a des infos ?

**Comment by srosset81** [comment]
On n'utilise un "cookie" (en fait du local storage, ce qui est équivalent) que pour les acteurs qui se connectent, donc je crois pas qu'un bandeau soit nécessaire sur tout le nécessaire.

Peut-être ajouter un petit message sur https://app.lescheminsdelatransition.org/login ?
