### ISSUE TITLE
Création page partenaires

### ISSUE THREAD

**Issue by Mathieu-CdlT** [chemins-de-la-transition/semapps#124]
C'est un impensé, 
Nous avons besoin de créer un page "Nos partenaires", notamment pour afficher nos partenaires financiers (obligation contractuelle). 
Est ce qu'on peut le faire directement via le back-office en créant une nouvelle page ? On doit mettre au moins leurs logos + peut être un petit texte de présentation  (notamment pour nos partenaires métiers). 
Comment va-t-elle s'afficher sur le front office - en bas de page ? Est ce suffisant ? 
Si on peut le faire via le back office, je veux bien tenter de m'en occuper. 
Merci de vos éclairages

**Comment by srosset81** [comment]
Oui tu peux créer une page depuis le back-office et je peux l'ajouter en bas de page si vous confirmez.

Pour les logos, c'est possible d'insérer des images mais pas de les uploader. Il suffit que tu me les envoies par email et je peux les mettre quelques part sur le serveur.

On pourrait aussi envisager d'ajouter une ressource "Partenaire" et des les afficher dynamiquement sur le site. Cela pourait permettre d'avoir quelque chose de plus clean et plus facilement éditable. Mais cela devrait faire l'objet d'une prestation supplémentaire. Je pense que c'est mieux de voir d'abord si une page simple est suffisante.

**Comment by GuillaumeAV** [comment]
Yop ! c'est pas par mail mais sur un dossier drive, j'imagine que ca marche aussi ;) https://drive.google.com/drive/folders/1_MP9MUvY-3UXk2abSvfAnjytoo1tSpmw?usp=sharing

**Comment by AudreyCDLT** [comment]
J'ai mis sur la homepage les logos des partenaires financiers

**Comment by GuillaumeAV** [comment]
L'idéal serait qu'on puisse afficher sur la homepage des CdlT les organisations (auto-) déclarées comme "est partenaire de"  Chemins de la Transition.

**Comment by srosset81** [comment]
- Créer organisation CDLT dans le backoffice
- Créer organisations partenaires (en uploadant l'image) avec le bon prédicat
- En bas de la homepage, afficher les logos des partenaires de CDLT
