### ISSUE TITLE
Bug carte - la position ne se met pas à jour

### ISSUE THREAD

**Issue by Mathieu-CdlT** [chemins-de-la-transition/semapps#127]
Localisation des lieux / événements… sur la carte

Quand on passe d’un lieu à un autre, la carte reste la même (positionnement du lieu précédent – rien à voir du coup) et ne se repositionne pas sur le nouveau lieu / événement (/parcours ?). 

Ex: 
1. je clique sur le lieu "CDLT Toulouse" --> le positionnement de la carte se met sur l'adresse des CdlT à Tlse. 
2. Ensuite je clique en bas de page sur un lieu similaire suggéré, par exemple le Battement d'Ailes en Corrèze, je suis redirigé sur la page du battement d'ailes, mais la carte reste bloquée sur l'adresse des CDLT Tlse

Idem pour événements.

**Comment by srosset81** [comment]
Je reproduis. Très bizarre... Je regarde ça plus tard.

**Comment by VincentFarcy** [comment]
PR semapps https://github.com/assemblee-virtuelle/semapps/pull/961
