### ISSUE TITLE
Parcours : Renseigner les bonnes object properties et les bons ranges

### ISSUE THREAD

**Issue by GuillaumeAV** [chemins-de-la-transition/semapps#13]
Celles-ci sont listées [aux lignes 22 à 30 de ce tableur](https://docs.google.com/spreadsheets/d/1PacHwzI__5FzYZx1DxD5bFlLDx6MMWfR8-7N6PH9z44/edit?usp=sharing)

Et faire donc en sorte qu'on puisse les éditer dans le formulaire et qu'elles soient affichées en visualisation :)

**Comment by srosset81** [comment]
J'avais pas encore travaillé sur les parcours, c'est pour ça que c'est le bordel ;-)
Mais j'en occupe pas de soucis.

**Comment by GuillaumeAV** [comment]
Génial :D
