### ISSUE TITLE
BACK (Admin) - Affichage événements / parcours

### ISSUE THREAD

**Issue by Mathieu-CdlT** [chemins-de-la-transition/semapps#131]
Dans la config actuelle ne s'affichent que les événements du mois en cours (vue liste). 
Est-il possible d'afficher tous les événements, quelle que soit leur date et non mois par mois (en gardant l'ordre par date) ? Ce serait bien plus pratique. 

Idem, les recherches ne fonctionnent que sur le mois en cours et non pas sur l'ensemble des événements / parcours. Pas pratique à l'utilisation. Possible que le moteur de recherche aille chercher dans l'ensemble des événements / parcours ?

**Comment by srosset81** [comment]
J'ai mis une vue liste par défaut

**Comment by Mathieu-CdlT** [comment]
Oui c'est mieux, moins sexy peut être mais ca fait bien le job et la recherche vient taper dans l'ensemble de la base de donnée. Merci !
