### ISSUE TITLE
BACK (Admin) - Mettre les champs en autocomplétion

### ISSUE THREAD

**Issue by Mathieu-CdlT** [chemins-de-la-transition/semapps#135]
Lors de la création d'un événement, dans l'onglet relations, est demandé le **lieu** auquel est associé l'événement et s'il **fait partie d'**un parcours. Actuellement c'est une liste qui s'affiche. Si demain on a 150 lieux / parcours, ca va vite être compliqué. Possible de mettre de l'autocomplétion avec suggestion des lieux comme c'est le cas pour organisé par ou thématiques? 

Peut être le même cas de figure se pose pour la création d'un lieu ou d'un parcours avec les champs événements.

**Comment by srosset81** [comment]
Utilise le champ AutocompleteInput au lieu de SelectInput
