### ISSUE TITLE
Bug front office - Impossible de renseigner la localisation

### ISSUE THREAD

**Issue by GuillaumeAV** [chemins-de-la-transition/semapps#142]
Via Guillaume Augais [sur discourse](https://forums.lescheminsdelatransition.org/t/bug-impossible-de-remplir-le-champ-localisation/66/2) 

Cette erreur se produit en voulant ajouter un nouveau lieu : lors de la saisie du champs obligatoire ‹ Localisation ›, le navigateur redirige vers une nouvelle page blanche.

Pour reproduire :

En étant connecté, se rendre sur Les Chemins de la Transition
Cliquer sur « Ajouter »
Saisir les premières lettres d’une ville dans le champs « Localisation »
Bug: redirection vers une page blanche.
Je ne peux donc pas créer le nouveau lieu « Atelier du Soleil et du Vent ».

J’essaierai de passer par le backoffice (https://admin.lescheminsdelatransition.org/), après votre accord, pour créer le nouveau lieu en contournant le problème.

**Comment by srosset81** [comment]
Doublon de #169
