### ISSUE TITLE
Problème à l'inscription de nouveaux utilisateurs

### ISSUE THREAD

**Issue by GuillaumeAV** [chemins-de-la-transition/semapps#143]
@srosset81 voici le problème rencontré :)

- J'invite Maxime en tant qu'acteur
- Il reçoit un mail et clique sur le lien, jusqu'ici tout va bien
- Il est invité à se connecter sur lescommuns.org
- Il se connecte avec ses identifiants 
- Il reçoit l'erreur : Requête erronée, acces denied ...  
- Il ne peut pas se connecter à la plateforme ... 

Ce problème a été rencontré avec : 
- maxime@lecoqlibre.fr
- [chloe.cruzel@orange.fr](mailto:chloe.cruzel@orange.fr)

**Comment by srosset81** [comment]
Je reproduis avec mon propre compte acteur (sebastien.rosset@assemblee-virtuelle.org) mais après plusieurs heures de recherches, je n'arrive toujours pas à identifier la cause.

Je me demande si le problème ne vient pas du SSO des Communs...

**Comment by GuillaumeAV** [comment]
Merde c'est horrible ... Je prie pour que ca ne te prenne pas trop d'heures supplémentaires !!

**Comment by srosset81** [comment]
C'est bon, le problème est réglé. Les nouveaux acteurs créés auront automatiquement le droit de modifier leur profil.
J'ai aussi rajouté rétrospectivement les droits de modification de profil sur tous les anciens profils. Vous pouvez l'annoncer à ceux qui avaient un souci.

Background: Normalement un nouvel utilisateur a toujours le droit de modifier son propre profil. Mais comme là on le créé pour quelqu'un d'autre, le fonctionnement est différent. C'est quand même bizarre car les premiers acteurs créés avaient les bons droits, il y a quelque chose qui a dû changer dans SemApps à un moment.

**Comment by GuillaumeAV** [comment]
Hip hip hip ... Merci @srosset81 !!!
