### ISSUE TITLE
Les événéments / parcours passés s'affichent sur le front office

### ISSUE THREAD

**Issue by Mathieu-CdlT** [chemins-de-la-transition/semapps#144]
Les événements et parcours dont les dates sont passées continuent de s'afficher "parfois" lorsqu'on est sur la page événements / parcours. 

--> créée de la pollution à l'affichage et rend les recherches non optimales

**Comment by GuillaumeAV** [comment]
Proposition de Seb & Maxime : 
Proposition: ajouter une case à cocher **[cochée par défaut]** dans les filtres: "N'afficher que les événements à venir", qui serait cochée par défaut.

**Comment by srosset81** [comment]
A confirmer avec @AudreyCDLT , mais on est prêt pour y aller.

Devrait bien aider à améliorer les performances.

**Comment by VincentFarcy** [comment]
Hello @srosset81 

J'ai trouvé comment filtrer les événements dont la date de fin est supérieure à la date du jour :
https://github.com/chemins-de-la-transition/semapps/commit/42ae1886a62ca84e960c889d90ba76b70c8fbc4c 

Cependant, il y 2 points qui me posent problème, et j'aimerais avoir ton avis :

1 - La bibliothèque DataFactory de @rdfjs/data-model ne fonctionne pas avec le filtre passé dans l'URL.
En effet, la property termType est une property définie directement sur un prototype, et elles ne sont pas prises en compte lors du stringify
(https://stackoverflow.com/questions/21732299/javascript-json-stringify-doesnt-handle-prototype-correctly)
Du coup je ne peux pas simplifier la syntaxe.

2 - La bibliothèque sparqljs utilisé dans le dataprovider ne tient pas compte des prefixes lorsqu'on passe un champ en paramètre. Je suis donc obligé de passer la référence complète : source="http://virtual-assembly.org/ontologies/pair#endDate" au lieu de source="pair:endDate".
https://github.com/chemins-de-la-transition/semapps/blob/b7c632692e801b6abe5ca0d40565476e035634b6/frontoffice/src/resources/Activity/Event/EventList.js#L29
Je n'ai pas trouvé comment faire autrement pour le moment.

**Comment by srosset81** [comment]
> 1 - La bibliothèque DataFactory de @rdfjs/data-model ne fonctionne pas avec le filtre passé dans l'URL.
> En effet, la property termType est une property définie directement sur un prototype, et elles ne sont pas prises en compte lors du stringify (https://stackoverflow.com/questions/21732299/javascript-json-stringify-doesnt-handle-prototype-correctly)
> Du coup je ne peux pas simplifier la syntaxe.

Je ne comprends pas bien de quoi tu parles. En effet un objet Javascript ne peut pas toujours être converti en JSON. Mais ça pose quel problème dans ton cas ?

> 2 - La bibliothèque sparqljs utilisé dans le dataprovider ne tient pas compte des prefixes lorsqu'on passe un champ en paramètre. Je suis donc obligé de passer la référence complète : source="http://virtual-assembly.org/ontologies/pair#endDate" au lieu de source="pair:endDate".

Effectivement je constate qu'ils n'ont pas l'intention de gérer les préfixes au niveau du data-model car ils considèrent que c'est trop "high level" (https://github.com/rdfjs/data-model-spec/issues/116). Dommage, mais comme c'est un composant qui sera utilisé pour le moment seulement pour les CDLT, je ne pense pas qu'il est nécessaire d'être trop perfectionnistes.

**Comment by VincentFarcy** [comment]
Pour le 1er point, la requête sparql à besoin d'identifier la nature de chaque item par le termType.
Et cette propriété (définie au niveau du propotype) n'est pas extraite lorsqu'on transforme le json en string pour le passer dans l'url

**Comment by srosset81** [comment]
Ah bizarre, et c'est bloquant ?

Tu es sûr que la librairie data-model ne fournit pas une fonction type `.toString()` ou `.toJSON()` ?

Sinon la fonction [JSON.stringify](https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify) peut prendre une fonction en second argument, ce qui pourrait permettre de parser correctement les objets. De même pour la fonction [JSON.parse](https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Global_Objects/JSON/parse), qui peut faire l'inverse. Mais ça semble compliqué, je me demande s'il n'y a pas une solution plus simple...

**Comment by srosset81** [comment]
Ah j'ai compris, c'est juste que tu peux pas utiliser cette librairie et que tu écris l'objet "à la main".

Du coup c'est pas vraiment bloquant, on peut garder comme ça.

**Comment by VincentFarcy** [comment]
Oui c'est juste pour simplifier la syntaxe.
ok ça marche ;)
