### ISSUE TITLE
Gestion du format photo compliquée

### ISSUE THREAD

**Issue by Mathieu-CdlT** [chemins-de-la-transition/semapps#148]
le format des photos est difficile à gérer : 
difficile d’anticiper ce que ça va donner → chronophage ou mauvais effet sur la fiche. 
→ Possible de pouvoir cadrer la photo au moment de la création de la fiche ? 
→ Possible de choisir l’ordre de l'affichage des photos ? 
→ Possible de régler le cadrage de la photo (format carré) qui s’affiche dans la liste des évènements ? (aléatoire ajd). 

+ Possible de compresser les photos automatiquement (aujourd'hui compression manuelle de la taille des photos) ?

**Comment by GuillaumeAV** [comment]
Doublon avec #243
