### ISSUE TITLE
Pouvoir ajouter une adresse directement sur un événement

### ISSUE THREAD

**Issue by GuillaumeAV** [chemins-de-la-transition/semapps#149]
A l'heure actuelle, il faut créer un lieu pour géolocaliser un événement : Or il y a souvent des événements qui se déroulent en dehors de lieux ayant vocation à être référencés sur les CdlT (ex : la salle communale ...)

Il faudrait pouvoir attribuer une adresse à des événements sans avoir nécessairement besoin de les lier à un lieu ..

**Comment by GuillaumeAV** [comment]
Proposition de Seb : 
Idéalement il faudrait pouvoir ajouter l'adresse à la volée, pex dans une modale.

**Comment by srosset81** [comment]
Proposition: ajouter un champ supplémentaire Localisation

- Utiliser le prédicat `pair:hasLocation`
- Trouver nouveau prédicat pour les régions (`cdlt:hasRegion` ?)

**Comment by lecoqlibre** [comment]
Estimation temps à la louche : 2 à 4h pour la partie back-office.
Je laisse Vincent estimer la partie front.

**Comment by lecoqlibre** [comment]
Je n'arrive pas à utiliser `PairLocationInput`. Probablement lié à #185.

**Comment by VincentFarcy** [comment]
@lecoqlibre ton problème est peut être aussi lié au service `region-tagger.service`.
`par:hasLocation` est écrasé par la région ex : `"pair:hasLocation": "http://localhost:3000/regions/occitanie"`,
Il faudrait remplacer `pair:hasLocation` par `cdlt:hasRegion` dans le service aussi.

**Comment by VincentFarcy** [comment]
Les pb de lenteurs sont gravement accentués avec les 2 relations vers Place
`dereference: ['pair:hostedIn/pair:hasPostalAddress', 'pair:hasLocation/pair:hasPostalAddress'],`
Il faudrait trouver un système pour ne pas avoir à interroger les 2 simultanément.
Par exemple n'utiliser que la relation hasLocation pour la localisation d'un Event,
et mettre à jour hasLocation via un service en cas de création/modification du lien entre un événement et un lieu.
Qu'en pensez-vous ?

**Comment by srosset81** [comment]
Il faut qu'on implémente la solution que tu as trouvée avec `UNION` @VincentFarcy 

Pour `pair:hostedIn`, on a l'`@id` donc on n'est pas obligé de déréférencer. Mais il faudrait un composant `MapList` plus intelligent qui aille fetcher les données. Pas sûr que les performances soient améliorées pour autant.
