### ISSUE TITLE
Adding needs and opportunities

### ISSUE THREAD

**Issue by GuillaumeAV** [chemins-de-la-transition/semapps#152]
## Contexte
De nombreux accueillants et voyageurs auront des offres et des demandes … Il s’agit de faciliter le matching entre l’offre et la demande … Ce qui pourra déclencher des réponses à des besoins … et des voyages sur les CdlT.

## Objectif
* Créer ou utiliser une ontologie Place de marché / Compétences ([pour le moment direct dans l’ontologie CdlT](http://virtual-assembly.org/ontologies/cdlt#OfferAndRequest))
* Ajouter [Offre de compétence](http://virtual-assembly.org/ontologies/cdlt#SkillOffer)
* Ajouter [Demande de formation](http://virtual-assembly.org/ontologies/cdlt#TrainingRequest) (complémentaire ou concurrent avec pair:needsSkill - voir plus haut)
* Ajouter [Appel à compétence](http://virtual-assembly.org/ontologies/cdlt#SkillRequest) dans le cadre de … Projets / lieux / événements, organisations …

Pour les demandes de compétences : Les faire porter sur les LEP
* Ajouter [“Type d’offre ou de demande de compétences”](http://virtual-assembly.org/ontologies/cdlt#typeOfSkillOfferOrRequest) (CDD - CDI - Stage …)
* Ajouter la relation Offre de compétence / Demande de formation / Appel à compétences [hasSkillOfferOrRequestType](http://virtual-assembly.org/ontologies/cdlt#hasSkillOfferOrRequestType) “Skill Offer Or Request Type” ainsi que [sa relation inverse](http://virtual-assembly.org/ontologies/cdlt#typeOfSkillOfferOrRequest)

Puis…
* Contextualiser les Pair:Ressource/Skill avec hasTopic / hasSector / HasBranch / hesDomain ?
* Répliquer le formulaire de contact

**Comment by Mathieu-CdlT** [comment]
Un gros enjeu dans la façon de nommer de cet espace de façon à ce que les utilisateurs (internet) cherchant à s'insérer sur une initiative (job, stage, service civique, prestation) puissent "tomber sur la plateforme". 

L'enjeu porte donc sur quels mots-clé un utilisateur va taper sur internet pour que la plateforme remonte sur les moteurs de recherche. #SEO 

"Espace emploi"? "Emplois"? 
Qu'est ce que vous tapez si vous recherchez un job sur internet ?

**Comment by srosset81** [comment]
Apparemment le mot "Emploi" ou "Offre d'emploi" a du sens: https://jobs.makesense.org/

**Comment by srosset81** [comment]
Mastopod will be ready next spring.

**Comment by Tonfa** [comment]
Specifications for Regen4All of an entity "opportunity" lifecycle that can be a need or an offer (marketplace)

**UX for the needs of the researcher**
1. As a Researcher the first part of the page that I see has an explanation text that explains the difference between research interest (need) and researched community (offer)
2. Then I see a search engine that presents all opportunities (needs & offers) with filtering options (type of research: survey, interview, residence / Field of research: Soil regeneration, water management, natural building)
3. First I check the research communities (offers) if something matches my need already
   - If I find a good match, I contact them by email or the number on their profile. If I don't find a match or matches that I found are unsuccessful, then:
4. I create a need

<table>
    <tr>
        <td>Field of research interest(tick which fields are of special interest to your)</td>
        <td>Have multiple options to pick from, in a scroll down menu. Which will be the same as in the community profile, for easy match.    </td>
    </tr>
    <tr>
        <td>Type of research </td>
        <td>Tick: Quantitative, qualitative, action research etc.   </td>
    </tr>
    <tr>
        <td>Research question and need – what are you asking others to respond to, what is your need? (and this is what people will see)</td>
        <td>Open</td>
    </tr>
    <tr>
        <td>Prior experience with research in communities</td>
        <td>Open </td>
    </tr>
    <tr>
        <td>Potential career implications </td>
        <td>Open</td>
    </tr>
    <tr>
        <td>Community involvement (how much do you expect the community to be involved, what would be the minimum criteria/expectations?)  </td>
        <td>Open</td>
    </tr>
</table>
- Ideally when I create a need:
   - communities fitting the same criterias get an email notification about it to consult and answer
   - for now we do it manually

**UX for the needs of the Researched community**
The same but I'm looking for a Research interest and I'm creating a Researched community offer.
- Ideally when I create an offer:
   - coordinators of the pathways fitting the same criteria get an email notification about it to consult and answer
   - for now, we do it manually

**Comment by AngelMatilla** [comment]
These are project documents with a first attempt at describing how needs and offers can look like from the point of view of a community (specific organization type) and a researcher (specific person type). 

Document communities: https://docs.google.com/document/d/1vHbOYk8JPXs7XMezDv2OmYFqLEBVCiSY51RwSltul3Q/edit?usp=sharing

Document researcher: 
https://docs.google.com/document/d/1IU9ZSgVHvzQyEVqWTIpJScU9RraqaQvVwvMk7LSrxCk/edit?usp=sharing

I will soon review the description provided by Abdul and these documents and I'll provide my comments on them

**Comment by daemuu** [comment]
/!\ Les URLs commencant par http://virtual-assembly.org/ontologies/cdlt ne sont plus accessibles !

**Comment by srosset81** [comment]
Ils ne l'ont jamais été. Mais c'est juste des identifiants, ça ne les empêche pas de fonctionner.
