### ISSUE TITLE
Importer les topics Discourse

### ISSUE THREAD

**Issue by GuillaumeAV** [chemins-de-la-transition/semapps#154]
## Contexte
SemApps et Discourse vont structurer le développement des CdlT. Discourse va notamment accueillir : Les discussions communautaires ; L'ingénierie collaborative de la construction des CLEPs.  
=> Proposition de spécification agile itérative en live et en fonction de notre découverte du champ des possibles … 

## Objectifs
* Sur Discourse : Faire en sorte que les parties prenantes (accueillants / formateurs / voyageurs / organisateurs etc. décrites sur SemApps) d’un CLEP (Chemin, Lieu, Event, Parcours) soient automatiquement invitées à rejoindre l’entrée correspondante du Chemin (thématique) ET du LEP sur Discourse…

* Sur SemApps
Faire en sorte que les premières lignes des derniers messages discourse pourraient apparaître sur les CLEP (Chemin, Lieu, Event, Parcours)
Concernant les Profils : SSO commun et plus si affinités
L’idéal serait que le profil d’une personne soit le même sur les 2 plateformes … On va voir ce que donne le travail du coq libre et à terme le développement des ActivityPods ! 

* Commentaires 
Intégrer des commentaires à la plateforme (affichage sur les LEP)

# Communauté
* Contexte
Les parties prenantes (accueillants / formateurs / voyageurs / organisateurs etc. décrites sur SemApps) d’un LEP pourraient être automatiquement invitées à l’entrée correspondante du LEP ET du Chemin (thématique) sur Discourse…
* Objectif (dépendant du point mentionné plus haut : Intégrer la classe Path)
Inférer :
Si une personne participe à tel LEP, alors, elle fait partie de la communauté du LEP ET de la communauté du chemin concernés.

**Comment by GuillaumeAV** [comment]
from @AudreyCDLT  
La page forum, j'ai ajouté une entrée dans le menu en haut. On peut mettre le lien de votre forum derrière. Il s'ouvrira dans un autre onglet (obligatoire!!!)

Réponse Guillaume : 
Ok ca roule, il faut qu'on voit avec Seb ce qu'il est possible de faire avec le forum, on reviendra ensuite vers toi vers toi éventuellement à ce sujet !

**Comment by srosset81** [comment]
- Faire un truc minimaliste pour tester
- Afficher sujets "Chemins" du Discourse sur la page du Chemin
- Lien vers le Discourse
- Utiliser la classe `pair:Debate`

**Comment by GuillaumeAV** [comment]
C'est génial !! Petites questions .. 

J'ai ajouté un topic dans la catégorie tiers lieux : https://forums.lescheminsdelatransition.org/t/actualiser-le-voyage-a-la-rencontre-des-tiers-lieux-du-bocage-ornais/148
Je m'attendais à ce qu'il remonte comme discussion dans SemApps, mais je ne le vois pas .. En termes de design : Tu affiches la dernière discussion ? Les dernières discussions ? Ou autre chose ?

**Comment by srosset81** [comment]
La synchronisation se fait toutes les nuits, c'est donc normal que ça n'apparaisse pas tout de suite. On pourrait éventuellement faire une synchronisation plus régulière.
Cela dit, la synchronisation de cette nuit n'a pas fonctionné, je regarde pourquoi.

**Comment by GuillaumeAV** [comment]
Ok super, c'est très bien toutes les nuits ! Et du coup ca affiche 1 discussion ou plusieurs discussions quand il y en a plusieurs ?

**Comment by GuillaumeAV** [comment]
A t'as répondu dans le comment - Limit discussions to 5 and sort by creation date - C'est top !

**Comment by srosset81** [comment]
@GuillaumeAV C'est bon, c'est corrigé. Et j'ai forcé une synchro.

**Comment by GuillaumeAV** [comment]
C'est génial merci beaucoup !
