### ISSUE TITLE
Créer un niveau de droit contributeur (en plus d'admin et d'acteur)

### ISSUE THREAD

**Issue by GuillaumeAV** [chemins-de-la-transition/semapps#155]
* Contexte 
On est un peu limité avec le seul profil admin : On donne les clés de la plateforme ou pas grand chose ...

* Objectif
Ajouter un profil contributeur en plus de admin et de acteur dont les droits seront à déterminer (plus tard - à faire ensemble)

**Comment by lecoqlibre** [comment]
Estimation temps à la louche : 4 à 8h.

**Comment by srosset81** [comment]
@Mathieu-CdlT @GuillaumeAV C'est fait et déployé.
On peut maintenant assigner un type "Contributeur" à une personne.
Cette personne a accès au backoffice https://dev.admin.lescheminsdelatransition.org
Pour le moment, elle a le droit de créer des LEPs ou d'éditer les LEPs existants.
Toute autre modification lui est interdite, par contre elle peut voir toutes les ressources.
Dispo pour définir des droits plus précis, selon vos besoins. Ce sera juste une question de config.
