### ISSUE TITLE
Corriger bug sur les filtres

### ISSUE THREAD

**Issue by GuillaumeAV** [chemins-de-la-transition/semapps#159]
Quand je suis sur la liste des lieux, 
* j'applique le filtre "Lieu privé" : La liste de résultat n'est pas actualisée
* j'applique le filtre "type de parcours" : la liste n'est pas actualisée
* j'applique le filtre "thématique"  : la liste n'est pas actualisée

**Comment by srosset81** [comment]
Reproduit, ne marche pas seulement sur la vue "Liste"

**Comment by VincentFarcy** [comment]
Détail du code sparql généré 
[place-filter-sparql.txt](https://github.com/chemins-de-la-transition/semapps/files/8253583/place-filter-sparql.txt)
[course-filter-sparql.txt](https://github.com/chemins-de-la-transition/semapps/files/8253584/course-filter-sparql.txt)

**Comment by VincentFarcy** [comment]
Problème réglé après le passage en V0.4
Temps passé : 4h
