### ISSUE TITLE
Suivi des réservations

### ISSUE THREAD

**Issue by Mathieu-CdlT** [chemins-de-la-transition/semapps#166]
Question du paramétrage de qui est contacté qd on clique sur le bouton contact / réservation. 
1. Initiative + quel mail envoyé ? 
2. CdlT ? 

Ce serait bien que l'initiative puisse recevoir un mail + pour les CdlT génération d'un compte rendu des personnes ayant contacté des initiatives pour avoir des infos sur les LEP (csv?). Avec informations sur la personne contactant l'initiative + objet du contact + initiative contactée & référence du LEP faisant l'objet du contact. 

Cette demande émane d'un besoin de connaitre les flux générés vers les initiatives, l'impact de la plateforme et de pouvoir envoyer des mails (automatiques?) de proposition de don aux personnes ayant bénéficié du service apporté par la plateforme.

**Comment by Mathieu-CdlT** [comment]
Essentiel pour le suivi des relations / impact avec les initiatives et pouvoir faire des points sur les flux générés et proposer des contributions en fonction du CA généré provenant des CdlT #modèle-éco #suivi-impact-plateforme

**Comment by GuillaumeAV** [comment]
On va répondre à ces questions via plusieurs moyens :  
- Mail envoyé à l'initiative (sur inscriptions - pas sur simple contact à l'heure actuelle) + aux CdlT (ok)
- Import des données jotform / stripe dans le backoffice par @srosset81 
- Mise en place d'un matomo avec Data Players ..

**Comment by GuillaumeAV** [comment]
Message de @Mathieu-CdlT : 
On aurait besoin de pouvoir générer du reporting sur le trafic de la plateforme, et en particulier de savoir quelles sont les personnes qui contactent ou s'inscrivent sur des lieux, événements ou voyages - afin de pouvoir faire des points réguliers avec les initiatives présentes sur la plateforme et échafauder notre modèle éco (contributions libres des voyageurs et initiatives) et l'impact de la plateforme auprès des différents partenaires.

On demande aux voyageurs de se créer un profil sur la plateforme avant de pouvoir contacter / ou s'inscrire sur un événement / lieu / voyage. On aura donc leurs coordonnées sur la plateforme.

Comment serait-il possible de générer des tableaux de suivi (type celui en pj)?
Est ce qu'on peut le faire en paramétrant Matomo ?
Est ce qu'on peut le faire depuis SemApps CdlT ?

Ci joint un exemple de rapport (draft) qu'il serait bien que l'on puisse avoir.
Merci de vos lumières....

**Comment by GuillaumeAV** [comment]
Message de @srosset81 

Sur le chat YesWiki, il y a Sebastian (de Gogogcarto) qui vient de recommander https://pipedream.com/ comme un outil de ouf
Je vois que ça permet de passer très facilement d'un webhook à un Google sheet: https://pipedream.com/docs/quickstart/#save-data-to-google-sheets
Ca pourrait être utilisé pour enregistrer des événements de type "User x a contacté Lieu y" ou "User x s'est inscrit à événement Z"
Le bus sémantique pourrait sans doute aussi le faire, mais avec plus de complications et moins de customisations possibles.

**Comment by srosset81** [comment]
Fait ici: https://github.com/chemins-de-la-transition/semapps/pull/520
