### ISSUE TITLE
Gérer les events se déroulant en plusieurs fois

### ISSUE THREAD

**Issue by Mathieu-CdlT** [chemins-de-la-transition/semapps#168]
Nous avons des cas de formations qui se déroulent sur plusieurs week-ends (ex: formation Guide Composteur Humus & Associés).
On ne peut renseigner que la date de début / fin de la formation et le calcul des heures de formation se fait en lien avec ces dates renseignées. Ce qui ne correspond dans la réalité à pas gd chose. 

Comment peut on se débrouiller sur une formation pour renseigner plusieurs dates de formations - sachant que ces formations  ne constituent pas pour autant des parcours ?

**Comment by srosset81** [comment]
J'ai l'impression que ça devrait faire l'objet d'une nouvelle classe, intermédiaire entre Event et Course.
Cela dit... Course = Formation et la propriété principale de la classe Course, c'est d'être une suite d'événements.
On ne pourrait pas juste différencier les Courses "parcours" des Courses "formations" ?

**Comment by srosset81** [comment]
A valider @GuillaumeAV @Mathieu-CdlT

**Comment by srosset81** [comment]
C'est un énorme changement au niveau de l'interface, notamment dans le frontoffice. Il y a presque tout à revoir.

Si c'est aussi validé par @Mathieu-CdlT, il faudra que @AudreyCDLT propose des maquettes.

Je propose de l'enlever du Milestone 2.0 pour le moment.

**Comment by GuillaumeAV** [comment]
Si très compliqué, on pourra plutôt les gérer comme des parcours ..
