### ISSUE TITLE
Ajouter le lieu dans l'affichage vignette d'un événement / parcours

### ISSUE THREAD

**Issue by Mathieu-CdlT** [chemins-de-la-transition/semapps#171]
on nous a fait remonter le fait qu'il était dommage que l'on ne voit pas le lieu, sur l'affichage liste / vignette des événements et parcours. 
Possible de la faire apparaitre ? 
Par avance merci !

**Comment by srosset81** [comment]
@AudreyCDLT besoin d'une validation et d'un design

**Comment by VincentFarcy** [comment]
rq : Pour les parcours on peut avoir plusieurs lieux.
