### ISSUE TITLE
Bug pour l'affichage de la carte sous SemApps v0.4

### ISSUE THREAD

**Issue by srosset81** [chemins-de-la-transition/semapps#183]
Visible ici:
https://dev.app.lescheminsdelatransition.org/Place

`Uncaught Error: No context provided: useLeafletContext() can only be used in a descendant of <MapContainer>`

Même en downgradant react-leaflet (https://github.com/assemblee-virtuelle/semapps/releases/tag/frontend-v0.4.0-alpha.15), le problème persiste.

Cela ne se produit ni si le backoffice, ni en local.

@Mathieu-CdlT @GuillaumeAV J'ai largement dépassé mon temps estimé pour la mise à jour de SemApps, j'aurai besoin d'une confirmation que je peux avoir une rallonge pour continuer à investiguer. Potentiellement je pourrai essayer de downgrader encore à la v3.0.0 de react-leaflet.

**Comment by Mathieu-CdlT** [comment]
Hello Seb, 

J'ai pas accès au lien que tu mets. Perso je ne sais pas de quoi on parle, ni de cette mise à jour de SemApps V0.4. S'agit-il d'un travail uniquement dans le cadre des CdlT ou parle-t-on du logiciel SemApps? 

Question budget, pour ma part, je n'ai aucune visibilité (ce que je déplore) ni ne sais jusqu'où nous pourrons avancer dans le développement des fonctionnalités. Cette plateforme étant **l'outil de travail des CdlT** (dont découlent nos avancées / nos discours envers nos partenaires...), si vous en savez davantage je suis preneur.  

Par ailleurs, je le pose ici même si c'est surement pas l'endroit, mais et surement parce que je découvre le fonctionnement d'une gestion de ce type de projets, il faudra sur l'enveloppe qui vous a été communiquée, isoler une partie du budget pour les corrections / débogages post livraison V2, car on va plus avoir beaucoup de budget par la suite et pas de sources de financement identifiées...

**Comment by srosset81** [comment]
La mise à jour de la plateforme CDLT vers SemApps v0.4 permet de bénéficier des dernières avancées: https://github.com/chemins-de-la-transition/semapps/issues/150

Si tu as un écran blanc en allant sur https://dev.app.lescheminsdelatransition.org/Place, c'est précisément à cause du bug. Le reste des sites https://dev.app.lescheminsdelatransition.org et https://dev.admin.lescheminsdelatransition.org (qui sont sous la v0.4) fonctionnent bien.

Le bug concerne SemApps, mais il ne s'est jamais produit sur d'autres plateformes. Donc il ne sera sans doute pas réglé par d'autres développeurs.

J'avais oublié de donner un temps d'estimation pour le régler: 2h.

Concernant le budget et notre manière de fonctionner, cela sort du sujet de cette issue. Je pense qu'il faut communiquer avec @GuillaumeAV qui a déjà beaucoup d'informations. On a donné un temps d'estimation sur toutes les issues de la milestone 2.0.

**Comment by srosset81** [comment]
C'est bon, le problème est résolu: https://dev.app.lescheminsdelatransition.org/Place

Temps passé: 2h30, facturé 2h
