### ISSUE TITLE
Stabilité de la plateforme (front + back)

### ISSUE THREAD

**Issue by Mathieu-CdlT** [chemins-de-la-transition/semapps#184]
Comment corriger les plantages récurrents de la plateforme V1 ? 
Avec le lancement de la plateforme qui approche, nous sommes dans des démarches quotidiennes de contact de prospects à référencer, de prescripteurs potentiels, acteurs, réseaux ou autres institutionnels. 
Nous avons besoin de pouvoir référencer des LEPs (objectif 150 d'ici à un mois) et qu'à la fois le back et le front soient fonctionnels en l'état. 
Nous avons besoin également de pouvoir présenter la plateforme et que nos prescripteurs puissent en faire de même, à tout moment. 
Si vous avez une solution on est vraiment très preneurs ! 
En vous remerciant par avance :)!

**Comment by srosset81** [comment]
C'est toujours lié à https://github.com/chemins-de-la-transition/semapps/issues/110
Je n'arrive pas à lancer le compactage toutes les nuits. J'ai essayé plusieurs options. Je continue cette semaine.

**Comment by srosset81** [comment]
@Mathieu-CdlT @GuillaumeAV Actuellement on utilise 60% des 50Go de stockage disponible. Donc en ne compactant pas tous les jours, on arrive très vite à la limite. Une solution serait de passer à une machine avec plus d'espaces, ce qui peut se faire en un clic sur OVH:

![Capture d’écran de 2022-03-24 11-05-30](https://user-images.githubusercontent.com/17931931/159893033-0aae850b-9c92-412e-a30d-3672111ae9b7.png)

On doublerait aussi la RAM et la puissance CPU, ce qui pourrait aider aussi pour les performances (https://github.com/chemins-de-la-transition/semapps/issues/145)

Si ça vous semble une bonne idée, dites-le moi et je le fais rapidement.
