### ISSUE TITLE
Problème de sauvegarde/affichage de la localisation d'un "Lieu" ou "Evènement"

### ISSUE THREAD

**Issue by ChloeCruzel** [chemins-de-la-transition/semapps#185]
Depuis ce matin (21/03/22) lorsque je saisis la localisation d'un lieu dans une fiche "Lieu" tant via le back-office que le front-office, elle disparait quelques secondes après l'enregistrement. Les lieux ne peuvent plus être référencés sur la carte. 

Par extension, la localisation d'un "Evénement" n'est pas sauvegardé également. 

Illustration :
![BUG étape 1](https://user-images.githubusercontent.com/102050177/159304781-ac455951-8e47-4358-ae46-d6d29bbd5f49.PNG)
![BUG étape 2](https://user-images.githubusercontent.com/102050177/159304976-e6c55cf2-0f65-4a20-98b3-810eba2e7dc9.PNG)
![BUG étape 3](https://user-images.githubusercontent.com/102050177/159304999-84644b8c-33ac-4f4d-886c-bedb3d23aec2.PNG)

**Comment by VincentFarcy** [comment]
Vérifier en local avec la V0.4 :
La localisation est bien sauvegardée en création et mise à jour, par le backoffice ou le frontoffice.
On retrouve bien la bonne donnée lorsqu'on retourne sur l'élément en lecture ou mise à jour.
La carte en revanche ne se met pas à jour.
Pb de cache ?

**Comment by VincentFarcy** [comment]
Même constat aujourd'hui, la carte n'est pas mise à jour : 
![image](https://user-images.githubusercontent.com/55813208/159906287-4dae2efa-4749-4d1f-b927-41bd433c9c04.png)
![image](https://user-images.githubusercontent.com/55813208/159906374-e3b4a9aa-aa0c-4346-9fc9-627ca85fbec6.png)
![image](https://user-images.githubusercontent.com/55813208/159906441-75d65ebd-4f80-413f-832f-fb4b893a4a3a.png)

**Comment by lecoqlibre** [comment]
De mon côté je n'arrive pas à enregistrer la localisation dans le BO, la donnée n'est pas sauvegardée.

**Comment by VincentFarcy** [comment]
De mon côté tout est ok maintenant.
@lecoqlibre tu parles bien de la localisation d'une ressource Place ?
