### ISSUE TITLE
Connexion utilisateur

### ISSUE THREAD

**Issue by srosset81** [chemins-de-la-transition/semapps#19]
Pour le moment il n'y a pas de connexion utilisateur.

- Est-ce nécessaire ?
- Passe-t-on par le login OIDC Les Communs ?
- Si on crée un profil "Personne", doit-on le différencier des autres "Personnes" qui auraient été créées manuellement ?

**Comment by bouviermullerp** [comment]
Il est nécessaire d'être identifié pour accéfder au back-office (et publier des données).
Il n'est pas nécessaire d'être identifié pour visualiser les évènements (dans un premier temps, peut être que ce paramètre changera dans une prochaine version).

**Comment by srosset81** [comment]
Je précise que mes questions regardent le back-office. Côté front-office, l'authentification sera certainement différente.

- N'importe qui peut-il créer un compte ?
- Doit-on pouvoir créer un compte pour un autre utilisateur ? (a priori pas possible la connexion Les Communs, par contre on peut envisager d'avoir une liste d'email autorisés par exemple)

**Comment by bouviermullerp** [comment]
- Dans un premier temps, seul les créateurs de parcours et les accueillants pourront créer un compte. Il n'est pas possible de créer un compte pour un autre utilisateur, par contre il est possible de créer différents lieux.
Je vais valider avec Guillaume et Mathieu comment on procède pour la création de compte.

**Comment by bouviermullerp** [comment]
Discuté ce jour : La possibilité d'envoyer une invitation de l'interface admin (par email)

**Comment by srosset81** [comment]
> Discuté ce jour : La possibilité d'envoyer une invitation de l'interface admin (par email)
J'ai créé une autre issue sur le sujet puisque techniquement c'est un sujet différent.

La discussion d'hier a aussi porté sur l'interface destinée aux acceuillants.
Comme les acceuillants n'auraient le droit que de créer/modifier des lieux ou des événements, cela ne semble pas pertinent de leur donner accès à tout le backoffice. Cela nous obligerait à filtrer les données qui s'affichent en fonction du type de profil, ce qui n'est pas une mince affaire.
Le plus simple serait de garder un backoffice basique (sans aucun efforts d'UX), accessible uniquement par l'équipe CDLT et les créateurs de parcours, et par contre d'ajouter la possibilité de créer/modifier des lieux ou des événements depuis l'interface "front-office".

Et du coup, si cette direction est validée:
- Il n'y aurait pas de connexion sur le back-office, un mot de passe pourrait suffire dans un premier temps
- On ajouterait bien une connexion sur le front-office, qui pourrait être limitée dans un premier temps aux utilisateurs qui ont été invités (pas de possibilité de s'inscrire sans invitation)

**Comment by GuillaumeAV** [comment]
Je trouve cette approche très pertinente ! Qu'en penses tu @bouviermullerp ?

**Comment by bouviermullerp** [comment]
@GuillaumeAV oui, c'est ce qu'on s'est dit !

**Comment by srosset81** [comment]
@bouviermullerp J'ai besoin de savoir par quels biais les acteurs (les lieux qui proposent des événements) se connecteront sur le frontoffice. Est-ce qu'on va passer par le login OIDC des Communs ?

**Comment by bouviermullerp** [comment]
@srosset81 oui OIDC pour des communs

**Comment by srosset81** [comment]
J'essaie de mieux comprendre les usages autour de la connexion utilisateur. Ce serait important de bien le spécifier afin de pouvoir avancer. Voilà ce que j'ai compris:

**Backoffice** (actuellement sur https://app.lescheminsdelatransition.org)
- On ne peut pas y accéder sans être connecté
- Pour se connecter, il faut avoir un compte sur les communs
- Pour se connecter, il faut que l'utilisateur connecté ait un `pair:UserType` défini (p.ex. "administrateur" ou "modérateur")
- On peut voir la liste des utilisateurs et leur type (administrateur, animateur de lieu, etc.)
- On peut inviter de nouveaux utilisateurs via un formulaire. On y choisi le type d'utilisateur.

**Frontoffice**
- Seuls les "animateurs de lieux" (?) ont un intérêt à se connecter sur le frontoffice
- Il n'y a pas la possibilité de se créer soi-même un compte depuis le frontoffice
- Si on a reçu une invitation (en tant qu'animateur de lieu), on peut se connecter (via les communs) et compléter son profil
- Une fois connecté, on peut éditer son lieu, ajouter des événements ou éditer ses propres événements

Est-ce que vous confirmez @bouviermullerp @AudreyCDLT ?

**Comment by srosset81** [comment]
Il y a aussi des questions autour de l'abonnement HelloAsso: 
Quel est le process autour de ça ? Est-ce que c'est les administrateurs qui invitent manuellement les animateurs de lieux (ou autres) une fois qu'ils sont notifiés de l'abonnement ? Comment gérer l'expiration de l'abonnement ?
Cela peut faire l'objet d'une autre issue éventuellement.

**Comment by srosset81** [comment]
@bouviermullerp Je vois que tu as fait un :+1: sur mon post précédent. Puis-je en conclure que je peux implémenter l'ensemble des points listés ?
Pourrais-tu partager ta/votre vision autour de l'abonnement HelloAsso ? Je crois que ça peut avoir un impact important sur le processus d'inscription et je ne veux pas me lancer sans que ce soit un minimum clair.

**Comment by bouviermullerp** [comment]
@srosset81 OK pour implémenter les points listés. 
Nous allons avoir une discussion demain avec @GuillaumeAV et @Mathieu-CdlT sur le point HelloAsso car dans le cahier des charges, le lien entre les 2 n'était pas acté, nous n'avons pas de cas d'usage précis pour le moment. Je peux t'en dire plus demain en fin d'aprem à ce sujet !

**Comment by srosset81** [comment]
OK ça marche, merci !

**Comment by srosset81** [comment]
> * On ne peut pas y accéder sans être connecté
> * Pour se connecter, il faut avoir un compte sur les communs
> * Pour se connecter, il faut que l'utilisateur connecté ait un `pair:PersonType` défini (p.ex. "administrateur" ou "modérateur")
> * On peut voir la liste des utilisateurs et leur type (administrateur, animateur de lieu, etc.)
> * On peut inviter de nouveaux utilisateurs via un formulaire. On y choisi le type d'utilisateur.

J'ai implémenté tout ça et déployé sur https://app.lescheminsdelatransition.org

Pour l'instant, @bouviermullerp, @GuillaumeAV, @laurecoplo et @J9rem ont accès à ce backoffice. Il faut qu'ils se connectent sur les communs avec leur adresse mail principale (si besoin elle peut être changée dans le backoffice).

**Le backoffice n'est plus accessible aux utilisateurs anonymes ou qui n'ont pas le type "Administrateur"**

Pour ajouter d'autres utilisateurs qui auraient accès au backoffice, il suffit d'aller sur Acteurs > Personnes > Créer ou alors éditer des profils existants et leur ajouter le type "Administrateur".

Pour ajouter d'autres types d'utilisateurs, il suffit d'aller dans Concepts > Types > Créer.
