### ISSUE TITLE
La même requête SPARQL est lancée 2 fois

### ISSUE THREAD

**Issue by srosset81** [chemins-de-la-transition/semapps#190]
Si on va sur https://dev.app.lescheminsdelatransition.org/Event, on constate qu'il y a deux requêtes SPARQL similaires lancées pour récupérer les événements, ce qui doit ralentir les performances.

Peut-être lié au nouveau composant UpcomingFilter ? @VincentFarcy 

A propos de ce composant UpcomingFilter, React m'averti d'un problème au niveau des dépendences du hook `useEffect`

> React Hook useEffect has missing dependencies: 'checked', 'filterValues', 'setFilters', and 'sparqlWhere'. Either include them or remove the dependency array  react-hooks/exhaustive-deps

Mais si j'ajoute les dépendences demandées, ça génère une boucle sans fin.

**Comment by VincentFarcy** [comment]
Le useEffect est là pour n'être lancé qu'une fois.
Si on rajoute les dépendances il va être exécuté à chaque mise à jour des dépendances.
J'ai pas bien pigé le sens du warning pour le moment.

**Comment by srosset81** [comment]
Normalement ces warnings sont assez précis, j'ai toujours réussi à les éliminer.
Si tu ne mets pas une variable en dépendance, c'est possible qu'il y ait des problèmes. Par exemple dans ce cas, si `checked` est à false au premier rendu, puis qu'il est mis à true, alors useEffect ne sera pas appelé.

**Comment by srosset81** [comment]
La différence entre deux requêtes est uniquement cette ligne:

`FILTER(?endDate > "2022-03-31T13:35:35.103Z"^^xsd:dateTime)`

`FILTER(?endDate > "2022-03-31T13:33:22.601Z"^^xsd:dateTime)`

Il y a toujours environ 2 secondes entre chaque appels.
