### ISSUE TITLE
Accès completion profil acteur / organisation depuis le front-office (?)

### ISSUE THREAD

**Issue by Mathieu-CdlT** [chemins-de-la-transition/semapps#194]
Un petit doute / blocage sur accès à la complétion des profils acteurs / organisations de nos partenaires. 
Aujourd'hui, on crée un profil acteur et un lien de connexion s'envoie directement pour que l'acteur créé puisse se connecter au front office et renseigner son lieu et ses événements. En revanche, il me semble qu'il n'est pas possible pour lui de compléter les informations sur son profil acteur ni son profil organisation puisque uniquement accessible via le back office. 
Est-ce que c'est prévu dans la V2, j'ai un doute, car sinon ca signifie que les acteurs n'ont pas accès à leur profil acteur/orga.

**Comment by srosset81** [comment]
Les acteurs sont des utilisateurs comme les autres, donc a priori ils pourront modifier leur profil, tout commes les voyageurs.
