### ISSUE TITLE
Revoir le vocabulaire utilisé pour chaque concept

### ISSUE THREAD

**Issue by VincentFarcy** [chemins-de-la-transition/semapps#202]
En particulier : 
Parcours => Voyage
Thème => Secteur d'activité

Sur le frontoffice / backoffice et mettre à jour le lexique : https://docs.google.com/document/d/1GxTMU5uPyEou5-Juol2Qxvr59Dh3EzAd/edit#heading=h.jl0hootjqcj8

1 - @GuillaumeAV peux-tu faire le tour des termes à modifier ?
2 - @clemenceCDLT peux-tu prendre en charge cette issue ?

**Comment by VincentFarcy** [comment]
autre point à noter en terme de lexique : mentor = intervenant

**Comment by GuillaumeAV** [comment]
En effet; @clemenceCDLT si tu pouvais virer mentor et remplacer par le mot intervenant, ce serait top !

**Comment by clemenceCDLT** [comment]
@GuillaumeAV Oui cette issue est déjà résolue et intégrée dans la branche next
