### ISSUE TITLE
Migration des données suite évolutions milestones 2.0 à 2.2

### ISSUE THREAD

**Issue by VincentFarcy** [chemins-de-la-transition/semapps#207]
**Localisations des événements à partir des lieux en relation**
Suite https://github.com/chemins-de-la-transition/semapps/issues/149 
1 - Migration de hasLocation en hasRegion, à effectuer sur places, events et courses
```
PREFIX cdlt: <http://virtual-assembly.org/ontologies/cdlt#>
PREFIX ldp: <http://www.w3.org/ns/ldp#>
PREFIX pair: <http://virtual-assembly.org/ontologies/pair#>
DELETE {?s ?p ?o}
INSERT {?s cdlt:hasRegion ?o}
WHERE {
  FILTER(?containerUri IN(<http://localhost:3000/events>))
  ?containerUri ldp:contains ?s.
  ?s pair:hasLocation ?o . 
  ?s ?p ?o .
}
```
2 - Il faut initialiser les nouvelles relations hasLocation des événements.
Donnée à utiliser : localisation (hasLocation) du lieu en relation (hostedIn) avec l'événement.

Suite https://github.com/chemins-de-la-transition/semapps/issues/146
Quelques relations pair:organises doivent être renommées en cdlt:organises. 
A vérifier également qu'il n'y a pas de pair:organizedBy à renommer de la même manière.

**Comment by srosset81** [comment]
Fait
