### ISSUE TITLE
Gérer les thèmes et compétences avec Dbpedia 

### ISSUE THREAD

**Issue by GuillaumeAV** [chemins-de-la-transition/semapps#210]
A discuter

**Comment by srosset81** [comment]
- Autocomplétion sur des mots
- Définition du mot
- Vérifier que la version française est complète

**Comment by srosset81** [comment]
Temps passé: 1.5JH au lieu de 7 annoncé ;-)

J'attend les tests sur le backoffice avant d'implémenter aussi côté frontoffice.

**Comment by GuillaumeAV** [comment]
C'est génial !!!

Test côté back-office, sur dev.admin, et admin, sur les personnes et events .. Pas decomplétion esco ou wikidata pour le moment :)

**Comment by srosset81** [comment]
Il faut cliquer d'abord sur "Ajouter ..." tout en bas de la liste de propositions. Ensuite cela affiche la modale qui permet d'importer des données wikidata/ESCO. Voir [ma démo](https://watch.screencastify.com/v/qiA6TsfkmH5WhnuDKHFT).

**Comment by GuillaumeAV** [comment]
Il faudrait idéalement maintenant rendre cliquable les thèmes et compétences et renvoyer vers une page de résultat telle que réalisée  pour le moteur de recherche principal, avec les Personnes, Orgas, Chemins, Lieux, Events, Voyages en onglets ..

**Comment by srosset81** [comment]
Je ferme car ça a bien été ajouté au frontoffice.
