### ISSUE TITLE
Déployer une instance BienvenueChezmoi pour des chantiers communautaires

### ISSUE THREAD

**Issue by GuillaumeAV** [chemins-de-la-transition/semapps#212]
A discuter

**Comment by srosset81** [comment]
- Déployer une instance ActivityPods pour les CDLT @clemenceCDLT 
- Permettre de rendre public les événements
- Réfléchir à interopérabilité avec plateforme CDLT

A voir plus tard

**Comment by GuillaumeAV** [comment]
Interesting of course but irrelevant !
