### ISSUE TITLE
Renommer parcours, sessions, événements

### ISSUE THREAD

**Issue by GuillaumeAV** [chemins-de-la-transition/semapps#22]
Proposition : 

* Remplacer le label "Parcours" par le label "Chemins"
    * Selon Wikipedia, un chemin est une voie,  un passage destiné à la circulation humaine ou animale => Un chemin peut exister sans qu'il n'y ait personne ou qu'il n'y ait des événements, **c'est une infrastructure**.
    * On éviterait du coup l’ambiguïté liée à la polysémie du terme Parcours (dans l'espace / et de formation)
* Remplacer l'URI "Session" par "Course", qui signifie parcours (dans l'espace / et de formation) ; Label : Parcours
   * Parcours : Chemin, trajet **que fait une personne** ou que l’on fait faire à une chose => Un parcours est un événement avec un début, une fin, des gens ...  On peut envisager de parcourir des chemins ... Les parcours sont par ailleurs à la fois des parcours physiques et des parcours de formation
* Remplacer les URI "hasSession" et "sessionOf" par "hasCourse" et "courseOn"
* Remplacer l'URI SessionType par CourseType
* Garder pour le moment événement ...
* Garder la notion de thèmes pour les mots-clés qu'on pourra gérer avec Wikipedia.

**Comment by GuillaumeAV** [comment]
J'ajoute qu'il y a plein de manière de nommer les choses, plein d'options possibles, les langages humains ne sont pas mathématiques, ils sont souvent flous, imprécis, ambigus => les termes qu'on utilise peuvent être polysémiques, faire l'objet d'interprétations, se recouvrir ...
Il faudra donc faire un choix et l'assumer, en sachant qu'on pourrait modéliser la chose autrement, puis l'expliciter, et l'institutionnaliser ...

**Comment by srosset81** [comment]
@GuillaumeAV Peux-tu mettre à jour le fichier OWL ou, encore mieux, créer le repo dédié à l'ontologie ?

**Comment by srosset81** [comment]
J'ai renommé les champs dans https://github.com/chemins-de-la-transition/semapps/pull/31
J'attend que la nouvelle ontologie soit nettoyée pour m'occuper du changement de Course à Session.

**Comment by GuillaumeAV** [comment]
Hola @srosset81 ! Petite question ... 
Est-ce qu'il serait possible, sans créer de nouvelle classe de distinguer : 

- Les événements One Shot, par exemple, un chantier participatif à Oloron,
- Des événements constitutifs d'un parcours ...

De manière : 
- à n'afficher dans la liste des événements que les événements One Shot
- à n'afficher les événements constitutifs d'un parcours que sur les fiches parcours ? 

Peut-être en créant une règle ? Ou via un mécanisme technique dont tu aurais le secret ?
