### ISSUE TITLE
Edition profil personne: Saisie des secteurs d'activité ne marche pas

### ISSUE THREAD

**Issue by GuillaumeAV** [chemins-de-la-transition/semapps#225]
La saisie des secteurs d'activité ne marche pas, comme [sur mon profil](https://dev.app.lescheminsdelatransition.org/Person/https%3A%2F%2Fdev.data.lescheminsdelatransition.org%2Fusers%2Fguillaume-rouyer/1) par exemple.

**Comment by VincentFarcy** [comment]
Il faut d'abord créer un secteur d'activité dans les concepts : https://dev.admin.lescheminsdelatransition.org/Sector
