### ISSUE TITLE
Implémenter une ontologie pour gérer les hébergements

### ISSUE THREAD

**Issue by GuillaumeAV** [chemins-de-la-transition/semapps#23]
### Hébergement
Utiliser la classe nouvellement créée sous "Resource", nommée "Hosting"

**Object properties**
* hasLocation Place
* offeredBy Actor

**Data properties**
* description - Description - Markdown
* beds - Nombre de lits - Une ligne
* campingPlaces - Nombre de places camping - Une ligne
* priceRange - Gamme de prix - Une ligne
* kitchenAcces - Accès cuisine - Une ligne

### Communauté apprenante
Placer sous Acteurs 
Utiliser la classe "Ecosystem"

**Comment by srosset81** [comment]
C'est pour le 15 mars ça ?

Je ne pensais pas que vous alliez déjà ajouter la notion d'hébergement. Pour info on a utilisé cette ontologie pour répertoriez les hébergements d'Oasis (on s'est lancé dans notre propre ontologie car @bouviermullerp nous avait dit à l'époque que le répertoriage des hébergements n'était pas une priorité pour les CDLT):

```
{
  type: "oasis:HostingService",
  oasis:bookingUrl: "http://www.lechateaupartage.fr/prestations-tarifs/",
  oasis:image: "https://colibris.social/files/montfranc_johanbarrot_dji_final-e1605546466528.jpg",
  oasis:maxCapacity: 15,
  oasis:minCapacity: 1,
  oasis:price: "Nuitée 25€/personne, location en gestion libre 1 nuit 450€, location salle de réunion 80€/jour",
  pair:description: "Sur les hauteurs du lac d'Aiguebelette, le Château partagé est un habitat groupế...",
  pair:hasType: [
    "https://colibris.social/hosting-services-types/locations-de-salles-pour-stages",
    "https://colibris.social/hosting-services-types/gites",
    "https://colibris.social/hosting-services-types/chambres-d-hotes"
  ],
  pair:label: "Venez découvrir le Château d'Arvieu",
  pair:offeredBy
}
```

Visible ici https://colibris.social/hosting-services.

`hasLocation` c'est un lien vers un [Lieu](https://app.lescheminsdelatransition.org/#/Place) déjà répertortié, ou bien c'est une adresse créée à la volée ? Les deux sont possibles, mais la première solution oblige à d'abord créer le lieu, puis à créer l'hébergement, tandis que la seconde est plus direct (on entre l'adresse et voilà).

`kitchenAcces` c'est plutôt `kitchenAccess`.

Il me faudrait aussi l'ontologie pour tout ça...

Pour **communauté apprenante** (entre paranthèse ça aurait été mieux de faire une issue à part), je dois connaître les liens avec les autres ressources.

**Comment by GuillaumeAV** [comment]
Doubloon, je ferme
