### ISSUE TITLE
"Mes intentions en tant que" ne marchent pas ..

### ISSUE THREAD

**Issue by GuillaumeAV** [chemins-de-la-transition/semapps#230]
Elles semblent ne pas s'enregistrer, et ne s'affichent donc pas en lecture ... [Exemple sur mon profil](https://dev.app.lescheminsdelatransition.org/Person/https%3A%2F%2Fdev.data.lescheminsdelatransition.org%2Fusers%2Fguillaume-rouyer/show).

**Comment by VincentFarcy** [comment]
Il faut d'abord créer des intentions dans les concepts : https://dev.admin.lescheminsdelatransition.org/Intention

**Comment by GuillaumeAV** [comment]
Ok je comprends mieux ... 

Comme je te disais, voici les data properties à utiliser pour les intentions (qui ne se confondent pas avec la classe intention de l'ontologie PAIR) : 
- http://virtual-assembly.org/ontologies/cdlt#asAHostIntentions
- http://virtual-assembly.org/ontologies/cdlt#asAMentorIntentions
- http://virtual-assembly.org/ontologies/cdlt#asAnOrganiserIntentions
- http://virtual-assembly.org/ontologies/cdlt#asATravelerIntentions
=> Un simple champ texte suffira ! 

On peut cependant réutiliser le travail que tu as fait avec intentions en proposant aux gens de renseigner leurs finalité : 

Dans PAIR, on a http://virtual-assembly.org/ontologies/pair#Intention qui est une supe classe contenant 
- http://virtual-assembly.org/ontologies/pair#Finality
- http://virtual-assembly.org/ontologies/pair#Challenge
- http://virtual-assembly.org/ontologies/pair/Mean

Option 1 :
- Utiliser "Acteur" [http://virtual-assembly.org/ontologies/pair#aims] http://virtual-assembly.org/ontologies/pair#Finality et pointer vers une liste controlée de finalités (en remplacement de "intention et Vincent .." Ces finalités pourraien être les 17 Objectifs du Développement Durable ou mieux .. 

Option 2 : 
On va plus loin et pon permet aux gens de renseigner : leurs finalités mais également leurs enjeux (http://virtual-assembly.org/ontologies/pair#Challenge) et leurs pratiques (http://virtual-assembly.org/ontologies/pair/Mean). 

Option 3 : 
On crée également les liens et liens inverses entre finalités, enjeux, pratiques 

On s'appelle pour clarifier si besoin !

**Comment by VincentFarcy** [comment]
Suite échange avec Guillaume :

On part sur l'option 1, avec affichage des finalités dans le bandeau de droite des LEV. 
+ affichage de la liste des LEF filtrés lors du click sur la finalité dans ce même bandeau. 

Rq @GuillaumeAV : Ca veut aussi dire qu'il faut ajouter la finalité dans les LEV. Tu confirmes ?

**Comment by VincentFarcy** [comment]
Vu avec Guillaume : on en profite pour faire pointer les éléments du bandeau des CLEV vers la liste de résultats communes plutôt que les listes spécifiques.
