### ISSUE TITLE
Les liens "est organisateur de" / "est mentor pour" renvoient vers des pages vides ..

### ISSUE THREAD

**Issue by GuillaumeAV** [chemins-de-la-transition/semapps#231]
[Exemple à partir de mon profil ... ](https://dev.app.lescheminsdelatransition.org/Person/https%3A%2F%2Fdev.data.lescheminsdelatransition.org%2Fusers%2Fguillaume-rouyer/show)

**Comment by VincentFarcy** [comment]
Correction effectuée (pull request en cours)
