### ISSUE TITLE
Améliorer la gestion des photos

### ISSUE THREAD

**Issue by GuillaumeAV** [chemins-de-la-transition/semapps#243]
La gestion des photos reste aléatoire, forme bandeau, pas de possibilité de réglages + question affichage vignette
Proposer un service gratuit et fiable ?
Problème cependant du responsive... @[audreycoudrin.pro@gmail.com](mailto:audreycoudrin.pro@gmail.com) t'as une solution ?

**Comment by AudreyCDLT** [comment]
@GuillaumeAV De quelle partie parles tu? je ne comprends pas cette issue. Merci de préciser.

**Comment by GuillaumeAV** [comment]
Euuh, il faut voir avec @Mathieu-CdlT et Chloé qui rencontrent ce problème quand ils saisissent des données : J'imagine que ca concerne les photos des profisl lieux, chemin, event, voyage ..

**Comment by AudreyCDLT** [comment]
@Mathieu-CdlT pourrais tu préciser quel est le Problème / besoin. je ne comprends pas cette tâche. merci

**Comment by Mathieu-CdlT** [comment]
Hello, 

La question des photos concerne l'affichage des photos en format vignette sur les listes (LEP). 
le format sur la page détail des photos est plutot "paysage allongé" alors que sur les vignettes (liste LEP) on est sur un format carré. 
Le hic, c'est que les vignettes viennent récupérer les images des pages détails et que du coup l'affichage est "mauvais". 
Du coup, ce qu'on fait avec Chloé, c'est qu'on fait des montages photos pour que l'affichage soit bon à la fois sur fiche détail et sur présentation. Mais ce n'est pas tenable car (1) ca nous prend bcp de tps et (2) les initiatives qui saisiront des données ne s’embêteront pas à faire ça...
Je me souviens plus comment ca se passe en version tel. 
J'espère que ça éclaire..
Exemple de Picojoule pour que la vignette soit à peu près propre : 
![Capture](https://user-images.githubusercontent.com/61470357/171852295-e842887b-d22c-4f00-a5ea-ca3fc6626665.PNG)
.

**Comment by Mathieu-CdlT** [comment]
+ Y'avait le sujet de la taille des photos et de trouver un système pour qu'elles puissent être compressées (200Ko) et qu'on n'ait pas des photos de 2Mo à stocker.. Mais sais pas si c'est la même issue. @GuillaumeAV

**Comment by AudreyCDLT** [comment]
Salut à tous les deux

Je vois ce que tu veux dire. Il n'y a pas besoin de faire un crop manuel
comme vous le faites, il s'agit simplement d'une façon d'afficher les
images dans le code.  CF pièce jointe, tu vois les marcheurs dans l'image
d'en haut est cropée en hauteur et elle s'étend sur la largeur, alors que
dans le format carré dessous, elle retrouve son format initial. Clémence
peut être mieux expliquer que moi. Il s'agit de dire à l'image de s'adapter
en largeur (sans l'étirer bien sur).

De ce côté il s'agit d'un bug à résoudre niveau dev.

[image: Capture d’écran 2022-06-03 à 14.39.53.png]

Le ven. 3 juin 2022 à 14:20, Mathieu-CdlT ***@***.***> a
écrit :
