### ISSUE TITLE
N'afficher que les partenaires institutionnels sur la homepage

### ISSUE THREAD

**Issue by GuillaumeAV** [chemins-de-la-transition/semapps#245]
Différencier partenaires institutionnels / financier des partenaires métiers référencés sur la plateforme + lien vers fiche orga 
Puis renvoyer vers une page "Tous les partenaires" : Affichage logos organisations partenaires métier (en petit) / ou sur une page dédiée ?

Comment les distinguer ? Peut être une classe dédiée au partenariats ? Utiliser organisationType ?

**Comment by clemenceCDLT** [comment]
Vu avec Mathieu : 
Sur la homepage : "Avec le soutien de : Nos partenaires financiers" + manuellement les logos des partenaires financiers
Et en-dessous : "Nos partenaires métiers :" et liste des partenaires métiers que l'on peut slider (partenaires indiqués dans les données) + personnaliser pour mettre celui que l'on veut en premier/deuxième
