### ISSUE TITLE
BUG Search/filtre et nomage filtre

### ISSUE THREAD

**Issue by AudreyCDLT** [chemins-de-la-transition/semapps#258]
- Attention les noms des filtres ne sont pas similaires dans la homepage et dans les pages/ (lieux, evenements, voyages)

L'un s'appelle "thématique" sur la Homepage, l'autre s'appelle "secteur d'activité". Merci d'uniformiser pour que l'on ne perde pas l'utilisateur. DIT ETRE IDENTIQUE ICI: (homepage filtre / filtre pages listes / pages détails bandeau + bloc jaune à droite)

- Est-ce volontaire de ne pas avoir mis le filtre date sur la homepage? Je trouve ça dommage. Plus que la recherche libre, les gens veulent chercher sur une période donnée. (même priorité que de faire du multi select pour moi)

<img width="480" alt="Capture d’écran 2022-05-22 à 11 46 17" src="https://user-images.githubusercontent.com/85290395/169689524-3868e4d1-4c17-4236-9ce4-b992e8271cfc.png">
<img width="1289" alt="Capture d’écran 2022-05-22 à 11 46 23" src="https://user-images.githubusercontent.com/85290395/169689525-4b5884b7-5e15-402e-94c0-92746a35f8f2.png">
)

**Comment by srosset81** [comment]
Il faut regarder sur la version dev, c'est celle-ci qui est à jour:
https://dev.app.lescheminsdelatransition.org/
On a bien "Secteur d'activité".

> Est-ce volontaire de ne pas avoir mis le filtre date sur la homepage? Je trouve ça dommage. Plus que la recherche libre, les gens veulent chercher sur une période donnée. (même priorité que de faire du multi select pour moi)

Répondu ici https://github.com/chemins-de-la-transition/semapps/issues/259

**Comment by GuillaumeAV** [comment]
Huum je croyais que c'était diificile d'ajouter le filtre date (mais en fait ca devait être chose qui était difficile dan la proposiion d'earch d'Audrey) ... Si ce n'est pas difficile, en effet, ca peut avoir beaucoup de valeur ajoutée pour les utilisateurs ! 
J'ai créé une issue : #275

**Comment by srosset81** [comment]
Oui c'est difficile. Et c'est ce que j'ai dit.
