### ISSUE TITLE
BUG Taille image sur la homepage

### ISSUE THREAD

**Issue by AudreyCDLT** [chemins-de-la-transition/semapps#260]
Peu importe la taille de l'écran (sauf mobile) l'image est proportionnelle et garde 40 px a gauche et droite par rapport au bord de l'écran. CF image ci dessous. 
<img width="771" alt="Capture d’écran 2022-05-22 à 12 05 44" src="https://user-images.githubusercontent.com/85290395/169690232-4a0d9e56-53e6-4247-8bae-d01720197c33.png">

**Comment by srosset81** [comment]
A faire: ajouter une marge de 40px (0px en taille xs)

**Comment by srosset81** [comment]
Fait ici #272
