### ISSUE TITLE
Bug sur adresses Organisations 

### ISSUE THREAD

**Issue by GuillaumeAV** [chemins-de-la-transition/semapps#264]
L'adresse disparait quand on édite à nouveau ..

**Comment by VincentFarcy** [comment]
non reproduit ni en local, ni en dev
j'ai pu modifier l'adresse une fois en prod 
https://admin.lescheminsdelatransition.org/Organization/https%3A%2F%2Fdata.lescheminsdelatransition.org%2Forganizations%2Fpicojoule
Le problème n'est donc pas systématique
on voit bien les data modifiés dans la requête PUT :

**Comment by VincentFarcy** [comment]
Le pb est le même avec un autre champ (description par exemple).
Je pense plutôt à un pb de droits.

**Comment by VincentFarcy** [comment]
Quand on clique sur permissions : 
![image](https://user-images.githubusercontent.com/55813208/171125029-0d7b34d3-f752-461f-8952-6bb872d7e540.png)

**Comment by VincentFarcy** [comment]
dans la console quand on clique sur permissions : `GET https://data.lescheminsdelatransition.org/users/juliette-roziere 404`

**Comment by srosset81** [comment]
L'utilisateur https://data.lescheminsdelatransition.org/users/juliette-roziere a été effacé, puis un nouveau compte a été créé pour https://data.lescheminsdelatransition.org/users/juliette-rozieres (avec un S final). Je crois qu'on gère mal l'effaçage des utilisateurs, car c'est quelque chose qui ne se produit pas.

**Comment by srosset81** [comment]
Je crois pas que ce soit lié au problème d'adresse tout ça...

**Comment by srosset81** [comment]
@VincentFarcy J'ai fait une migration pour supprimer l'utilisateur https://data.lescheminsdelatransition.org/users/juliette-roziere des ACLs. Pour régler l'issue à long terme, j'ai fait une issue sur SemApps: https://github.com/assemblee-virtuelle/semapps/issues/982

Je vais jeter un coup d'oeil à ce problème d'adresse.

**Comment by VincentFarcy** [comment]
Pour moi il n'y a pas de pb d'adresse, c'est juste le user en 404 qui pose pb

**Comment by srosset81** [comment]
Il n'y a plus de 404 maintenant mais pourtant c'est toujours impossible de mettre à jour Picojoule :-/
Les autres organisations semblent marcher bien...
J'ai l'impression que le problème est au niveau de la requête SPARQL générées par l'opération PUT, j'investigue

**Comment by srosset81** [comment]
Il y a un problème au niveau des données: `cdlt:hasRegion` ne devrait indiquer que l'URI de la région, mais là il comprend l'adresse complète. Si je vire manuellement `cdlt:hasRegion`, l'édition marche à nouveau !

**Comment by srosset81** [comment]
C'est quand on a fait la migration de l'adresse des events, ça a impacté les organisations aussi:
```
await this.actions.replacePredicate({ oldPredicate: 'http://virtual-assembly.org/ontologies/pair#hasLocation', newPredicate: 'http://virtual-assembly.org/ontologies/cdlt#hasRegion' }, { parentCtx: ctx });
```
J'abais ouvlié que les organisations utilisaient aussi pair:hasLocation.

**Comment by srosset81** [comment]
C'est bon. j'ai corrigé en supprimant `cdlt:hasRegion` pour les organisations. Tout semble marcher correctement maintenant.
