### ISSUE TITLE
Remplacer Topic par Sector dans le code 

### ISSUE THREAD

**Issue by GuillaumeAV** [chemins-de-la-transition/semapps#265]
Une quarantaine de compposants concernés ..

**Comment by VincentFarcy** [comment]
Avant d'intervenir, j'aurais besoin de confirmer la situation attendue pour les ressources concernées :

Ressources concernées :

pair:Theme
----------
libellé => Sujet
relation utilisée => pair:hasTopic

pair:Sector
-----------
libellé => Secteur d'activité
relation utilisée => pair:hasSector


Relations avec ces ressources :

Person et Organization
----------------------
'pair:hasTopic': 'A pour intérêt'
'pair:hasSector': 'Secteurs d'activité'

Event, Course, Place, Path
--------------------------
'pair:hasSector': 'Secteurs d'activité'


@GuillaumeAV ?

**Comment by srosset81** [comment]
@VincentFarcy Guillaume a fait les corrections directement dans ton commentaire, je sais pas si tu l'as vu (c'est pas forcément une bonne pratique @GuillaumeAV)

**Comment by VincentFarcy** [comment]
oui on en a parlé par téléphone. XD
Je remodifie avec l'original

**Comment by VincentFarcy** [comment]
Suite à notre échange @GuillaumeAV voici une version actualisée : 
Ressources concernées :

pair:Theme  => **pair:Topic** (!)
----------
- libellé => **Centre d'intérêt** (en attente de confirmation)
- relation utilisée => pair:hasTopic

pair:Sector
-----------
- libellé => Secteur d'activité
- relation utilisée => pair:hasSector


Relations avec ces ressources :

Person et Organization
----------------------
- 'pair:hasTopic': **A pour centres d'intérêt** (en attente de confirmation)
- 'pair:hasSector': 'Secteurs d'activité'

Event, Course, Place, Path
--------------------------
**- 'pair:hasTopic': A pour centres d'intérêt** (libellé en attente de confirmation)
- 'pair:hasSector': 'Secteurs d'activité'

**Comment by VincentFarcy** [comment]
@srosset J'aimerais avoir ton avis sur cette issue.
il s'agirait non seulement de remplacer des hasTopic par hasSector mais également de remplacer pair:Theme par pair:Topic (et donc pour bien faire ThemesInput par TopicsInput ...).
Rien de compliqué à priori mais assez long et nécessite une bonne communication pour éviter de réutiliser les anciennes notions sur des branches en cours.
Et il y aura probablement des migrations.
Je pense que c'est jouable mais chronophage. Qu'en penses-tu ?

**Comment by srosset81** [comment]
@VincentFarcy Pour moi c'est un truc qui n'a aucun intérêt pour l'utilisateur (le changement ne sera pas visible), et par contre source de beaucoup de bugs. Je le ferai plutôt après le 14, quand on a le temps, afin de préserver de l'énergie pour ce qui est important, et notamment le fix de bugs qui vont apparaître.

**Comment by VincentFarcy** [comment]
ok je propose donc de mettre cette issue en standby, et de créer une autre issue pour quelques points visibles : J'ai repéré quelques meli melo entre les 2 notions.

**Comment by VincentFarcy** [comment]
Je suis en phase. 
je pense que @GuillaumeAV a confondu cette issue avec celle ci qui est traitée : https://github.com/chemins-de-la-transition/semapps/issues/296

**Comment by VincentFarcy** [comment]
Oui c'est bien ça.
Il y aussi le concept Theme à remplacer par Topic et la migration des données

**Comment by srosset81** [comment]
Je m'occupe de faire la migration Theme->Topic histoire de pouvoir clôre la PR de Clémence (https://github.com/chemins-de-la-transition/semapps/pull/450)

**Comment by srosset81** [comment]
Done
