### ISSUE TITLE
Créer des formulaires types

### ISSUE THREAD

**Issue by GuillaumeAV** [chemins-de-la-transition/semapps#266]
pour le jotform

**Comment by Mathieu-CdlT** [comment]
Quand les utilisateurs veulent s'inscrire sur un événement, il faudrait que les organisations publiant des événements puissent choisir si elles veulent être contactées par mail ou qu'elles aient une possibilité de renvoi directement sur leur formulaire interne de réservation (+ suivi pour les CdlT - nom /prénom/mail).

**Comment by GuillaumeAV** [comment]
On a réglé le problème, on passe systématiquement par un formulaire de contact .. Je ferme !
