### ISSUE TITLE
Afficher les relations des Thèmes et Compétences

### ISSUE THREAD

**Issue by GuillaumeAV** [chemins-de-la-transition/semapps#27]
Quand on clique sur un thème ou sur une compétence, il faudrait pouvoir identifier les relations avec les Acteurs, Chemins, Parcours 

A l'heure actuelle, il n'y a aucune relation..

**Thème** "a pour intérêt / theme" Personne / Organisation  / Chemin / Parcours / Lieu
**Compétence** skillOf Personne | producedBy Chemin / Parcours

**Comment by srosset81** [comment]
Le problème que je vois est UX. 
Si on mets tout dans la colonne de droite ce sera laid et peu lisible. Je proposerai de mettre que les acteurs (Person et Organizations) dans la colonne de droite, et le reste (Parcours, Lieux, Chemins) dans la colonne principale, de la même manière qu'on affiche les Sessions dans la page Parcours:

![Capture d’écran de 2021-03-10 16-19-57](https://user-images.githubusercontent.com/17931931/110652285-84fdea80-81bc-11eb-9f0e-a8f95c8f5a9a.png)
