### ISSUE TITLE
Pouvoir ne renseigner qu'un nom d'utilisateur (et pas nécessairement nom - prénom) 

### ISSUE THREAD

**Issue by GuillaumeAV** [chemins-de-la-transition/semapps#274]
Important pour permettre de conserver un relatif anonymat : 
On peut envisager d'utiliser  : http://virtual-assembly.org/ontologies/pair#alternativeLabel 
Ou de créer pair:username... (Bizarre qu'on ne l'ait pas déja ..) 
CF https://github.com/assemblee-virtuelle/pair/issues/191

**Comment by VincentFarcy** [comment]
Donc la règle pour afficher le libellé d'un user **partout** sur le site serait : 
Si j'ai un alternativeLabel je l'utilise, sinon j'affiche prénom + nom
@GuillaumeAV  ?

**Comment by GuillaumeAV** [comment]
Oui c'est bien ça !

**Comment by srosset81** [comment]
> Donc la règle pour afficher le libellé d'un user **partout** sur le site serait : Si j'ai un alternativeLabel je l'utilise, sinon j'affiche prénom + nom @GuillaumeAV ?

C'est mieux d'utiliser `pair:label` partout et de compiler `pair:label` à l'édition. C'est ce qu'on fait actuellement.

![Capture d’écran de 2022-06-02 10-21-42](https://user-images.githubusercontent.com/17931931/171587190-6cdc53c2-e64a-49af-aaaa-4801a679aebc.png)

**Comment by GuillaumeAV** [comment]
Au passage, dans SOLID ou AP, on a pas une notion de Nom d'utilisateur ?

**Comment by VincentFarcy** [comment]
C'est bien ce que j'ai prévu @srosset81 : 
 Si j'ai un alternativeLabel je l'utilise pour valoriser pair:label, sinon je valorise pair:label avec prénom + nom
Je ne vois pas de nécessité de rendre obligatoire le nom d'utilisateur avec ce système.
Préviens moi en cas de changement @GuillaumeAV
