### ISSUE TITLE
Bug création de profil personne - URGENT

### ISSUE THREAD

**Issue by Mathieu-CdlT** [chemins-de-la-transition/semapps#276]
Hello, petit problème de mon coté pour inscrire une nouvelle personne sur la plateforme : 
Personne : Juliette ROZIERES - mail: ecrire@picojoule.org
Organisation : PicoJoule
Un premier profil personne (acteur) a été été créé sur la backOffice. A priori, cette personne n’a pas reçu le mail. Suite à ça, je l’ai accompagné à l’inscription sur la plateforme via les Communs / S’enregistrer. 
On a repris les éléments renseignés sur son profil (back) + elle a créé un mot de passe → message de non autorisation à se connecter 
J’ai supprimé son profil, recréé le même profil, elle n’a pas reçu le mail de confirmation et ne peut toujours pas se connecter. 
Comment peut on solutionner ce problème? On a un besoin urgent de pouvoir référencer ce futur partenaire

**Comment by Mathieu-CdlT** [comment]
Est-il  possible de recréer une fiche profil identique après avoir supprimé le profil de la personne sans que ca ne pose de problèmes ? 
Comment peut on récupérer les infos envoyées / accompagner nos partenaires dans la création d’un profil en cas de bug - c’est pas la première fois que ca nous arrive.

**Comment by srosset81** [comment]
Dans l'état actuel des choses, je ne vois aucun compte avec l'email ecrire@picojoule.org
Par contre il y a bien l'utilisateur https://admin.lescheminsdelatransition.org/Person/https%3A%2F%2Fdata.lescheminsdelatransition.org%2Fusers%2Fjuliette-rozieres/show
Je vais regarder, une régression a dû être introduite sur au dernier déploiement.
