### ISSUE TITLE
Intervertir Cdlt.org et app.cdlt.org

### ISSUE THREAD

**Issue by GuillaumeAV** [chemins-de-la-transition/semapps#287]

**Comment by srosset81** [comment]
Qui s'occupe de ça ? Quand ?
Il faut prévoir de le faire 24h (voir 48h) en avance pour être sûr que tout le monde ait un DNS à jour.

**Comment by srosset81** [comment]
@GuillaumeAV @Mathieu-CdlT 
Questions urgentes à répondre SVP

**Comment by srosset81** [comment]
Est-ce que cela signifie que le site https://lescheminsdelatransition.org ne sera plus visible par personne ?

**Comment by GuillaumeAV** [comment]
Oui ! 
Ou peut-être decouvrir.lescheminsdelatransition.org ? - Je vois avec mathieu et on te dit !

Merci @srosset81 pour ta vigilance, on peut basculer d'ici dimanche du coup ?

**Comment by GuillaumeAV** [comment]
On vient de se mettre d'accord sur projet !

**Comment by srosset81** [comment]
> Merci @srosset81 pour ta vigilance, on peut basculer d'ici dimanche du coup ?

Je pense que c'est bon si la bascule se fait lundi, si la présentation est mardi à 18h (?)
Attention, ça veut dire qu'à partir de lundi, certaines personnes verront déjà le nouveau site (pour éviter ça, on aurait pu mettre une sorte de countdown sur la plateforme elle-même mais là c'est trop tard)

> On vient de se mettre d'accord sur projet !

OK ! Je pourrai faire le switch DNS côté OVH, par contre pour le Wordpress il faudra sans doute renseigner quelque part la nouvelle adresse, mais j'imagine que @clemenceCDLT saura faire ça.

**Comment by srosset81** [comment]
Oui c'est ce qu'il a dit ailleurs

**Comment by srosset81** [comment]
Le switch est fait ! https://lescheminsdelatransition.org devrait rediriger sur la plateforme d'ici à une heure ou deux (ou plus selon votre provider)
https://app.lescheminsdelatransition.org continuera à rediriger vers la plateforme pour le moment.
J'ai aussi remplacé https://dev.app.lescheminsdelatransition.org par https://dev.lescheminsdelatransition.org
Restera donc à ce que @clemenceCDLT configure le Wordpress pour qu'il utilise le nouveau domaine https://projet.lescheminsdelatransition.org (déjà configuré dans le DNS)

**Comment by srosset81** [comment]
@clemenceCDLT J'ai tenté de configurer le domaine https://projet.lescheminsdelatransition.org/ depuis la console OVH mais ça ne marche pas, en tout cas pour le moment
https://www.ovh.com/manager/web/#/hosting/lescheminsdelatransition.org/multisite

**Comment by GuillaumeAV** [comment]
Et il faudrait également mettre le lien à jour sur les endroits ou il est présent dans la plateforme:)

**Comment by clemenceCDLT** [comment]
@srosset81 J'ai généré le certificat SSL mais la redirection vers le site wordpress ne fonctionne pas, ça redirige toujours vers la plateforme alors qu'il y a bien la bonne redirection vers le serveur wordpress sur OVH...

**Comment by srosset81** [comment]
Ca m'a l'air bon, merci. J'ai fixé le lien vers le don.
