### ISSUE TITLE
Bug menu ancre (design pas ok)

### ISSUE THREAD

**Issue by AudreyCDLT** [chemins-de-la-transition/semapps#304]
Le menu gris est un menu ancre qui permet de naviguer facilement dans la page. Lorsqu'on se situe sur une partie, le menu doit être souligné (etat actif) Voir PJ pour exemple et figma pour design précis.
<img width="708" alt="Capture d’écran 2022-06-03 à 07 30 30" src="https://user-images.githubusercontent.com/85290395/171792728-01bfbc81-260e-4677-9523-ce6420ba564a.png">

**Comment by srosset81** [comment]
Ce n'est pas un bug mais une simplification. Souligner les menus au fur et à mesure qu'on scrolle n'est pas évident. Pas faisable avant le 14 en tout cas.
