### ISSUE TITLE
Redirections pages

### ISSUE THREAD

**Issue by clemenceCDLT** [chemins-de-la-transition/semapps#307]
- Quand on modifie un LEV depuis le front et qu'on sauvegarde on arrive sur une liste alors qu'on aimerait arriver sur la lecture du LEV
- Quand on clique sur un lev à partir de la liste de nos lev, on arrive en édition, sans pouvoir rebasculer en mode lecture

**Comment by clemenceCDLT** [comment]
@GuillaumeAV pour le deuxième cas, je ne le vois pas. Est-ce que tu parles bien de quand on a les 3 menus en liste LEV et que l'on clique sur un événement/lieu/voyage ?

**Comment by GuillaumeAV** [comment]
T'as raison, je ne vois pas le 2ème cas non plus @clemenceCDLT laisse tomber donc :)
