### ISSUE TITLE
Secteurs d'activité

### ISSUE THREAD

**Issue by Mathieu-CdlT** [chemins-de-la-transition/semapps#313]
Les secteurs d'activité ne doivent regrouper que les catégories thématiques telles que définies initialement. 
Dans la version dev, il semble que d'autres secteurs aient été ajouté en autocomplétion, ils doivent rester fixes (filtres...). Un petit bug s'est glissé par là.
![Capture](https://user-images.githubusercontent.com/61470357/172125473-523824b3-5fd8-4f78-80b1-c2e1b5a4696b.PNG)

**Comment by srosset81** [comment]
J'assigne @VincentFarcy puisqu'il semble être sur le coup
A voir si c'est aussi le cas pour les données de prod...

**Comment by Mathieu-CdlT** [comment]
Ca semble bon en prod

**Comment by VincentFarcy** [comment]
Les secteurs ont été créés au mauvaise endroit (topic / sujet ou mot clé).
Il va falloir tout déplacer dans sector.

**Comment by GuillaumeAV** [comment]
Ca va heureusement il n'y a pas beaucoup d'items !

**Comment by VincentFarcy** [comment]
oui c'est vrai. 
Il y a pas mal de relations par contre : https://data.lescheminsdelatransition.org/themes
