### ISSUE TITLE
Problème de chargement et d’affichage de la Home page

### ISSUE THREAD

**Issue by GuillaumeAV** [chemins-de-la-transition/semapps#321]
Via @Mathieu-CdlT - Apparition d’un page blanche (pas systématique). Obligation de recharger la page pour qu’elle s’affiche

=> J'avais ce problème aussi mais je ne l'ai plus .. Tu l'as toujours @Mathieu-CdlT ? A tout hasard, si oui t'as essayé de faire Ctrl Alt R (vidage du cache) ?

**Comment by Mathieu-CdlT** [comment]
Oui, ca me le fait toujours (à l'instant)

**Comment by clemenceCDLT** [comment]
Ca ne me le fait pas de mon côté! C'est sur dev ? app ? quel navigateur ?

**Comment by GuillaumeAV** [comment]
Ca me l'a fait ce matin sur dev.app avec Firefox ..

**Comment by srosset81** [comment]
Je ne reproduis pas avec Firefox
@GuillaumeAV Quand tu  as l'écran blanc, peux-tu ouvrir la console en faisant CTRL+ALT+I puis en allant sur l'onglet Console ? Et là copier le/les messages d'erreur

**Comment by GuillaumeAV** [comment]
Ok si ca me le refait je te dirai !

**Comment by GuillaumeAV** [comment]
J'ai reproduit !
![Capture d’écran de 2022-06-09 16-26-06](https://user-images.githubusercontent.com/6160028/172871104-83d2a710-5657-43ce-ac98-7c39854cdd75.png)

**Comment by GuillaumeAV** [comment]
J'ai rereproduit ! 
![Capture d’écran de 2022-06-09 17-08-11](https://user-images.githubusercontent.com/6160028/172880759-a32d3287-9f5b-4c78-9091-54e3761fc330.png)

![Capture d’écran de 2022-06-09 17-09-21](https://user-images.githubusercontent.com/6160028/172880999-14df07de-0474-4162-abbc-d61b3071d5ea.png)

**Comment by GuillaumeAV** [comment]
Rerereproduit sur https://dev.app.lescheminsdelatransition.org/Course
![Capture d’écran de 2022-06-09 17-12-56](https://user-images.githubusercontent.com/6160028/172881844-9229746b-6cf4-4fbf-a047-3eeca1bd4a6e.png)

**Comment by srosset81** [comment]
Merci ! Les erreurs concernant donc les composants AgendaFilter et SearchContent

**Comment by GuillaumeAV** [comment]
Reproduit à nouveau :
![Capture d’écran de 2022-06-10 20-37-58](https://user-images.githubusercontent.com/6160028/173129610-ed453444-8126-4889-8734-8cbb97bc39ec.png)
)

**Comment by srosset81** [comment]
Oui on n'a pas encore pu regarder. Je le fais au plus vite.

**Comment by srosset81** [comment]
@GuillaumeAV Normalement c'est réglé (déployé en prod dans 3 minutes)

**Comment by srosset81** [comment]
Peut-être qu'il était sur une ancienne version du site, en cache ?
