### ISSUE TITLE
Ajouter les réseaux sociaux à côté du site internet dans la rubrique "Liens" ... 

### ISSUE THREAD

**Issue by GuillaumeAV** [chemins-de-la-transition/semapps#328]
Lesquels ... 

Twitter, FB, LinkeIn, Insta, Mastodon et n'importe ... Via le petit mécanisme qui avait été développé je crois avec affichage automatique du logo ?

**Comment by srosset81** [comment]
J'ai fait ça pour Organigraph: https://cercles.assemblee-virtuelle.org/Circle/https%3A%2F%2Fdata.virtual-assembly.org%2Forganizations%2Fassemblee_virtuelle/show

**Comment by GuillaumeAV** [comment]
Aah c'est top ça en effet ! A voir si c'est prioritaire et faisable d'ici au 14, je vous laisse juger ..

**Comment by srosset81** [comment]
Voilà ce que ça donne avec les réseaux sociaux les plus connus:

![Capture d’écran de 2022-09-26 18-53-12](https://user-images.githubusercontent.com/17931931/192335814-16ccd166-e891-453f-9319-4d728bae909e.png)

Je dois fixer un bug dans SemApps avant de pouvoir déployer ça.

**Comment by srosset81** [comment]
@GuillaumeAV Je vais le faire pour les organisations. Besoin pour d'autres types de ressources ?
