### ISSUE TITLE
Bug sur les personnes dans le back office

### ISSUE THREAD

**Issue by GuillaumeAV** [chemins-de-la-transition/semapps#329]
Se rendre à l'onglet personne du back office .. .

**Comment by VincentFarcy** [comment]
Le pb vient de cette ligne : [dereference: ['sec:publicKey', 'pair:hasLocation/pair:hasPostalAddress'],](https://github.com/chemins-de-la-transition/semapps/blob/81cac9465cb9b71f4f6d8101cc1b7218dce183aa/backoffice/src/resources/Agent/Actor/Person/index.js#L22)

**Comment by srosset81** [comment]
C'est parce qu'on avait pas défini l'ontologie "sec" côté backoffice. C'est corrigé.
