### ISSUE TITLE
Quand on clique sur la plupart  des items, on arrive sur les interfaces d'édition ...

### ISSUE THREAD

**Issue by GuillaumeAV** [chemins-de-la-transition/semapps#33]
Aller sur le menu de gauche, cliquer sur des événement, orga, personne, compétence, personne, type, statut et constater le problème .. 

Aller sur une fiche parcours, cliquer sur un thème ou une compétence et constater le problème ... 

Il faudrait arriver sur les interfaces de visualisation des items ;)

**Comment by srosset81** [comment]
@GuillaumeAV C'est bon c'est fixé sur https://app.lescheminsdelatransition.org/
