### ISSUE TITLE
Page Chemins

### ISSUE THREAD

**Issue by clemenceCDLT** [chemins-de-la-transition/semapps#332]
* Réorganiser champs : 
commentaires Mathieu : 
Pourquoi proposé par ? 
En tout cas pas en premier –> le mettre ailleurs ? 
Si proposé par, permettre que ce soit aussi proposé par une organisation

* Apparait “logo”  → Bug ?

**Comment by GuillaumeAV** [comment]
Ne pas investir de temps sur la reorg, ca va être réorganisé selon les maquettes d'Audrey par @VincentFarcy chere @clemenceCDLT 
Le logo par contre, oui c'est une bug destiné à être résolu :)

**Comment by VincentFarcy** [comment]
Pour info j'ai pas mal avancé sur Place, Organization et Person.
Il vaut mieux éviter les modif au coup par coup sur ces ressources pour éviter les conflits.
Pour gagner du temps sur Event, Course et Path le mieux sera je pense de repartir d'un copier coller de Place.

**Comment by clemenceCDLT** [comment]
Ok ça marche, j'ai quand même déjà fait un réarrangement rapide (voir ma PR)
Le bug du logo sera résolu tout seul car ce ne sont pas les mêmes composants qu'on utilisera pour afficher les lieux/événements/voyages

**Comment by VincentFarcy** [comment]
Doublon avec https://github.com/chemins-de-la-transition/semapps/issues/176
Je ferme l'issue
