### ISSUE TITLE
Page d'accueil - front

### ISSUE THREAD

**Issue by bouviermullerp** [chemins-de-la-transition/semapps#34]
[écrans en cours de création](https://www.figma.com/file/jGQg6lDWmr0EW4YFBuiY0n/Untitled?node-id=0%3A1)

Cette page a vocation à être hébergé à l'ardresse https://lescheminsdelatransition.org/

Elle se décompose en plusieurs frames.
- Le header inclus le logo CdlT sur la gauche, et la possibilité d'accéder au "back-office" (réservé aux accueillants et aux créateurs de parcours)
- Une image + des boutons qui redirigent vers Parcours / Evenements / Carte
- Un affichage par carte d'une sélection de lieux 
- Un affichage par carte d'une sélection d'évènement
- Un footer avec les mentions légales, la politique de cookie, etc.

**Comment by bouviermullerp** [comment]
Commentaires : 
[Bandeau de recherche]: est-ce qu'on recherche uniquement les voyages ?
[Bandeau recherche]: est ce qu'on ouvre bien une nouvelle page avec la recherche ? (auquel cas, ajouter un bouton pour lancer la recherche ?)
[Lieux et acteurs de la transition]: Un statut "en vedette" a été mis en place par Seb pour les Colibris - ou alors aléatoire ?
[Lieux et acteurs de la transition]: On n'affiche que les lieux pour le moment (plus simple pour ne pas mélanger les classes)
[Lieux et acteurs de la transition]: Texte à afficher sur la photo : Attribut Thème
[Notre objectif]: Possible d'avoir le crédit des photos ?
[Lanque]: Uniquement en français - internationalisation dans une prochaine milestone.
[Favoris / Like]: Dans une prochaine milestone.
[Design]: Proche de https://www.merckgroup.com/fr-fr !
[Mobile]: Comment apparait la version mobile ?
[Région]: géré avec 'Place' - discussion côté technique
[Evenement et projet]: seulement des évènements. Comment sont sélectionnés les 3 évènements mis en avant ?
Clarifier la sémantique : voyage, 
On n'affiche que les parcours, les chemins ne s'affichent pas sur le front.

**Comment by J9rem** [comment]
Je passe cette carte en revue car j'ai l'impression d'avoir une bonne couverture du design de la page d'accueil.

SAUF la partie des filtres et boutons de recherche (que je ne sais pas comment implémenter).

**Comment by srosset81** [comment]
Je ferme puisque l'essentiel du travail a été fait par Jérémy.
On verra pour créer des issues sur les choses manquantes.
