### ISSUE TITLE
Améliorer l'affichage des secteurs d'activité

### ISSUE THREAD

**Issue by GuillaumeAV** [chemins-de-la-transition/semapps#345]
Dans le corps de la page : Soit avec les pictos, soit sans rien avec la police par défaut si c'est plus simple ! 

Dans le header : Ils sont limités à 2 semble t'il .. Dévérouiller la limite !

**Comment by VincentFarcy** [comment]
ok pour la llimite à modifier.

pour le corps de la page peux-tu préciser ce que tu voudrais modifier ?
![image](https://user-images.githubusercontent.com/55813208/172859673-8e0f7366-63e6-422e-bbc2-4c8d910484c0.png)

**Comment by VincentFarcy** [comment]
Vous avez la main pour les charger depuis le backoffice maintenant :-)

**Comment by srosset81** [comment]
Faut attendre que ce soit en prod, sinon ils vont entrer des données pour rien.
