### ISSUE TITLE
Onglet édition - Mettre tout sur une seule page (pour l'ensemble des données)

### ISSUE THREAD

**Issue by GuillaumeAV** [chemins-de-la-transition/semapps#346]
A la réflexion, plutôt que d'avoir 3 onglets en mode édition, je me dis qu'il serait mieux d'avoir un seul onglet.
Ca éviterait le risque que les gens oublient de renseigner les 2 onglets supplémentaires .. J'imagine que ce n'est pas trop difficile ? Je fais une issue dédiée !

Peut-être avec des grands titres : 
- A propos du XX
- En lien avec le XX
- Informations de contact

**Comment by VincentFarcy** [comment]
Personnellement je trouve ça beaucoup plus propre avec des onglets.
A réfléchir après le 14 ?

**Comment by GuillaumeAV** [comment]
Suite à discussion avec @VincentFarcy on se laisse le temps de bien réfléchir et en solution temporaire on met une petite phrase en bas du premier onglet du formulaire, juste avant le bouton Enregistrer : 
"N'oubliez pas de renseigner le deuxième onglet du formulaire, c'est là qu'on pose les questions les plus intéressantes !"
