### ISSUE TITLE
Vignette d'un lieu suite à une recherche - localisation undefined

### ISSUE THREAD

**Issue by GuillaumeAV** [chemins-de-la-transition/semapps#347]
Quand on arrive sur la barre de résultats en mode onglet, la localisation des lieux est marquée "undefined
![Capture d’écran de 2022-06-09 14-05-28](https://user-images.githubusercontent.com/6160028/172842862-8fdc27bc-caee-4c27-8db7-bf161a1484be.png)
"

**Comment by srosset81** [comment]
C'est parce qu'on ne déréférence pas le lieu dans le moteur de recherche (pas d'affichage en carte)
Si on déréférençait le lieu, dans l'état actuel du code, ça s'appliquer à toutes les ressources (aussi événements, voyages...) et baisserait les perf.
Si on a pas le temps de régler ça avant le 14, je propose de cacher temporairement cette information.

**Comment by GuillaumeAV** [comment]
Good solution !
