### ISSUE TITLE
Sur organisation, on ne voit pas les personnes

### ISSUE THREAD

**Issue by GuillaumeAV** [chemins-de-la-transition/semapps#349]
[Sur AV par exemple](https://dev.app.lescheminsdelatransition.org/Organization/https%3A%2F%2Fdev.data.lescheminsdelatransition.org%2Forganizations%2Fassemblee-virtuelle1/show), Seb et moi qui sommes membre mais on n'apparait pas (dans la colonne de droite)  ...

**Comment by VincentFarcy** [comment]
S'il s'agit du front, ce n'est pas prévu sur la maquette.
Ce serait à ajouter en quelle position dans la colonne de droite ?

**Comment by GuillaumeAV** [comment]
Sorry .... Tu peux le mettre juste en dessous de Ou sommes nous avec le libellé "a pour contributeur.trice"
