### ISSUE TITLE
Edition des profils :  réordonner quelques champs et changer quelques libellés

### ISSUE THREAD

**Issue by GuillaumeAV** [chemins-de-la-transition/semapps#350]
Salut @VincentFarcy voici une proposition de réorganisation des champs dans l'interface d'édition .. Qui pourrait globalement être duppliquée pour les autres profils !

Sur une même page ... Réordonner comme suit et remplacer - par  : 

**A propos de vous :** 
- Photo (cf #348 )
- Prénom - Prénom (Renseignez un nom d'utilisateur pour que votre prénom n'apparaisse pas publiquement)
- Nom - (Renseignez un nom d'utilisateur pour que votre nom n'apparaisse pas publiquement)
- Site internet - Un lien sur le web ? (Site web, réseau social ...)
- Téléphone - Téléphone (ne s'affichera pas)
- Localisation - Localisation (Reseignez au choix une adresse précise ou seulement une commune
- En quelques mots
- Description
- Vos intentions en venant sur les chemins de la transition
- Les finalités que vous poursuivez
- Secteurs d'activité - Vos secteurs d'activité. 
- Les mots-clés (centres d'intérêts) qui vous caractérisent
- Vos compétences actuelles
- Les compétences que vous recherchez

**En lien avec vous :** 
- Membre de - Tu es membre d'une ou plusieurs organisations ? 
- Inspirée par - Des personnes t'inspirent ? 
- Hote de - Tu es l'hôte d'un lieu ? 
- Est organisateur de - Tu contribues à l'organisation d'un évenement ou d'un voyage ? 
- Est mentor pour - Tu es intervenant sur un évenement ou un voyage ? 
- Chemins - Tu contribues à la construction d'un chemin ?

**Comment by VincentFarcy** [comment]
Vu avec @GuillaumeAV  : à voir après le 14

**Comment by clemenceCDLT** [comment]
mettre le même ordre et les mêmes titres de parties dans les autres fiches
