### ISSUE TITLE
Enlever la possibilité de s'inscrire sur un chemin

### ISSUE THREAD

**Issue by GuillaumeAV** [chemins-de-la-transition/semapps#354]
Parce qu'on ne peut pas s'inscrire sur un chemin ;)
![Capture d’écran de 2022-06-09 18-07-54](https://user-images.githubusercontent.com/6160028/172893823-99cde8d9-2a85-4381-9baa-af5c54a4f131.png)

**Comment by clemenceCDLT** [comment]
Ca a été fait sur cette issue : https://github.com/chemins-de-la-transition/semapps/pull/305
