### ISSUE TITLE
Supprimer (ou modifier) le texte de connexion

### ISSUE THREAD

**Issue by srosset81** [chemins-de-la-transition/semapps#357]
... puisque maintenant la connexion est ouverte à tous.

![Capture d’écran de 2022-06-10 11-36-34](https://user-images.githubusercontent.com/17931931/173037401-67c28ff6-b2d6-4471-9c93-9c0de51aa2f8.png)

On supprime le texte ou vous avez une idée pour un autre texte @GuillaumeAV @Mathieu-CdlT ?

**Comment by GuillaumeAV** [comment]
TEXTE : 
Bienvenue sur les Chemins de la Transition ! 
Créer un compte sur la plateforme va te permettre de renseigner ton profil : Qui tu es, dans quoi tu t'impliques, ce que tu recherches et ce que tu as à offrir. 
Il va également te permettre d'enregistrer tes coups de coeur en favoris (acteurs, lieux, evenements, voyages), et de rejoindre la communauté des Chemins de la Transition ! 


Au passage y aurait pas moyen de mettre un fond avec une couleur de la charte graphique CdlT + le logo ?
