### ISSUE TITLE
Les pictos thématiques ne s'affichent plus sur les vignettes

### ISSUE THREAD

**Issue by Mathieu-CdlT** [chemins-de-la-transition/semapps#362]
les images des pictos thématiques (secteurs d'activité) ne s'affichent plus, ni sur la home page (vignettes), ni dans les fiches. 
Sauf pour le secteur d'activité "écologie - environnement"

**Comment by srosset81** [comment]
Je crois que c'est même chose que rapporté par Guillaume:
https://github.com/chemins-de-la-transition/semapps/issues/345#issuecomment-1151180281
Voir le commentaire de Vincent

**Comment by VincentFarcy** [comment]
Il faut juste les charger depuis le backoffice, j'en ai fait une moi même pour tester.

**Comment by Mathieu-CdlT** [comment]
Je viens de tester, reste que les images des vignettes ne s'affichent pas (voir home page par exemple)  @VincentFarcy

**Comment by Mathieu-CdlT** [comment]
Ok c'est fait !
