### ISSUE TITLE
Voyages - Il manque la possiblité de renseigner les events constitutifs du voyage

### ISSUE THREAD

**Issue by GuillaumeAV** [chemins-de-la-transition/semapps#366]
Ce qui est dommage !!!

Voir par exemple ...
https://admin.lescheminsdelatransition.org/Course/https%3A%2F%2Fdata.lescheminsdelatransition.org%2Fcourses%2Falterfixe/show

**Comment by srosset81** [comment]
Je crois pas que ça a été possible jusqu'à maintenant ?
On créait les événements et on les liait au voyage à ce moment, non ?

J'enlève le label "avant 14 juin" car c'est du backoffice.

**Comment by GuillaumeAV** [comment]
Oui c'était possible, c'est comme ça qu'on créait les voyages ... J'envisageait de créer un voyage ou 2 demain pour l'exemple, si c'est juste un truc à réactiver, je veux bien que vous le fassiez demain :)

**Comment by VincentFarcy** [comment]
J'ai créé une PR mais ça pose une question.
Un événement peut il faire partie de plusieurs voyages ?
si oui c'est ok.

Dans le cas contraire on ne peut pas ouvrir le champ des 2 côtés.
On pourrait en effet depuis différents voyages choisir un même event. Dans ce cas l'interface d'édition de l'event, prévu pour une seule valeur, n'affiche rien.

**Comment by srosset81** [comment]
@GuillaumeAV m'a dit par téléphone que c'était pas un problème qu'un événement puisse faire partie de plusieurs voyages.

Donc t'as le go @VincentFarcy :-)
