### ISSUE TITLE
Quand je suis sur un voyage et que je clique sur un chemin, ca bugue

### ISSUE THREAD

**Issue by GuillaumeAV** [chemins-de-la-transition/semapps#367]
Par exemple : Depuis l'alertfixe vers le chemin de la reprise de fermes en collectif

**Comment by srosset81** [comment]
Le lien est /Actor alors que ça devrait être /Path
https://lescheminsdelatransition.org/Actor/https%3A%2F%2Fdata.lescheminsdelatransition.org%2Fpaths%2Fchemin-de-la-reprise-de-fermes-en-collectif/show
