### ISSUE TITLE
Changer le texte en haut de la homepage ..

### ISSUE THREAD

**Issue by GuillaumeAV** [chemins-de-la-transition/semapps#368]
TITRE : Apprendre en voyageant (, comme le font les compagnons depuis des siècles si c'est pas trop long) 

TEXTE :
Après plusieurs années de développement, les Chemins de la Transition sortent en version Beta ! Nous sommes très heureux de vous inviter à tester cette plateforme :  
Celle-ci a été conçue pour vous permettre d'explorer le monde des transitions écologiques, énergétiques, culturelles, sociales, économiques, technologiques, en allant à la rencontre de leurs acteurs. 
Sur les Chemins de la Transition, vous pouvez apprendre à leur contact et vous former en voyageant, comme le font les compagnons depuis des siècles !

**Comment by clemenceCDLT** [comment]
D'après Mathieu, remettre l'ancien texte : 
Vous êtes curieux des expériences et métiers qui se développent, qui redonnent du sens à nos actions ? Nous vous proposons de partir découvrir ces initiatives, d'apprendre et de vous former au contact des professionnels qui font déjà le monde de demain. Embarquez sur les chemins de votre transition, à la rencontre des acteurs et de lieux inspirants et découvrez leurs savoir-faire. Plusieurs modalités s'offrent à vous...

**Comment by GuillaumeAV** [comment]
Ok ca roule, je ne suis pas complètement en phase avec le titre notamment qui ne dit pas la proposition de valeur des CdlT et pense par ailleurs, qu'il faut absolument préciser dès le premier texte que c'est une beta pour ne pas générer d'attentes inconsidérées. 

Je remettrai le sujet sur la table dans quelques jours !

**Comment by srosset81** [comment]
Par ailleurs le texte est long, sur mobile surtout, ça empêche de voir le moteur de recherche sans scroller.

**Comment by Mathieu-CdlT** [comment]
![Home Page haut](https://user-images.githubusercontent.com/61470357/173389095-77660ded-3fee-4d7b-8d11-0f51a546ee18.PNG)
Est ce qu'il est possible ds un premier temps de remettre le texte qu'il y avait avant ?

**Comment by clemenceCDLT** [comment]
ça a été fait !
