### ISSUE TITLE
Contrôle de cohérence entre les formulaires d'édition et les pages d'affichage des ressources en frontoffice

### ISSUE THREAD

**Issue by VincentFarcy** [chemins-de-la-transition/semapps#375]
Suite à un échange avec Guillaume, j'ai comparé formulaire d'édition et page d'affichage de chaque ressource.

J'ai relevé quelques champs présents en édition mais pas ou peu utilisés :

```
Course => cdlt:CourseStatus (uniquement utilisé dans les filtres du backoffice) (vu : enlevé du formulaire)
Course => pair:documentedBy

Event => cdlt:pedagogicalMeans
Event => cdlt:evaluationMethod
Event => cdlt:full (uniquement utilisé sur les cartes d'affichage des events)
Event => cdlt:accessibility
Event => cdlt:price

Place => cdlt:hostDescription

Person => pair:phone

Organization => cdlt:hasCourseType
Organization => pair:partnerOf (uniquement utilisé sur la homePage)

Course/Event/Place => pair:e-mail
Course/Event/Place => pair:phone
```

Que fait on pour chacun de ces champs ?

**Comment by VincentFarcy** [comment]
Suite à un échange avec Guillaume, j'ai comparé formulaire d'édition et page d'affichage de chaque ressource.

J'ai relevé quelques champs présents en édition mais pas ou peu utilisés :

Course => cdlt:CourseStatus	(uniquement utilisé dans les filtres du backoffice)
Course => pair:documentedBy	
		
Event => cdlt:pedagogicalMeans	
Event => cdlt:evaluationMethod	
Event => cdlt:full		(uniquement utilisé sur les cartes d'affichage des events)
Event => cdlt:accessibility	
Event => cdlt:price	
		
Place => cdlt:hostDescription	
		
Person => pair:phone	
		
Organization => cdlt:hasCourseType	
Organization => pair:partnerOf	(uniquement utilisé sur la homePage)
		
Course/Event/Place => pair:e-mail	
Course/Event/Place => pair:phone

**Comment by srosset81** [comment]
cdlt:CourseStatus ne devrait pas être visible en édition, mais uniquement modifiable avec le bouton "Publier" / "Dépublier"

**Comment by VincentFarcy** [comment]
> cdlt:CourseStatus ne devrait pas être visible en édition, mais uniquement modifiable avec le bouton "Publier" / "Dépublier"

ok je l'enlève du formulaire

**Comment by VincentFarcy** [comment]
Vu avec @GuillaumeAV (à vélo) : 
Tous les champs sont à ajouter sauf : 
```
Course => cdlt:CourseStatus
Course => pair:documentedBy
Event => cdlt:price
```

**Comment by VincentFarcy** [comment]
Et à la demande de Guillaume : remplacement de "type de voyage" par "mode de voyage"
