### ISSUE TITLE
Intégrer Jeremy sur le projet SemApps CdlT

### ISSUE THREAD

**Issue by GuillaumeAV** [chemins-de-la-transition/semapps#38]
Hola @J9rem ! 

La gestion du projet SemApps va se dérouler par ici à priori, pas vrai @bouviermullerp ?

**Comment by bouviermullerp** [comment]
Hola @GuillaumeAV ! oui, c'est le cas :) 
C'est une issue originale que tu nous a créé la, non ?

**Comment by J9rem** [comment]
Merci de me faire un ping

@GuillaumeAV @bouviermullerp quels seraient vos critères pour déterminer que je suis intégré ?

**Comment by bouviermullerp** [comment]
@J9rem aucune idée ! Se sentir intégré en tant que prestataire-développeur ou contributeur-bénévole ?

Ce sont des critères très personnel, non ? J'ai l'impressuion que je me sens intégré à un projet quand je m'entends bien avec les protagonistes, qu'on s'appelle régulièrement pour se donner des nouvelles, que je peux m'exprimer et que je suis entendu.

En école d'ingénieur on m'a intégré après moultes beuveries :beers: 

N'hésite pas partager explicitement ce dont tu as besoin et on fera de notre mieux ! Dispo pour un appel au besoin. A bientôt

**Comment by J9rem** [comment]
Ok ok je vois que tu le prends avec humour. ;-) 
Bon comme je pensais que cette issue était plus sérieuse, j'avais besoin de plus de détails sur l'intention pour bien la comprendre.

Plus sérieusement,  si c'est juste s'assurer que je suis dans le projet Semapps Cdlt, c'est déjà le cas via le suivi par Sébastien. 

Donc je clos l'issue.

**Comment by GuillaumeAV** [comment]
Partant tout de même de mon côté pour des appels et des apéros sans alcool (j'ai très sérieusement diminué ma conso de mon coté !) :)
