### ISSUE TITLE
"Evénements sur le lieu": des événements passés sont affichés

### ISSUE THREAD

**Issue by srosset81** [chemins-de-la-transition/semapps#381]
Cela serait plus cohérent de n'afficher que les événements futurs, ou ça a du sens de quand même l'afficher comme un historique @GuillaumeAV ?

Visible ici p.ex. https://lescheminsdelatransition.org/Place/https%3A%2F%2Fdata.lescheminsdelatransition.org%2Fplaces%2Fatelier-du-soleil-et-du-vent/show

**Comment by srosset81** [comment]
Surtout que ces événements passés s'affichent aussi sur la barre de côté...

![Capture d’écran de 2022-06-13 10-34-18](https://user-images.githubusercontent.com/17931931/173313411-2d545fdd-5801-4034-b427-4c7a1b13a324.png)

**Comment by clemenceCDLT** [comment]
Ajouter un bouton coché "N'afficher que les événements à venir"
