### ISSUE TITLE
Réservation

### ISSUE THREAD

**Issue by bouviermullerp** [chemins-de-la-transition/semapps#4]
En tant que administrateur CdlT, je peux composer une instance d'un chemin : un voyage.
Quand ce voyage est finalisé, je peux envoyer une propositon par mail qui prend la forme d'une facture.Le mail embarque un lieu vers Stripe afin de régler cette facture.

**Comment by srosset81** [comment]
Cette issue n'est plus à jour, ce n'est pas ce qui est prévu dans la v1
Je ferme
