### ISSUE TITLE
Affichage rubriques page événement (détail)

### ISSUE THREAD

**Issue by Mathieu-CdlT** [chemins-de-la-transition/semapps#402]
Un certain nombre de rubriques ont disparu (elles figuraient avant - travail effectué par Clémence) dans l'affichage de la page détail des événements. 

Elles sont remplissables en mode édition mais n'apparaissent plus sur le front office en mode lecture. 

Toutes ces rubriques sont essentielles pour les formations labellisées qualiopi et ce serait fort dommage qu'on ne puisse pas présenter ce point fort de la plateforme lors de l'événement de lancement. 

exemple : formation réparation cycle de la maison du vélo de Novembre.

**Comment by VincentFarcy** [comment]
De quels rubriques s'agit-il ?
Certains données ont été réintroduites aujourd’hui. Voir issue https://github.com/chemins-de-la-transition/semapps/issues/375

**Comment by Mathieu-CdlT** [comment]
de tous les champs qui sont à compléter en mode édition et qui n'apparaissent plus en mode affichage: 
- moyens matériel et pédagogique
- modalités d'évaluation 
- accessibilité

Et je dois en oublier car j'ai plus les critères qualiopi en tête. La fiche que avait modifié était bien faite.

**Comment by VincentFarcy** [comment]
Ce sont les 3 champs qui ont été ajouté ce matin.
