### ISSUE TITLE
Gérer les publics cibles

### ISSUE THREAD

**Issue by GuillaumeAV** [chemins-de-la-transition/semapps#406]
Il manque les boutons Editer etc .... 
Si chronophage, on décale hein ;)

**Comment by srosset81** [comment]
Ca peut être utile de faire `call webacl.resource.refreshContainersRights`

**Comment by GuillaumeAV** [comment]
Il faudrait ensuite les mettre dans les filtres ...

**Comment by GuillaumeAV** [comment]
je ferme il y a déja la #421 ...
