### ISSUE TITLE
Accéder à des bases de données exhaustives et structurées pour les thèmes et compétences 

### ISSUE THREAD

**Issue by GuillaumeAV** [chemins-de-la-transition/semapps#41]
En tant qu'utilisateur de la plateforme, je veux pouvoir sélectionner des thèmes et compétences sur la base de listes prédéfinies, dans lesquelles je pourrais trouver mon bonheur. 

Afin de renseigner mon profil, ou le profil d'un "truc" (Personnes, orgas, chemins, parcours programmés, lieux etc.), si je pouvais taper quelques lettres d'un mot-clé et accéder de la sorte à des termes correspondant à ma recherche ce serait génial. #Complétion. 

Si je pouvais par ailleurs identifier tous les "trucs" (Personnes, orgas, chemins, parcours programmés, lieux etc.), en lien avec les thèmes et compétences qui m'intéressent, ce serait magnifique.

**Comment by srosset81** [comment]
Une base de compétences et de thématiques est un projet à part entière qui dépasse largement le cadre de celui-ci, donc je propose de fermer.
