### ISSUE TITLE
Sur le voyage inaugural, je ne parviens à pas à enregistrer suite à une modification ..

### ISSUE THREAD

**Issue by GuillaumeAV** [chemins-de-la-transition/semapps#415]
Sur https://admin.lescheminsdelatransition.org/Course/https%3A%2F%2Fdata.lescheminsdelatransition.org%2Fcourses%2Fvoyage-inaugural-des-chemins-de-la-transition-a-velo/1

Ca marchait puis ensuite je ne suis parvenu à enregistrer l'enlèvement de 2 mots clés :)
![Capture d’écran de 2022-06-14 08-02-19](https://user-images.githubusercontent.com/6160028/173504548-042d35cf-9ad5-4239-9339-be201c06bf4c.png)

**Comment by srosset81** [comment]
Pas reproduit. J'ai enlevé 2 ou 3 mots-clés (et je les ai remis) mais je n'ai eu aucune erreur.

**Comment by GuillaumeAV** [comment]
Pas reproduit non plus .. Je ferme !
