### ISSUE TITLE
Je suis l'hote du chemin de l'éco-construction

### ISSUE THREAD

**Issue by GuillaumeAV** [chemins-de-la-transition/semapps#416]
Chelou non ? 

https://lescheminsdelatransition.org/Place/https%3A%2F%2Fdata.lescheminsdelatransition.org%2Fpaths%2Fchemin-de-l-eco-construction
![Capture d’écran de 2022-06-14 08-07-11](https://user-images.githubusercontent.com/6160028/173505140-1400ae41-00bf-4b99-af4b-dbaaad3fcc3c.png)

**Comment by srosset81** [comment]
C'est parce qu'on utilise le même prédicat (`cdlt:proposes`) pour les lieux et les chemins.

Pas un bug donc, mais il faudrait faire évoluer l'ontologie pour éviter ces cas de figures.

**Comment by srosset81** [comment]
On fait quoi du coup ? C'est un "bug" dans l'ontologie donc je me désassigne pour le moment.
