### ISSUE TITLE
Mettre les publics cible dans les filtres

### ISSUE THREAD

**Issue by Mathieu-CdlT** [chemins-de-la-transition/semapps#421]
Sur la fiche événement (front) la completion de public cible ne marche pas

**Comment by clemenceCDLT** [comment]
Il faut créer les publics cibles sur le backoffice dans les concepts

**Comment by Mathieu-CdlT** [comment]
C'est compliqué de pré-créer des publics cibles figés. Il y a des multitudes de conditions selon les événements / voyages (ex: les CIVAM exigent des titulaires de BPREA pour certaines de leurs formations, on va pas créer un public cible "titulaire d'un BPREA")

**Comment by GuillaumeAV** [comment]
Pour moi il doit y avoir, de la même manière que pour les secteurs d'activités, un nombre restreint de publics cibles, de manière à pouvoir les utiliser en tant que filtres : 

Je cherche les LEV qui correspondent à qui je suis : Etudiant, personne en insertion, en reconversion, entreprise, collectivité, particulier .. et quelques autres peut -être .. 

J'ai commencé à renseigner ! https://admin.lescheminsdelatransition.org/TargetAudience

**Comment by GuillaumeAV** [comment]
Je ne vois pas les personnes référentes sur le formulaire d'édition, normal ?

**Comment by Mathieu-CdlT** [comment]
Ajouter "jeunes" / "Jeunesse"?
