### ISSUE TITLE
Docker utilise presque tout l'espace disque

### ISSUE THREAD

**Issue by srosset81** [chemins-de-la-transition/semapps#423]
Docker utilisait plus de 95Gb d'espace disque sur 100Gb, ce qui bloquait les mises à jour.
Même en faisant un `docker system prune`, ça reste à 84Gb.
Le dossier concerné est `/var/lib/docker/overlay2`
Il faudrait soit augmenter l'espace disque, soit trouver une solution. J'ai jamais rencontré ce type de problème.

**Comment by srosset81** [comment]
C'est bon, j'ai résolu le problème en lançant `docker system prune --all --volumes --force`
Attention: cette commande efface les volumes. Comme on utilise pas pour les CDLT, c'était pas un problème, mais ce n'est pas forcément le cas pour toutes les config Docker (on peut vérifier ça en faisant `docker volume ls`)
J'ai ajouté cette commande au cron qu'on lance chaque nuit pour compacter le triplestore.

**Comment by fluidlog** [comment]
Tu peux aussi ajouter cela à la doc de maintenance SemApps : https://pad.lescommuns.org/MZi_7lwJRAaRWOZ-Di988A

**Comment by srosset81** [comment]
@simonLouvet Oui mais ils sont mappés sur des dossiers. Ce ne sont pas des containers indépendents.

**Comment by simonLouvet** [comment]
> @simonLouvet Oui mais ils sont mappés sur des dossiers. Ce ne sont pas des containers indépendents.

et le prune avec volume ne supprime pas ces données/fichiers?
