### ISSUE TITLE
Vérifier que les accueillants sont adhérents HelloAsso

### ISSUE THREAD

**Issue by srosset81** [chemins-de-la-transition/semapps#43]
HelloAsso fournit un API qui pourrait permettre cela.

A réfléchir à quel endroit on intégrerait ça au niveau technique.

@bouviermullerp peux-tu préciser à quel moment cette vérification serait nécessaire ? Que se passerait-il si un accueillant n'est plus adhérent ?

**Comment by GuillaumeAV** [comment]
Question ... Au regard de la présentation d'open collective et de son API graphql, ne serait-il pas pertinent d'envisager une migration sur open collective plutôt qu'hello asso ?
