### ISSUE TITLE
Cacher ou désactiver le bouton Contact si aucune adresse mail n'est définie

### ISSUE THREAD

**Issue by srosset81** [chemins-de-la-transition/semapps#433]
Actuellement si une organisation ou un lieu n'ont pas défini d'adresse mail, le formulaire de contact retourne l'erreur:

`Aucune adresse mail définie pour XXX`

Ce serait mieux de cacher ou désactiver le bouton de Contact si aucune adresse mail n'est définie, ça évite de faire perdre du temps à l'utilisateur. Ou alors rendre l'adresse mail obligatoire, mais il faudra l'ajouter aux lieux/organisations existants.

**Comment by GuillaumeAV** [comment]
Rendre le mail obligatoire, c'est une bonne idée je crois ! On pourra renseigner les adresses mail manquantes avec @Mathieu-CdlT & Chloé !

**Comment by srosset81** [comment]
En fait pour les lieux c'est obligatoire, mais je sais pas quand ça a été activé du coup il peut y en avoir qui ne sont pas rempli.

Pour les organisations, il faut le rendre obligatoire
