### ISSUE TITLE
Commentaires 

### ISSUE THREAD

**Issue by GuillaumeAV** [chemins-de-la-transition/semapps#442]
Sur chaque page un formulaire de commentaires. 
En dessous, la liste des commentaires .. 
A gauche l'avatar
Et la date etc. 

Si la personne n'est pas loguée, message "Connectez vous".

Hiérarchie optionnelle à terme

**Comment by srosset81** [comment]
Fait ici https://github.com/chemins-de-la-transition/semapps/pull/508

Déployé ici en dev:
https://dev.lescheminsdelatransition.org/Path/https%3A%2F%2Fdev.data.lescheminsdelatransition.org%2Fpaths%2Fchemin-du-web-semantique/show

Par contre je remarque que j'ai pas géré le cas où l'utilisateur n'est pas connecté. Je regarde ça très bientôt.
