### ISSUE TITLE
Scrapping

### ISSUE THREAD

**Issue by GuillaumeAV** [chemins-de-la-transition/semapps#444]

**Comment by clemenceCDLT** [comment]
Pouvoir détecter les changements sur les pages des agendas/futurs événements des partenaires.
Utiliser un outil en ligne : simple à maintenir et facile à utiliser pour tout le monde, facile à mettre en place et automatiser

* Choisir un outil : Visualping, voir s'il y a mieux, s'inscrire avec le mail Occitanie
* Vérifier le max de pages que l'on peut surveiller et autres limites
* Ecrire un petit tuto pour que tout le monde puisse le prendre en main
* Mettre en place ça avec tous nos partenaires (Lien A sur le suivi partenaire, mettre à jour si besoin), vérification toutes les semaines ou 15j, le lundi matin
