### ISSUE TITLE
Quand on clique sur "Liste des organisations" il n'y a rien sur la page

### ISSUE THREAD

**Issue by clemenceCDLT** [chemins-de-la-transition/semapps#447]

**Comment by clemenceCDLT** [comment]
Exemple : 
https://lescheminsdelatransition.org/Organization/https%3A%2F%2Fdata.lescheminsdelatransition.org%2Forganizations%2Fles-petits-debrouillards/show

Quand on clique en haut à gauche sur 'Liste des organisations' on arrive sur la page https://lescheminsdelatransition.org/Organization et il serait bien d'y retrouver la liste des orgas

**Comment by clemenceCDLT** [comment]
Cela pourrait mener à cette page : https://lescheminsdelatransition.org/LEP?filter=%7B%7D

**Comment by srosset81** [comment]
Si on renvoie sur https://lescheminsdelatransition.org/LEP?filter=%7B%7D, ça serait bien de trouver un moyen de renvoyer directement au tab avec les organisations, par exemple avec une query string. C'est quelque chose que j'ai déjà fait mais je me rappelle plus où.

L'autre option serait de supprimer le lien "Liste des organisations"
