### ISSUE TITLE
Créer la possibilité d'afficher le numéro de téléphone sur une fiche lieu / profil organisation ?

### ISSUE THREAD

**Issue by ChloeCruzel** [chemins-de-la-transition/semapps#451]
Certaines organisations/lieux sont OK pour être contactés par téléphone, cela dit pas tous. 
L'idée serait donc de créer la possibilité en mode "édition" de cocher/décocher pour que le numéro s'affiche ou pas.

**Comment by srosset81** [comment]
Ne peut-on simplement ne pas entrer de numéro de téléphone quand l'organisation/lieu ne le veut pas ?
