### ISSUE TITLE
Bug Via Brachy

### ISSUE THREAD

**Issue by GuillaumeAV** [chemins-de-la-transition/semapps#452]
@clemenceCDLT tu crois que tu pourrais regarder ce bug ? 

Salut Salut !

Cool, heureuse d'entrendre que ce premier voyage a été une réussite et qu'il vous a nourris comme espéré ! J'espère que vous aurez le temps de souffler un peu dans les prochains mois, histoire de refaire le plein d'énergie pour la saison prochaine ;p

Pour la plateforme, j'ai bien créé un compte et j'accède aux différents onglets personne / orga / lieux / événements mais à l'exception de la localisation, rien de ce que j'écris ne s'enregistre et je n'arrive pas à trouver où se trouverais l'interface pour mettre à jour la fiche de Via Brachy sur la plateforme et ajouter les prochaines formations que l'on voudrait proposer. Peut-être y a t-il désormais 2 Caroline Ferrafiat dans la plateforme, avec probablement la même adresse mail puisque j'ai également utilisé mon adresse pro pour me connecter...? Bref : je crois que je vais avoir besoin de vos lumières... ;p
Je me suis également inscrite sur le Forum. J'ai reçu le message de Nadège tout à l'heure, j'ai l'impression que tout marche bien de ce côté.

Avec plaisir de renvoyer sur la plateforme à partir de notre site internet. Je viens d'ajouter un mot sur la page des "Lieux de la transition" : http://www.viabrachy.org/h%C3%A9t%C3%A9rotopies/les-lieux-de-la-transition. Je te laisse me dire si cela te convient. On pourra également relayer vos infos sur les réseaux sociaux.

Last but not least : Pas d'Agitaterre pour moi ce dimanche. Je reste dans le Tarn ce weekend, j'ai la famille et des copains de passage. Mais avec plaisir une prochaine ! (On va finir par réussir à se la boire, cette mousse !)

A vous les studios !

Salutations de Lisle

Caro

**Comment by clemenceCDLT** [comment]
Dans les acteurs je vois bien une seule Caroline inscrite avec l'adresse mail caroline.ferrafiat@viabrachy.org et elle a bien un profil Acteur qui devrait lui donner les droits de modifier Via Brachy depuis la page en appuyant sur le bouton éditer. Donc je vois pas d'où ça peut venir

**Comment by srosset81** [comment]
Fixé ici https://github.com/chemins-de-la-transition/semapps/issues/457
