### ISSUE TITLE
Accès à la modification d'un lieu pour un acteur

### ISSUE THREAD

**Issue by Mathieu-CdlT** [chemins-de-la-transition/semapps#457]
Petit problème qui s'est présenté ce matin (front). 

Nous avions créé un profil acteur + fiche lieu pour une orga (Via brachy (old)) avec un profil personne caroline ferrafiat. 
Caroline n'est pas parvenue à modifier les informations sur son lieu (elle était hote). Le stylo modification n'apparaissait pas sur son interface. 
J'ai supprimé son profil personne recréé un autre. Ca n'a rien changé. 
On a été obligé de recréer une nouvelle fiche lieu (Via Brachy) à laquelle elle a désormais accès. 

Est-il possible de voir d'où vient ce bug afin de voir si on peut éviter que cela se reproduise. Nous avons plusieurs acteurs dont on a créé les fiches et qui n'ont pas pris en main la plateforme encore. Il me semble que c'est la 2eme fois que se présente ce cas.

**Comment by srosset81** [comment]
De ce que je vois dans les données, Via Brachy est une organisation, pas un lieu.

Et il manquait effectivement le code côté middleware qui donnait automatiquement les droits en écriture pour les personnes liées à une organisation. C'est maintenant fixé (https://github.com/chemins-de-la-transition/semapps/commit/8911828377e7099a5f36e51bb0ac85ea59d1fd4c)

Si jamais ça se reproduit, essaie de m'avertir tout de suite (c'est-à-dire avant de régler le problème en effaçant la fiche et la recréant), ça me permettra de voir plus facilement ce qui se passe.

**Comment by srosset81** [comment]
Il fallait aussi que je migre les droits des utilisateurs actuels pour être sûrs qu'ils aient tous les bons droits pour les organisations. C'est fait (https://github.com/chemins-de-la-transition/semapps/commit/69c32f936cf60750092eb96e7e1a04e1fa37d166) et la migration a été lancée.

**Comment by Mathieu-CdlT** [comment]
Ok, on le fera. Je sais plus ce qu'il s'est passé mais il devait y avoir un caractère d'urgence à régler le problème vis à vis de notre partenaire et on a fait au plus vite pour pas le pénaliser / décourager.

**Comment by Mathieu-CdlT** [comment]
Merci d'avoir corrigé tout ça !
