### ISSUE TITLE
Upload photos

### ISSUE THREAD

**Issue by Mathieu-CdlT** [chemins-de-la-transition/semapps#458]
Salut Mathieu !

C'était bien à Agitaterre ?

Au final, j'ai bien réussi à créer de nouveaux contenus sur la plateforme, par contre aucune des photos que j'uploade n'apparaît. Aurais-tu une idée d'où pourrais venir le problème ?

Merci d'avance !
Caroline pour ViaBrachy

**Comment by srosset81** [comment]
@Mathieu-CdlT @GuillaumeAV Je ne reproduits pas. L'upload fonctionne bien pour moi.

J'ai vu qu'il y avait bien des images uploadées pour:
https://lescheminsdelatransition.org/Place/https%3A%2F%2Fdata.lescheminsdelatransition.org%2Fplaces%2Fvia-brachy

J'ai essayé d'en ajouter sur l'événement et ça a bien fonctionné (je les ai supprimé ensuite)

Si ça se reproduit, il faudrait qu'elle envoie par mail l'image qu'elle essaie d'uploader, afin qu'on puisse voir s'il y a un problème spécifique à l'image (mauvais format p.ex.)

**Comment by Mathieu-CdlT** [comment]
A priori, en tant qu'utilisateur via le front, si les photos sont trop lourdes (?), impossible de valider le formulaire. C'est arrivé à Via Brachy cette semaine et elle m'a envoyé la photo pour que je la charge moi et à Nehom qui a publié un événement sans photo du coup. Est ce que c'est possible de faire un test dans cette config ?

**Comment by srosset81** [comment]
Peux-tu m'envoyer la photo "trop lourde" de Via Brachy par mail ?

**Comment by Mathieu-CdlT** [comment]
Je ne l'ai pas... 
c'est ce qu'ils m'ont dit... Qu'ils n'arrivaient pas à sauvegarder en mettant la photo. 
Ils m'ont envoyé l'image et j'ai pu la charger de mon coté

**Comment by srosset81** [comment]
Alors la prochaine fois qu'une personne dis qu'elle n'arrive pas à uploader une image, demandez-leur de vous l'envoyer par email puis envoyez-la moi. Sinon je ne peux pas faire grand chose...

**Comment by GuillaumeAV** [comment]
Add an helper text to indicate which format, size & weight for pictures .. And eventually a link to an online good tool..
