### ISSUE TITLE
Rendre clicables les titres des CLEV

### ISSUE THREAD

**Issue by Mathieu-CdlT** [chemins-de-la-transition/semapps#463]
Pour accéder à une fiche détail depuis les CLEVS, il faut cliquer sur "Afficher + oeil". 
Sur la version mobile, seul l'oeil s'affiche et ça ne saute pas aux yeux de cliquer sur l'oeil. 
Est-il facilement possible de rentre les titres "clicables" également ?
Ca faciliterait grandement, notamment sur la version mobile. 
Merci !

**Comment by clemenceCDLT** [comment]
Tu veux dire depuis la carte des événements et des lieux ?

**Comment by Mathieu-CdlT** [comment]
Yes !
