### ISSUE TITLE
Fournir des contenus et des illustrations libres de droits pour la plateforme 

### ISSUE THREAD

**Issue by GuillaumeAV** [chemins-de-la-transition/semapps#48]
Un besoin du projet remonté par @J9rem !

@Mathieu-CdlT @laurecoplo @GuillaumeAV

**Comment by GuillaumeAV** [comment]
Une banque d'image : Le compte instagram de Lilian ;à https://www.instagram.com/cybermoyenage/

**Comment by J9rem** [comment]
Dans les faits, c'est une demande qui n'est pas de moi, juste que c'est compliqué de concevoir un site sans contenu

**Comment by J9rem** [comment]
> 
> 
> Des sources d'image dans lesquelles on peut puiser :
> 
>     * Le compte instagram de Lilian Chardon, notre graphiste en chef !  https://www.instagram.com/cybermoyenage/
> 
>     * [Les pistes graphiques](https://docs.google.com/presentation/d/1Cgfx4ElLykhSURb5ykI19RY9JrLnnlA76DFXSwDlTSw/edit?usp=sharing) de Lilian, Boris et Audrey notre équipe de designers / Graphistes !

Au fait @GuillaumeAV , pour les photos du compte Instagram, as-tu un fichier de licence Open de la part de Lilian ? (car sinon je ne peux pas intégrer les images dans les sources, ... vu que le site est en open source)

**Comment by GuillaumeAV** [comment]
@J9rem pour info, on a les droits pour 50 ans ;) https://drive.google.com/drive/folders/1lAmn4IvFsOOkVr_Hpz5ZPHLZKMKAfJr8
