### ISSUE TITLE
BUG : Onglet PERSONNES non accessible sur le back-office 

### ISSUE THREAD

**Issue by ChloeCruzel** [chemins-de-la-transition/semapps#488]
Assez urgent car initiatives en attente de création profil personne "acteur"

 ![image](https://user-images.githubusercontent.com/102050177/180979060-41bd5f28-2078-4f4e-8223-ab3ab55d293f.png)

**Comment by srosset81** [comment]
C'est bon c'est corrigé
https://admin.lescheminsdelatransition.org/Person
Mais il y a un problème de cache (https://github.com/assemblee-virtuelle/semapps/issues/1017) qui peut obliger à faire une mise à jour forcée.
