### ISSUE TITLE
Ouvrir les liens externes dans une nouvelle fenêtre

### ISSUE THREAD

**Issue by Mathieu-CdlT** [chemins-de-la-transition/semapps#489]
Serait-il possible de faire en sorte que les liens externes s'ouvrent dans une nouvelle fenêtre ? 
Ca éviterait que les utilisateurs sortent de la plateforme. 

Même chose sur le fait qu'on ait la possibilité d'ouvrir certains liens (exemple les "pages mentions légales, a propos...") dans de nouvelles fenêtres.

**Comment by srosset81** [comment]
Pour les liens généré par Markdown, il suffirait a priori de passer la props overrides au composant MarkdownField:

```jsx
<MarkdownField overrides={{ 
  a: {
    props: {
      target: '_blank',
      rel: 'nofollow noopener'
    }
  }
}} />
```

Voir https://github.com/probablyup/markdown-to-jsx#optionsoverrides---override-any-html-tags-representation
