### ISSUE TITLE
Fournir les données à implémenter dans la plateforme CdlT

### ISSUE THREAD

**Issue by GuillaumeAV** [chemins-de-la-transition/semapps#49]
Ces données concernent à priori et sans doute prioritairement (?) 
- Les lieux
- Les événements
- Les chemins / parcours 

 @laurecoplo @Mathieu-CdlT @GuillaumeAV @bouviermullerp j'avais amorcé [un doc pour l'ontologie CldT](https://docs.google.com/spreadsheets/d/1PacHwzI__5FzYZx1DxD5bFlLDx6MMWfR8-7N6PH9z44/edit?usp=sharing), pour les classes et relations, je viens de créer un nouvel feuillet pour les données spécifiques à chaque concept (Lieux, events, chemins / parcours

**Comment by GuillaumeAV** [comment]
@AudreyCDLT @Mathieu-CdlT @bouviermullerp 
j'ai renseigné quelques dataproperties (attributs) en plus sur le doc => [N'hésitez pas à contribuer si vous le souhaitez!](https://docs.google.com/spreadsheets/d/1PacHwzI__5FzYZx1DxD5bFlLDx6MMWfR8-7N6PH9z44/edit?usp=sharing)

**Comment by srosset81** [comment]
Fait ici
https://docs.google.com/spreadsheets/d/1y8WjrJxVV9i8ji2m2Y2D2HBp1MaYxzSaMSRuji8rwz4/edit
