### ISSUE TITLE
Profils acteurs ne peuvent pas acceder à la modification de leur organisation

### ISSUE THREAD

**Issue by Mathieu-CdlT** [chemins-de-la-transition/semapps#491]
Au moins pour les profils orgas créés par les CdlT pour le compte d'orgas, les personnes (acteurs) membres de l'orga n'ont pas accès à la modification de leur fiche orga. 

Ex: Nehom avec le profil acteur de Aurore Chatain

**Comment by ChloeCruzel** [comment]
Petite précision suite à quelques tests réalisés : Lorsqu'un profil personne "acteur" crée un profil orga de son interface front-office : impossible de savoir du back-office qui l'a proposé. On ne retrouve pas cette information. 

Ma réflexion/proposition : si possible, il faudrait une rubrique "Personnes Référentes" dans l'onglet "relations" qui permettrait de renseigner la ou les personne(s) qui ont droit de modification sur le profil orga ou qui indiquerait automatiquement l'acteur.rice qui l'a créé à partir de son espace du front-office. 

Ce fonctionnement pourrait être généralisé aux fiches évènements et lieux. Ainsi le nom de la personne ne serait pas forcément visibilisé en mode affichage. Aujourd'hui, les personnes ayant droit de modification des fiches sont celles renseignées dans la rubrique "organisateurs" ou "hôtes", or parfois elles n'ont pas forcément envie d'apparaitre (ou ce n'est pas correct) et préfèrent que ce soit leur organisation qui ait cette désignation.

**Comment by srosset81** [comment]
Vous pouvez le voir depuis le backoffice en cliquant sur le bouton "Permissions" en haut à droite de la fiche et en regardant qui a le droit de modification de la fiche.

![Capture d’écran de 2022-08-11 17-31-27](https://user-images.githubusercontent.com/17931931/184171718-306b4229-250f-470b-bdd9-575d7821a547.png)

Dans l'issue #312 il est question de permettre au créateur d'une ressource de donner le droit de modification à d'autres personnes.

Au niveau des données elles-mêmes, il y a un prédicat `dc:creator` qui est enregistré au moment de la création de l'organisation. Il pourrait être rendu visible dans le backoffice.

**Comment by ChloeCruzel** [comment]
Je relance cette issue car il n'est pas possible pour les personnes n'ayant pas créé leur organisation (car nous l'avons fait à leur place) d'y avoir accès via le front-office dans "mes organisations". 
Ceci est problématique car nous avons créé pas mal d'organisations pour nos acteurs au démarrage et nous pouvons pas leur donner la main.

**Comment by Mathieu-CdlT** [comment]
Le commentaire de Chloé fait référence à l'association Néhom (coloc de bureau) qui ne parvient pas à faire des modifs.

**Comment by srosset81** [comment]
OK merci pour les précisions, je regarde ça !

**Comment by srosset81** [comment]
C'est bon, c'est réglé (en cours de déploiement). Il y avait un double bug (https://github.com/chemins-de-la-transition/semapps/commit/bbbe10a6e5ce86febcfdbc61064820c0914caf41)

**Comment by Mathieu-CdlT** [comment]
Cool ! Merci :)
