### ISSUE TITLE
La plateforme est plantée !

### ISSUE THREAD

**Issue by GuillaumeAV** [chemins-de-la-transition/semapps#492]
![Capture d’écran de 2022-07-30 10-10-59](https://user-images.githubusercontent.com/6160028/181891657-e0a4cfd4-d03d-4221-9581-6f0cf012f111.png)
![Capture d’écran de 2022-07-30 10-09-57](https://user-images.githubusercontent.com/6160028/181891714-24a6646f-1545-4105-b434-8c06e8508ebe.png)

**Comment by srosset81** [comment]
C'est dû au problème de cache signalé ici: https://github.com/chemins-de-la-transition/semapps/issues/488
Il faut faire CTRL+MAJ+R pour forcer la mise à jour
J'ai fait une mise à jour de SemApps pour supprimer le cache (https://github.com/assemblee-virtuelle/semapps/issues/1017)
Le cache en question ne reste que 24h, donc la plateforme devrait fonctionner à nouveau pour tous d'ici à peu de temps
