### ISSUE TITLE
Onglet contact manquant pour profils personne et organisation

### ISSUE THREAD

**Issue by ChloeCruzel** [chemins-de-la-transition/semapps#493]
Que ce soit en version "édition" du front-office ou à partir du back-office, il n'y a **pas d'onglet "contact"** qui permet de collecter les coordonnées des personnes ou organisations. 

Or, nous offrons la possibilité de contacter les personnes et organisations sur la plateforme. 

![image](https://user-images.githubusercontent.com/102050177/182100740-a381faae-e1c5-4953-ae10-d50df481db9e.png)

![image](https://user-images.githubusercontent.com/102050177/182100859-76c3c1f8-8764-4f61-ba33-7c99bab47818.png)

Deux problèmes : 

* PROFIL ORGA : on ne peut pas renseigner d'adresse mail de contact, ainsi **impossible pour une personne de contacter l'organisation**.

![image](https://user-images.githubusercontent.com/102050177/182101103-e34d7218-4ad0-4432-88a4-fa5943ae18c5.png)

* PROFIL PERSONNE : une adresse mail est renseignée à la création du profil. Cela dit, sur les profils personnes les + récents, elle ne s'affiche ni en mode "édition" du front-office, ni dans le back-office. Donc **impossible de voir a posteriori quelle adresse mail a été choisie au départ**. Ce qui rend **difficile** la **gestion des bugs liés aux profils personnes + l'accompagnement lors de difficultés de connexion**. Sans parler qu'il n'est **pas possible de changer l'adresse mail de contact** si besoin.  Rq : pour les profils personnes les + anciens, l'information est donnée dans le back-office en mode affichage mais impossible de modifier car pas de rubrique dédiée en mode "édition". 

![image](https://user-images.githubusercontent.com/102050177/182101293-5ef9b0d0-bfad-4843-85cc-36fbdd88b4c1.png)

**Comment by srosset81** [comment]
Pour les organisations, il suffit d'ajouter le prédicat `pair:e-mail` dans le backoffice. Je crois que pour le moment on ne peut modifier l'email que depuis le frontoffice.

Pour les personnes, c'est lié à l'issue #221
