### ISSUE TITLE
Partenaires affichés sur la homepage : ajouter nouveau prédicat indépendant

### ISSUE THREAD

**Issue by clemenceCDLT** [chemins-de-la-transition/semapps#496]
Ajouter un prédicat spécifique pour les partenaires de la homepage, sinon si une orga nous choisi en partenaire elle est automatiquement affichée sur la homepage. 
Afficher ce prédicat seulement pour Les Chemins de la Transition

**Comment by srosset81** [comment]
Une alternative, peut-être plus propre, serait de créer un statut "Featured" qu'on pourrait appliquer aux organisations depuis le backoffice. Cela indiquerait qu'on veut mettre en avant une organisation sur la homepage.

**Comment by clemenceCDLT** [comment]
Ok, du coup on gèrerait ça depuis la page orga de chaque partenaire ?

**Comment by GuillaumeAV** [comment]
huum ah oui ca pose une bonne question ... Ca suppose d'assumer que les admin ont un accès permanent en édition au profil des orgas utilisatrices ...

**Comment by srosset81** [comment]
Oui effectivement ça obligerait à aller sur chaque organisation et à la "tagger" avec le statut "Featured".

C'est une proposition, pas forcément la meilleure solution.

**Comment by clemenceCDLT** [comment]
@GuillaumeAV @Mathieu-CdlT Pour l'instant j'ai fait cette solution (tagger depuis les organisations sur le backoffice laquelle on affiche sur la homepage : https://github.com/chemins-de-la-transition/semapps/pull/504 ), est-ce que c'est ok ou vous préférez faire différemment ?

**Comment by GuillaumeAV** [comment]
C'est goood !
