### ISSUE TITLE
Suivi de contact

### ISSUE THREAD

**Issue by bouviermullerp** [chemins-de-la-transition/semapps#5]
En tant que Laure (profil contributeur), je peux documenter le suivi des mes contacts avec les partenaires.

Si je suis connecté et et que je me rends sur la page d'un partenaire, je peux : 
- ajouter un compte-rendu (sous forme de texte) auquel sera lié la date du jour
- lire les comptes-rendus précédents.

**Comment by srosset81** [comment]
Lié à #58

**Comment by srosset81** [comment]
Fait https://github.com/chemins-de-la-transition/semapps/issues/58
