### ISSUE TITLE
Quelle est l'intéraction quand on s'inscrit quelque part ?

### ISSUE THREAD

**Issue by bouviermullerp** [chemins-de-la-transition/semapps#50]
Il y a 2 possibilité de contact pour être mis en lien - participer à un évènement.
- Quand c'est un évènement pontcuel (hors parcours) : l'accuillant peut indiquer la manière dont on peut réserver (HelloAsso par exemple), il y a un lien.
- Il est aussi possible d'être mis en contact, si l'accueillant le souhaite. Il peut remplir son adresse email. Celle-ci est cachée pour le visiteur, qui a juste un bouton "me contacter" qui ouvre un formulaire et qui enverra un mail.

- Quand c'est pour un parcours, alors il y a un bouton "candidatez" qui ouvre un formulaire de contact et qui envoie un mail à une adresse à définir (de type parcours@cdlt.com

**Comment by srosset81** [comment]
Je m'occupe du formulaire de contact, Julien s'occupera des formulaires de réservation.

**Comment by srosset81** [comment]
Pour info, le formulaire de contact est visible ici:
https://app.lescheminsdelatransition.org/Place/https%3A%2F%2Fdata.lescheminsdelatransition.org%2Fplaces%2Fla-piscine/show

**Comment by GuillaumeAV** [comment]
Je clos cette issue qui est à priori résolue ;)
