### ISSUE TITLE
Créer un champ "débouchés métiers"

### ISSUE THREAD

**Issue by Mathieu-CdlT** [chemins-de-la-transition/semapps#501]
Il serait hyper interessant de pouvoir créer une rubrique débouchés métiers, en particulier pour les événements (+ Voyages + Chemins?) où l'on puisse indiquer les métiers auxquels les formations peuvent conduire. 

A savoir si on utilise ESKO + ajout de nouveaux métiers dans la base ?

**Comment by clemenceCDLT** [comment]
Pour l'instant on a le champ "Idées de débouchés vers des métiers de la transition" sur les événements et sur les chemins, je peux le rajouter sur les voyages. Et on avait mis juste un champ libre pour l'instant.

**Comment by GuillaumeAV** [comment]
On pourra pointer sur le référentiel métier d'ESCO : https://esco.ec.europa.eu/fr/classification/occupation_main qui est différent de celui qu'uon utilise et qui concerne les apititudes !

**Comment by Mathieu-CdlT** [comment]
Je suis pas sûr que ce soit pertinent... 
J'ai fait qq tests
le métier "facilitateur tiers lieux" ou meme "facilitateur" n'existe pas sur ESCO. Idem si tu écris "poele de masse", rien ne sort et pourtant c'est des métiers sur lesquels pourraient déboucher les formations proposées.  
Du coup, si ESCO n'est que sur des métiers classiques, ca le fera pas

**Comment by GuillaumeAV** [comment]
Je propose de partir d'une complétion sur ESCO et si rien, de renseigner de nouvelles compétences, en attendant de trouver mieux (bases de données de métiers de la transition .. Il y avait un appel à projet à ce sujet il y a peu d'ailleurs - mais je me demande si ce n'est pas nous qui pourrions avoir vocation à la créer (un élément du modèle économique de l'asso ?) !  Il faut en tout cas je crois qu'on parte de l'existant et de données structurées pour la cohérence de notre démarche !

**Comment by clemenceCDLT** [comment]
Utiliser un concept comme pour les secteurs d'activité et mots clés. Comme ça on a une base de métiers que l'on peut enrichir, des suggestions quand on remplit et on a des données structurées.
