### ISSUE TITLE
Je ne parviens pas à sauvegarder des modifs sur un voyage à partir d'admin.cdlt

### ISSUE THREAD

**Issue by GuillaumeAV** [chemins-de-la-transition/semapps#514]
https://admin.lescheminsdelatransition.org/Course/https%3A%2F%2Fdata.lescheminsdelatransition.org%2Fcourses%2Fvoyage-inaugural-des-chemins-de-la-transition-a-velo/1

**Comment by srosset81** [comment]
Je ne reproduis pas, j'arrive bien à éditer ce parcours. 
C'était peut-être lié à https://github.com/chemins-de-la-transition/semapps/issues/519 ?
