### ISSUE TITLE
Bug affichage localisation

### ISSUE THREAD

**Issue by srosset81** [chemins-de-la-transition/semapps#516]
![Capture d’écran de 2022-09-19 11-15-31](https://user-images.githubusercontent.com/17931931/190986388-03e6c369-be19-4108-a8bf-860532fba56e.png)

https://lescheminsdelatransition.org/Event/https%3A%2F%2Fdata.lescheminsdelatransition.org%2Fevents%2Fatelier-brico-vetements-fabrication/show

**Comment by Mathieu-CdlT** [comment]
Hello, 

A priori, quand on renseigne des adresses (hors lieux pré-enregistrés) cela ne s'affiche pas sur le résultat des événéments affichage liste 
On avait évoqué le fait de pouvoir afficher "ville (num de departement)". 

Est ce qu'on pourrait revoir ça ?

**Comment by srosset81** [comment]
Je transfers vers #538 car c'est une autre issue.
