### ISSUE TITLE
Inférer les événements constitutifs des parcours ?

### ISSUE THREAD

**Issue by GuillaumeAV** [chemins-de-la-transition/semapps#52]
@srosset81 il y a avait cette question en suspens ... 

Afin de ne pas voir les événements constitutifs des parcours affichés dans la section événement : 
* Faut-il inférer que puisqu'ils font partie des parcours on ne les affiche pas dans les événements
* Ou faut-il créer une sous classe d'évenement pouvant par exemple s'intituler "Etape", de manière à ne pas les afficher dans la liste d'évenements ? 

Avec Pierre, l'option 1 inférence nous parait intéressante ;) 
La bise !

**Comment by srosset81** [comment]
A priori le plus simple est de regarder s'ils font partie d'un parcours ou non.

**Comment by srosset81** [comment]
Comme discuté via le chat avec @Mathieu-CdlT, on va pour finir afficher tous les événements (liés ou non à un parcours) et on affichera un bandeau + un bouton "S'inscrire au parcours" pour les événements liés à un parcours. Je ferme donc cette issue.

**Comment by GuillaumeAV** [comment]
C'est super comme solution je crois !
