### ISSUE TITLE
Bug Affichage fiche événements

### ISSUE THREAD

**Issue by Mathieu-CdlT** [chemins-de-la-transition/semapps#528]
Hello, 

Un petit bug est apparu sur les fiches événements (frontend) : 
- La rubrique Secteur d'activité (doit être en bas) apparait 2 fois 
- La rubrique description s'affiche également 2 fois 
- Les mots clés s'affichent aussi 2 fois

Par ailleurs on a 2 couleurs et types de police apparaissent, c'est pas très sexy. 

Des possibilités de corriger ça ? 
Merci merci :)

exemple : https://lescheminsdelatransition.org/Event/https%3A%2F%2Fdata.lescheminsdelatransition.org%2Fevents%2Fformation-autoproduire-ses-semences-potageres/show

**Comment by srosset81** [comment]
Corrigé (https://github.com/chemins-de-la-transition/semapps/commit/99cca39edaac5a467257570fc91575d901f9fed4), en prod dans 3 min
