### ISSUE TITLE
Scroller en haut de page lorsqu'on va sur une page détails

### ISSUE THREAD

**Issue by Mathieu-CdlT** [chemins-de-la-transition/semapps#536]
Quand on clique sur une fiche détail (événements, lieux, chemins, orgas), la page se charge et affiche automatiquement le milieu de la page au lieu d'arriver en haut de page.

Est ce qu'il serait possible de corriger ça pour que l'on arrive sur la haut de page ?

**Comment by srosset81** [comment]
On a un script qui gère le scrolling automatique en haut de page, mais apparemment il ne marche plus bien.

**Comment by srosset81** [comment]
Alors après tests, le scroll en bas ne se fait que sur les ressources qui ont une carte géographique, donc peut-être lié à React-Leaflet.

Par contre ce qui est bizarre, c'est que je ne reproduis pas en local, ce qui rend le debugging plus compliqué.

Comme on va devoir mettre à jour React-Leaflet (issue #540), je vais d'abord voir si la mise à jour règle le problème.

**Comment by Mathieu-CdlT** [comment]
De mon coté, je ne reproduis plus sous Firefox, par contre Chloé reproduit le pb sur internet explorer

**Comment by srosset81** [comment]
Apparemment le problème est au niveau du composant pour ajouter les commentaires. Je vais fixer ça...

**Comment by srosset81** [comment]
Réglé ! Déployé dans 10-15 minutes...
