### ISSUE TITLE
Répétition éléments fiche événement

### ISSUE THREAD

**Issue by Mathieu-CdlT** [chemins-de-la-transition/semapps#537]
Hello, 

On a laissé passé la répétition des "moyens matériels et pédagogiques" sur les fiches événements.... 

Est ce qu'il serait possible de corriger? 
Merci

**Comment by Mathieu-CdlT** [comment]
Closed ? 

De mon coté, y'a toujours le bug : https://lescheminsdelatransition.org/Event/https%3A%2F%2Fdata.lescheminsdelatransition.org%2Fevents%2Fformation-reparation-cycles-avec-la-maison-du-velo-septembre/show

**Comment by srosset81** [comment]
Oui c'est pas encore déployé, désolé.
