### ISSUE TITLE
Page blanche quand je clique sur un topic .. 

### ISSUE THREAD

**Issue by GuillaumeAV** [chemins-de-la-transition/semapps#549]
Yo ! 

Il y a un bug je crois quand on clique sur un topic à partir de [cet événement (bizarre)](https://lescheminsdelatransition.org/Event/https%3A%2F%2Fdata.lescheminsdelatransition.org%2Fevents%2Fdecouverte-de-la-ressourcerie-des-fourmis-vertes/show) .. 
https://lescheminsdelatransition.org/LEP?filter=%7B%22pair%3AhasTopic%22%3A%22https%3A%2F%2Fdata.lescheminsdelatransition.org%2Ftopics%2Feconomie-circulaire%22%7D
![Capture d’écran du 2022-11-25 11-18-14](https://user-images.githubusercontent.com/6160028/203960815-375ebf5a-405f-4729-ab44-ea83e2504ac5.png)

**Comment by GuillaumeAV** [comment]
Je viens de reproduire le bug à partir de https://lescheminsdelatransition.org/Event/https%3A%2F%2Fdata.lescheminsdelatransition.org%2Fevents%2Fdecouverte-de-deuxieme-vie-deuxieme-chance/show

**Comment by srosset81** [comment]
Fixé ici https://github.com/chemins-de-la-transition/semapps/commit/b05e5dae395aab27cc3705c340c7654292eb8389 et déployé d'ici à quelques minutes

Le moteur de recherche gérait mal lorsque les résultats étaient filtrés car ils sont passés. En l'occurence le topic "économique circulaire" que tu cliquais ne renvoyait aucun événement, car par défaut le moteur de recherche ne montre pas les événements passés, et l'événement depuis lequel tu cliquais sur le topic ("Découverte des fourmis vertes") était lui-même passé.
