### ISSUE TITLE
Bug "Erreur de communication avec le serveur

### ISSUE THREAD

**Issue by MaximeCDLTOcc** [chemins-de-la-transition/semapps#550]
Hello, 
Une utilisatrice de la plateforme m'a informée qu'elle n'arrive à pas créer ou modifier d'élèments (profil acteur, profil orga ou event) car ? lorsqu'elle enregistre ses infos un message d'erreur "erreur de communication avec le serveur" apparait. Elle n'arrive donc pas à modifier les informations de son profil ou à valider nouveaux event. Est-ce déjà arrivé ? Une piste de solution ?

![Message serveur](https://user-images.githubusercontent.com/119333195/204484478-f0ba9e11-28fc-4f87-8613-00f919aa249f.JPG)

La seule manière qu'elle a trouvé pour valider son évènement et d'enregistrer à chaque nouveau champ rempli: " je n'ai réussi à effectuer des modifications que bloc par bloc, par exemple : je mets la date, j'enregistre, je renseigne le programme, j'enregistre, etc..."

Savez-vous d'où cela peut provenir ?

**Comment by MaximeCDLTOcc** [comment]
@srosset81 peut-être une idée ?

**Comment by GuillaumeAV** [comment]
![Capture d’écran du 2022-12-07 10-52-09](https://user-images.githubusercontent.com/6160028/206146639-945ed2f6-b67a-4827-9981-5aadb144456c.png)

**Comment by GuillaumeAV** [comment]
![Guillaume_Rouyer_2022](https://user-images.githubusercontent.com/6160028/206147263-8e794fd3-5281-47f2-b284-760016e19c31.jpg)

**Comment by srosset81** [comment]
A priori c'était le même bug que #555 
Cela arrivait lorsqu'on met une image

Fixé ici https://github.com/chemins-de-la-transition/semapps/commit/99c62c9f8290bb39420b93aa98b3f4d98e5ed205

**Comment by MaximeCDLTOcc** [comment]
Cool merci beaucoup !
