### ISSUE TITLE
Mettre la fonction publier / dépublier sur les CLEPs et PAIRs du back-office 

### ISSUE THREAD

**Issue by GuillaumeAV** [chemins-de-la-transition/semapps#551]
A l'heure actuelle, nous avons la fonction publier / dépublier sur les voyages CdlT dans le back-office, ce qui est très bien. 
Par défaut, le voyage n'est pas publié, et je crois qu'on utilise "status" pour renseigner sur le voyage est publié ou non. 

L'objectif est de généraliser sur le back-office cette fonction publier / dépublier, de manière à ce qu'on puisse, sur le back-office, renseigner notre veille et un max de données susceptibles de basculer - lorsqu'elles seront validées - sur le front-office. 

Muni de cette fonction, le back-office pourrait alors agréger de nombreuses données, y compris en provenance de sources externes, type Transiscope ou autres ... 

La conséquence serait un intérêt particulier du back-office, notamment pour les aspirants voyageurs qui pourraient y avoir accès afin de préparer leur voyage. 

Toutes les personnes ayant accès au back-office (ce seront les membres de l'asso) doivent pouvoir voir ou ajouter des données. 
Les personnes ayant le rôle administrateur et/ou contributeur doivent pouvoir publier / dépublier. 

------- 
Dans un second temps : 
L'idée sera de permettre à tout.e.s, depuis le front-office, de proposer des PAIRs / CLEPs, qui pourront arriver dans un espace dédié à la modération d'items ...  
Je ferai une autre issue dédiée !

**Comment by VincentFarcy** [comment]
Salut @GuillaumeAV ,

j'attaque cette évolution et je me heurte à un problème d'ontologie.  

Actuellement on utilise `pair:hasStatus` pour gérer la notion de publication des voyages.  
Or ce prédicat est utilisé pour gérer d'autres notions :

events: 	open/finished
place: 	featured (?)
path:		imagine/valide-par-les-cdlt  

D'autres statuts sont référencés mais ne semblent pas utilisés (ex: "complet" pour courses) :
https://admin.lescheminsdelatransition.org/Status

1 - Il serait intéressant je pense de faire le tour des statuts réellement utiles.  

2 - Pour ajouter la notion de publication aux CLEV :
Il ne me semble pas qu'il soit possible actuellement de typer le prédicat, pour préciser qu'il s'agit d'un statut "de publication". Il faudrait donc je pense créer un nouveau prédicat commun aux 4 CLEV : hasPublicationStatus ?

Dis moi ce que tu en penses

**Comment by VincentFarcy** [comment]
Peux-tu repréciser ce que recouvre les PAIRs ?

**Comment by VincentFarcy** [comment]
Autre point : actuellement sauf erreur de ma part la publication ne bloque que l'affichage dans les listes.
On peut malgré tout accéder à l'élément par son url ou au travers d'un lien.
Ex : j'ai un événement publié sur un lieu non publié, je peux accéder au lieu non publié via le lien créé par la relation entre l'événement et le lieu.
Est ce bien le comportement souhaité ?

**Comment by GuillaumeAV** [comment]
Salut @VincentFarcy ! 
De retour de vacances .. 

>  Il faudrait donc je pense créer un nouveau prédicat commun aux 4 CLEV : hasPublicationStatus ?
Oui très bonne idée ! 

> Peux-tu repréciser ce que recouvre les PAIRs ?
De manirère générique : Projet, Acteur, Idée, Ressource. 
Dans le contexte de la publication : Organisations, en plus des CLEVs

> la publication ne bloque que l'affichage dans les listes. Est ce bien le comportement souhaité ?
Huuum en effet c'est un point auquel on n'a pas pensé ... J'aurais tendance à laisser comme ça, jusqu'à ce qu'un problème éventuel se pose ...

**Comment by VincentFarcy** [comment]
Hello @GuillaumeAV
Je suppose qu'on initialise l'existant à "publié" ?
Peux-tu confirmer ?

**Comment by GuillaumeAV** [comment]
Yes !

**Comment by VincentFarcy** [comment]
Salut @GuillaumeAV !
La PR est en cours de review par Seb.
A noter : Le statut de publication sur les orga bien qu'en place n'a actuellement pas d'effet puisque les orgas ne sont pas présentées en liste sur le site.

**Comment by GuillaumeAV** [comment]
Super !! Merci beaucoup @VincentFarcy ! 

Pour les orgas, en effet, mais ca va changer, on va les faire apparaitre très bientôt !
