### ISSUE TITLE
Bug à la saisie des photos sur les profils perso à minima

### ISSUE THREAD

**Issue by GuillaumeAV** [chemins-de-la-transition/semapps#552]
Ca me donne "erreur de connexion avec le serveur"
Lié à la compression des images @srosset81 ?

**Comment by GuillaumeAV** [comment]
Idem #555

**Comment by srosset81** [comment]
Fixé https://github.com/chemins-de-la-transition/semapps/commit/99c62c9f8290bb39420b93aa98b3f4d98e5ed205
