### ISSUE TITLE
Bug à la saisie des compétences

### ISSUE THREAD

**Issue by GuillaumeAV** [chemins-de-la-transition/semapps#553]
Toujours sur le profil perso .. 
Je ne paviens à la cliquer sur "ajouter" quand j'essaie d'ajouter une nouvelle compétence ... Facile à corriger tu crois @srosset81 ?

**Comment by srosset81** [comment]
Je reproduis. On est obligé d'effacer ou ajouter un caractère sur la boîte de dialogue pour avoir l'option "Ajouter XXX au dictionnaire", qui permet ensuite de cliquer sur le bouton Ajouter. Je regarde pour corriger le composant LexiconCreateDialog qui gère ça.
