### ISSUE TITLE
Bug à l'enregistrement du profil

### ISSUE THREAD

**Issue by GuillaumeAV** [chemins-de-la-transition/semapps#555]
@srosset81 Message de Jean-Baptiste (https://admin.lescheminsdelatransition.org/Person/https%3A%2F%2Fdata.lescheminsdelatransition.org%2Fusers%2Fjbfonta)

Salut Guillaume j'ai enregistré un profil sur cdlt mais il a disparu? 
Y a une étape modération ou j'ai perdu ce que j'avais écrit définitivement ? 

J'avais cliqué sur Enregistrer. Ca avait l'air de fonctionner car j'ai du apercevoir le rendu quelques secones et puis rafraichissement automatique je dirais. Et plus de trace, voila, si ca peut aider ..

**Comment by GuillaumeAV** [comment]
Idem #552 

Je viens de tester à nouveau .. Ca me fait précisément ce que décris Jean Baptiste quand j'ajoute une photo ..

**Comment by srosset81** [comment]
Fixé https://github.com/chemins-de-la-transition/semapps/commit/99c62c9f8290bb39420b93aa98b3f4d98e5ed205
