### ISSUE TITLE
Les hôtes ne s'affichent pas .. 

### ISSUE THREAD

**Issue by GuillaumeAV** [chemins-de-la-transition/semapps#558]
![Capture d’écran du 2022-12-09 11-17-24](https://user-images.githubusercontent.com/6160028/206679596-f079fc99-ee04-4cd9-8ab4-de76f2990119.png)

**Comment by GuillaumeAV** [comment]
Chelou non ? En l'occurence, ici c'est Guillaume Rouyer et Alice Poggioli...

**Comment by srosset81** [comment]
Fixé e4e2ad33a57ceae5c7e71a9dbaf881858964fdcd. Il était pas prévu qu'il puisse y avoir plusieurs hôtes...
