### ISSUE TITLE
Display future ... and ongoing events

### ISSUE THREAD

**Issue by GuillaumeAV** [chemins-de-la-transition/semapps#560]
Hello, (from @Mathieu-CdlT )

Est ce qu'on aurait la possibilité de n'afficher par défaut sur les pages Chemins que les événements à venir avec un bouton "afficher les événements passés" comme on a sur les fiches lieux?

Sinon ca pollue grave et les sur certaines fiches, les premiers événements remontent à 2019.

La bise

**Comment by GuillaumeAV** [comment]
See also #259

**Comment by VincentFarcy** [comment]
@Tonfa 
C'est dispo en préprod : https://dev.app.lescheminsdelatransition.org/
PR : https://github.com/chemins-de-la-transition/semapps/pull/632
Temps passé = 45mn
