### ISSUE TITLE
Bug duplication event front-office

### ISSUE THREAD

**Issue by MaximeCDLT** [chemins-de-la-transition/semapps#562]
Hello il semblerait que lorsque l'on créé un event à travers "dupliquer un événement" depuis le front-office notamment, il ne se charge pas comme c'est le cas ici pour le module 2 : https://lescheminsdelatransition.org/Activity/https%3A%2F%2Fdata.lescheminsdelatransition.org%2Fevents%2Fanimation-participative-module-2-pratiquer-une-animation/show

**Comment by VincentFarcy** [comment]
@Tonfa 
Le correctif est dispo en préprod : https://dev.app.lescheminsdelatransition.org/
PR : https://github.com/chemins-de-la-transition/semapps/pull/635
Temps passé = 3h pour le moment.  
Il reste à passer le traitement de migration pour corriger l'existant en préprod, j'attends un retour de Seb.
