### ISSUE TITLE
Créer un parcours

### ISSUE THREAD

**Issue by bouviermullerp** [chemins-de-la-transition/semapps#57]
En tant qu'utilisateur connecté sur le back-office je peux : 
- Démarrer la création d'un parcours.
- Le parcours est initialisé à l'état de "en cours de création". Il n'est pas visible sur la partie front-office.
   - L'utilisateur peut modifier le statut "arrêté" - "publié"
   - Le parcours qui a un statut "publié" est mis en ligne sur le front-office.
  
- Un parcours est composé de lieux. L'utilisateur peut ajouter/retirer un lieux à un parcours.

- Un parcours a plusieurs attributs : finalités pédagogiques, etc. [A compléter qui seront mis en ligne sur la partie Front.

- L'utilisateur peut également des éléments de suivi de la création de parcours : 
   - des comptes rendus. Ces comtpes rendu peuvent être liés à un lieu, ils ont une date et une zone de texte.

**Comment by srosset81** [comment]
Merci Pierre ! Ci-dessous mes commentaires.

> En tant qu'utilisateur connecté sur le back-office je peux :
> 
> * Démarrer la création d'un parcours.
> * Le parcours est initialisé à l'état de "en cours de création". Il n'est pas visible sur la partie front-office.
>   
>   * L'utilisateur peut modifier le statut "arrêté" - "publié"
>   * Le parcours qui a un statut "publié" est mis en ligne sur le front-office.

Nous avons déjà une classe CourseStatus. Je pourrais ajouter un bouton "Publier" qui permettra de faire passer du statut "En cours de création" à "Publié". Il faudra aussi que je réfléchisse à un mécanisme qui change automatiquement les droits de lecture d'un parcours en fonction de son statut (afin que les parcours non-publiés ne soient visibles que des administrateurs). Côté WebACL, il faudrait également créer un groupe "administrateurs" dans lequel seront ajouté automatiquement les utilisateurs qui ont ce UserType.

> * Un parcours est composé de lieux. L'utilisateur peut ajouter/retirer un lieux à un parcours.

Dans la [nouvelle ontologie](https://github.com/chemins-de-la-transition/semapps/issues/22) qui a été déployée sur le backoffice, les [parcours](https://app.lescheminsdelatransition.org/Course) sont composés d'événements et non de lieux. Ce sont les [chemins](https://app.lescheminsdelatransition.org/Path) qui sont composés de lieux. Cependant dans la v1 les chemins ne sont pas amenés à figurer sur le frontoffice, seulement les parcours.

@bouviermullerp peux-tu confirmer que, dans cette issue, tu parles bien de création de **parcours** et non de **chemins** ?

> * Un parcours a plusieurs attributs : finalités pédagogiques, etc. [A compléter] qui seront mis en ligne sur la partie Front.

En attente de la liste exacte. Pour le moment il y a des attributs sur les chemins et d'autres sur les parcours, mais l'ontologie permet de les attribuer à l'un ou à l'autre.

> * L'utilisateur peut également des éléments de suivi de la création de parcours :
>   
>   * des comptes rendus. Ces comtpes rendu peuvent être liés à un lieu, ils ont une date et une zone de texte.

OK j'ajouterai donc une classe Document et DocumentType.

**Comment by bouviermullerp** [comment]
@srosset81 pardon pour le qui pro quo ! j'étais fatigué et confirme bien ce qui est dit dans l'ontologie.

**Comment by srosset81** [comment]
Je ferme cette issue car tout a été mis dans des issues séparées.
Il me reste à faire https://github.com/chemins-de-la-transition/semapps/issues/58
