### ISSUE TITLE
Image ne s'affiche pas sur back-office

### ISSUE THREAD

**Issue by GuillaumeAV** [chemins-de-la-transition/semapps#571]
Quand je renseigne une image sur un chemin, elle apparait sur le front office mais pas sur le back office. 
Exemple : https://admin.lescheminsdelatransition.org/Path/https%3A%2F%2Fdata.lescheminsdelatransition.org%2Fpaths%2Fchemin-de-la-velo-francette/show

Ce serait bien que l'image soit aussi présente sur le back-office !

**Comment by VincentFarcy** [comment]
@Tonfa 
PR : https://github.com/chemins-de-la-transition/semapps/pull/633
Dispo en préprod : https://dev.app.lescheminsdelatransition.org/
