### ISSUE TITLE
Configuring account creation

### ISSUE THREAD

**Issue by ixxie** [chemins-de-la-transition/semapps#575]
When trying to create an an account in our new [CDLT installation](https://pathways.gen-europe.org/), we are greeted by the login screen:

![image](https://github.com/chemins-de-la-transition/semapps/assets/20320695/4c3ca678-555e-40f1-a073-e5afd2629dca)

When trying to press the button, we are redirected to lescommunes.org but get an error:

![image](https://github.com/chemins-de-la-transition/semapps/assets/20320695/3acb763d-27d8-47a7-99ec-17555ecbf735)

Presumably, this makes sense since our new deployment isn't authorized to authenticate with lescommunes.org. Would be correct to assume that we must configure an OIDC provider for the app the work?

This should probably be expanded in the [deployment instructions](https://github.com/chemins-de-la-transition/semapps/tree/master/deploy).

**Comment by srosset81** [comment]
Hi Matan
I sent you the password by email, and added your server in the list of valid redirection URL.
I also added a sentence about valid URLs in the deployment instructions: https://github.com/chemins-de-la-transition/semapps/commit/38ef6ef50626dfe2a89d39e162d567abb87b1089

**Comment by ixxie** [comment]
Thanks @srosset81, it works now. FWIW the sentence added to the docs still seems confusing, because it seems to imply something needs to be done in the semapps deployment, when in fact it needs to be done on the end of the OIDC provider.
