### ISSUE TITLE
Join the community could be more user friendly

### ISSUE THREAD

**Issue by GuillaumeAV** [chemins-de-la-transition/semapps#579]
From Romeo : 
- Button to join the community brings you to the forum... where you find yourself a bit lost
- Simplify the forum welcome (first step, introducing yourself, etc.)
- 
We could for exemple better design and link to this post :
https://forums.lescheminsdelatransition.org/t/bienvenue-sur-les-chemins-de-la-transition/152

**Comment by Tonfa** [comment]
@maxime-senza to change the link "Join the community" to https://forums.lescheminsdelatransition.org/t/bienvenue-sur-les-chemins-de-la-transition/152

**Comment by maxime-senza** [comment]
done @Tonfa :)
