### ISSUE TITLE
Itération 1 : Implémentation des 1ères spéc fonctionnelles de la plateforme : Ontologie CdlT

### ISSUE THREAD

**Issue by GuillaumeAV** [chemins-de-la-transition/semapps#6]
L'enjeu de la première itération consiste à implémenter l'ontologie PAIR enrichie des concepts et relations de base qui permettront d'exprimer la spécificité métier des Chemins de la Transition, dans le cadre d'une instance SemApps + Archipel générique. 

L'implémentation de l'ontologie comporte une dimension technique + une dimension UX. Dans le cadre de cette première itération, on ne fera pas grand cas de l'UX, en faisant simplement "du mieux qu'on peut" .. 

Plus de détail sur les [spécifications fonctionnelles dans ce document](https://docs.google.com/document/d/1IwUlCyhlw-EYfsn2x2E51WFHWmLCYntXL9mPixkIo5E/edit?usp=sharing). 
Vous pouvez par ailleurs [accéder à l'ontologie ici](https://drive.google.com/file/d/1At5k3C77tSokGcwlmMIKSUJtuqCDveVv/view?usp=sharing) => Il faudra la mettre sur github et mettre en place un process d'évolution carré dans les plus brefs délais !

Ping @bouviermullerp

**Comment by bouviermullerp** [comment]
@GuillaumeAV cette issue doit être retravaillée pour être Agile.
Il n'est nécessaire de considérer des petits fonctionnalités, des petites briques. J'ai créé les issues #7 et #8 pour les missions 1 et 2.
La mission 2 est assez conséquente, il faudrait la détailler, voir la découper en plus petite tâche.
La mission 3 n'est pas clair pour Seb et moi à ce stade.
D'autres issues doivent être créé pour spécifier les autres missions

**Comment by bouviermullerp** [comment]
@GuillaumeAV cette issue est-elle résolue ?

**Comment by GuillaumeAV** [comment]
Yop ! Oui en effet on peut la considérer comme résolue, terminée !
Il n'y a plus de bugs et les principaux concepts, y compris thèmes, types, statuts sont implémentés !
