### ISSUE TITLE
Internationalize an item in AppBar.js

### ISSUE THREAD

**Issue by Tonfa** [chemins-de-la-transition/semapps#615]
I don't know how to internationalize the 'Se connecter' line 49 of the file [AppBar.js](https://github.com/chemins-de-la-transition/semapps/blob/403d3ed7e6ebf5747f75074ecf059b30567e1cec/frontoffice/src/layout/AppBar.js#L49)

Is anyone able to help?

**Comment by srosset81** [comment]
You can pass props to makeStyles like in this example:

https://v4.mui.com/styles/api/#examples-3

**Comment by VincentFarcy** [comment]
@Tonfa do you want to try with sebastian's explanations ?

**Comment by Tonfa** [comment]
Yes thank :)

**Comment by Tonfa** [comment]
I couldn't do it :(

I need help for this one.

**Comment by VincentFarcy** [comment]
@Tonfa it's done here on i18n branch : https://github.com/chemins-de-la-transition/semapps/commit/053f71623db75073e73d0f58bca66df6882fc750
