### ISSUE TITLE
Authentification timeout via les Communs

### ISSUE THREAD

**Issue by Tonfa** [chemins-de-la-transition/semapps#617]
We are getting a new error

{"name":"TimeoutError","message":"Timeout awaiting 'request' for 10000ms","code":"ETIMEDOUT"}

when login through les communs on https://pathways.gen-europe.org/

Any idea of what could be the cause? This is a new issue.

**Comment by srosset81** [comment]
Fuseki was down, the Docker container was killed probably because of a lack of memory. I restarted it and it works.

If you went on other parts of the website, you would probably have found other errors.

**Comment by Tonfa** [comment]
Amazing. Is it something me or @Angel Matilla ***@***.***> can
solve next time?
(Maybe with a procedure).

**Comment by srosset81** [comment]
Log to the server, go the `/app` folder and do `docker compose up -d`
