### ISSUE TITLE
Enable trips editing from the front office

### ISSUE THREAD

**Issue by GuillaumeAV** [chemins-de-la-transition/semapps#619]
To do this, create the form and assign the corresponding rights to travellers, actors, contributors and administrators.

**Comment by VincentFarcy** [comment]
travelers should be able to create new trips ?

**Comment by GuillaumeAV** [comment]
Yes ! Indeed we could merge travelers and actors, with same rights ..

**Comment by VincentFarcy** [comment]
Firstly, I propose to create the form using the same rights as for the other resources.
I notice that the required fields are not defined for trips, can you check it  @GuillaumeAV ?

**Comment by GuillaumeAV** [comment]
Super ! 

Pour les champs obligatoires, je dirais : 
Nom du voyage
Comment le décririez vous en une phrase ? 
Qui sont les organisateur.ice.s 
Adresse email

**Comment by VincentFarcy** [comment]
@GuillaumeAV and @Tonfa 
as the i18n branch is not yet merged, note that this improvement involves new translations in the front office

**Comment by VincentFarcy** [comment]
@GuillaumeAV the pull request is in progress
https://github.com/chemins-de-la-transition/semapps/pull/622

**Comment by VincentFarcy** [comment]
> I was suggesting to merge to lain branch "Offer and needs 152 with i18n" and comment the menus on the frontend to simplify these 3 branches work...
check with seb : he is the master !

**Comment by srosset81** [comment]
Good idea !
