### ISSUE TITLE
Des données non publiées apparaissent sur le front office .. 

### ISSUE THREAD

**Issue by GuillaumeAV** [chemins-de-la-transition/semapps#624]
@VincentFarcy c'est très bizarre, la menuise apparait en page d'accueil alors qu'elle n'est pas référencée en tant que lieu sur le front office (elle a le statut dépublié) .. Tu saurais dire d'où ca vient ? 
https://lescheminsdelatransition.org/Place/https%3A%2F%2Fdata.lescheminsdelatransition.org%2Fplaces%2Fla-menuise/show

**Comment by GuillaumeAV** [comment]
Problème identifié, problème à moitié résolu ? Ca demande beaucoup de travail ?

**Comment by VincentFarcy** [comment]
Quelques heures je pense, le temps de faire le tour de tous les composants et de mettre en place les filtres / redirections.
2 ou 3h je dirais.

**Comment by GuillaumeAV** [comment]
Si t'as un peu de temps ces prochains jours ce serait génial ..

**Comment by VincentFarcy** [comment]
Je pense que c'est jouable peut être cette semaine. Je te redis

**Comment by GuillaumeAV** [comment]
@VincentFarcy je ne sais plus si tu l'as gérée au final cette issue ?

**Comment by VincentFarcy** [comment]
@GuillaumeAV J'attendais le feu vert pour merger l'internationalisation d'abord.
Je m'en occuperai dans la foulée.
