### ISSUE TITLE
Fournir une spécification claire de l'ontologie CDLT

### ISSUE THREAD

**Issue by J9rem** [chemins-de-la-transition/semapps#65]
Pour pouvoir développer le front-office, @AudreyCDLT et moi, nous avons besoin d'une stabilité sur l’ontologie CDLT.
Est-il possible d'avoir le lien vers le document drive qui donne cette spécification ?

**Comment by bouviermullerp** [comment]
@J9rem la dernière version de l'ontologie est stockée ici https://github.com/chemins-de-la-transition/ontology
@GuillaumeAV en est le référent !

**Comment by J9rem** [comment]
merci ça m'aide.
Alors je n'ai peut-être pas été clair, dans ma question.
Quelles sont les données que doivent contenir les Event, Place, et Course ?
Par exemple, Event n'a pas de type dans la base de données alors qu'il semblerait que normalement un évènement a un type ? C'est un exemple.
https://github.com/chemins-de-la-transition/semapps/blob/master/backoffice/src/resources/Agent/Activity/Event/index.js

**Comment by srosset81** [comment]
EventType est défini dans l'ontologie PAIR
http://virtual-assembly.org/ontologies/pair-2020-winter/index-en.html#EventType

On peut l'ajouter si (et seulement si) c'est nécessaire (voir https://github.com/chemins-de-la-transition/semapps/issues/66)

**Comment by J9rem** [comment]
Y a-t-il un document existant qui référence le besoin ?
à défatu @bouviermullerp est-il possible de lister le besoin ici ?

**Comment by bouviermullerp** [comment]
@J9rem le besoin général ? Il y a un [cahier des charges](https://docs.google.com/document/d/1qgf9-FNbIrFaodyW3t8NsnhRUwi9OCwYQ6s5q_kJWZs/edit#heading=h.rh99div6bpga) haut niveau.
Peux-tu préciser stp ? (on peut s'appeler après 15h au besoin)

**Comment by J9rem** [comment]
Plus précisément :
un évènement contient-il bien ceci  SANS AVOIR DE TYPE ?
        'pair:label': 'Titre',
        'pair:description': 'Description',
        'pair:comment': 'Courte description',
        'pair:hostedIn': 'Lieu',
        'pair:aboutPage': 'Site web',
        'pair:startDate': 'Date de début',
        'pair:endDate': 'Date de fin',
        'pair:involves': 'Implique',
        'pair:hasTopic': 'Thèmes',
        'pair:partOf': 'Fait partie de'

**Comment by srosset81** [comment]
> Plus précisément :
> un évènement contient-il bien ceci SANS AVOIR DE TYPE ?
> 'pair:label': 'Titre',
> 'pair:description': 'Description',
> 'pair:comment': 'Courte description',
> 'pair:hostedIn': 'Lieu',
> 'pair:aboutPage': 'Site web',
> 'pair:startDate': 'Date de début',
> 'pair:endDate': 'Date de fin',
> 'pair:involves': 'Implique',
> 'pair:hasTopic': 'Thèmes',
> 'pair:partOf': 'Fait partie de'

C'est juste les traductions, pas tout est implémenté.
Il suffit d'éditer les ressources pour voir ce qui est implémenté.

https://app.lescheminsdelatransition.org/Event/https%3A%2F%2Fdata.lescheminsdelatransition.org%2Fevents%2Fa-la-decouverte-du-web-semantique

**Comment by J9rem** [comment]
Oui effectivement, ce sont les traductions, j'avais lu trop vite.

A quel endroit pourrions-nous avoir un fichier qui liste les champs qui sont définis ou à définir pour Event, Place, Course ?

**Comment by srosset81** [comment]
@GuillaumeAV avait produit ce fichier:
https://docs.google.com/spreadsheets/d/1PacHwzI__5FzYZx1DxD5bFlLDx6MMWfR8-7N6PH9z44/edit#gid=0

**Comment by J9rem** [comment]
Merci @srosset81 c'est exactement ce document qui pourrait nous servir de base de travail!
Est-il validé @bouviermullerp ?

**Comment by srosset81** [comment]
Il a été validé puisqu'il a servi de base pour l'ontologie.
Sur le deuxième onglet, seuls les éléments marqués "Intégrés" sont validés.
Par contre il n'y a pas forcément tout à implémenter.

Avec @AudreyCDLT on a convenu que je vais faire un tableau récapitulatif de tout ce que j'estime qu'il faut implémenter pour Place / Event / Course (en fonction de ma compréhension de l'ontologie et des différents échos que j'ai vu). Je l'envoie dès que possible et on pourra le valider tous ensemble à la réunion de demain 16h.

**Comment by J9rem** [comment]
et donc si je comprends bien, nous aurions pour les évènements hasSessionType ? est-ce bien ceci ?

**Comment by J9rem** [comment]
Je clos cette issue car les réponses ont été données en réunion du 1 juillet avec ce tableau : https://docs.google.com/spreadsheets/d/1y8WjrJxVV9i8ji2m2Y2D2HBp1MaYxzSaMSRuji8rwz4/edit#gid=1578368962

en lien avec le [backoffice](https://app.lescheminsdelatransition.org/)
et le [document initial sur l'ontologie](https://docs.google.com/spreadsheets/d/1PacHwzI__5FzYZx1DxD5bFlLDx6MMWfR8-7N6PH9z44/edit#gid=0)
