### ISSUE TITLE
Implémenter l'ontologie CDLT dans le backoffice

### ISSUE THREAD

**Issue by J9rem** [chemins-de-la-transition/semapps#66]
Pour être en adéquation avec les maquettes initiales, et après fourniture de l'ontologie validée #65 , @AudreyCDLT et moi avons besoin d'une mise à jour du backoffice.
@srosset81 effectivement, ça reste dépendant de la réalisation de #65

**Comment by srosset81** [comment]
On va implémenter ce dont on a besoin, car Guillaume a mis dans l'ontologie des choses qui ne seront pas utilisées à court terme.
Le plus simple serait donc de lister quels éléments sont manquants, selon les besoins de la maquette.
