### ISSUE TITLE
Fournir les specifications ACL pour Event et Place vue acteur sur le front

### ISSUE THREAD

**Issue by J9rem** [chemins-de-la-transition/semapps#67]
Pour développer le front, @AudreyCDLT et moi avons besoin des spécifications des droits de création, modification et ou suppression pour un acteur navigant sur une page Place ou Event.

Le besoin :
 - nous permettre de savoir quels boutons nous devons inclure dans le design
 - qui a le droit de modifier un évènement ou les données d'un lieu ?

Même si ceci peut être améliorer par la suite, nous avons besoin de savoir si ces droits sont ouverts à tous ou non pour savoir si nous devons penser une interface différenciée en fonction des utilisateurs

**Comment by bouviermullerp** [comment]
@J9rem en tant que accueillant connecté, je peux créer un Place / Event.
Je peux modifier/supprimer les Place / Event que j'ai créé
Je ne peux pas modifier/supprimer les Place / Event que je n'ai pas créé.

En tant que admin, j'ai tous les droits.

**Comment by J9rem** [comment]
Super merci, si je ne suis pas connecté que se passe-t-il ?
@AudreyCDLT est-ce que ça t'aide ?

**Comment by srosset81** [comment]
Si t'es pas connecté, tu ne peux rien créer, ni éditer.
Tu ne peux voir que les parcours qui sont finalisés (je suis en train de gérer ça automatiquement via les WebACL)

Pour simplifier, on pourrait ne pas mettre de bouton Editer/Supprimer sur la page des lieu/événement, mais avoir une interface dédiée, accessible par exemple en cliquant sur le bouton de profil (quand on est connecté). Cela permettrait aux acteurs de trouver plus facilement leurs lieux/événements.

**Comment by J9rem** [comment]
Merci pour ta proposition @srosset81 , j'envoie un lien vers cette issue à @AudreyCDLT pour qu'elle ce serve de ce qui est donc validé 

```
en tant que accueillant connecté, je peux créer un Place / Event.
Je peux modifier/supprimer les Place / Event que j'ai créé
Je ne peux pas modifier/supprimer les Place / Event que je n'ai pas créé.

En tant que admin, j'ai tous les droits.
Si t'es pas connecté, tu ne peux rien créer, ni éditer.
Tu ne peux voir que les parcours qui sont finalisés (je suis en train de gérer ça automatiquement via les WebACL)
```

**Comment by GuillaumeAV** [comment]
Salut tout le monde ! 

Je sors de mon tunnel de plusieurs semaines et de quelques jours de repos :) De nouveau dispo et chaud chaud chaud !! Hâte de notre petite réunion à 16h pour me mettre à jour sur le projet et contribuer à ma mesure !
