### ISSUE TITLE
Déployer une instance basée sur Archipel

### ISSUE THREAD

**Issue by bouviermullerp** [chemins-de-la-transition/semapps#7]
Munie des fonctionnalités déjà développées, notamment
BackOffice React-Admin
Affichage liste
Navigation de proche en proche
Authentification OIDC
Recherche simple
Carte
Etc. 
Couleurs, logo
En vue d’un déploiement 
Middleware: data.lescheminsdelatransition.org
Frontend: app.lescheminsdelatransition.org
Serveur à 22€ HT/mois sur le compte OVH des CDLT (validé le 23/02)

**Comment by srosset81** [comment]
Tout est fait sauf la connexion OIDC. Je propose d'en faire une autre sur le sujet, en spécifiant notamment s'il doit y avoir création d'un profil utilisateur et, si oui, de quel type.
