### ISSUE TITLE
Calculer automatiquement la région

### ISSUE THREAD

**Issue by srosset81** [chemins-de-la-transition/semapps#72]
Ca va être trop compliqué de déduire la région du numéro de département pour ce qui concerne les recherches SPARQL.

Côté middleware, je vais ajouter un bot qui "taggera" la bonne région les lieux, les événements et évent. les parcours (si c'est trop compliqué pour les parcours, il faudra les tagger manuellement).

@GuillaumeAV on ajoute une classe "Region" dans l'ontologie CDLT ? On pourrait utiliser "Place" mais ça va être compliqué de différencier avec les lieux. J'utiliserais `pair:hasLocation` comme predicat.

**Comment by srosset81** [comment]
Fait ici https://github.com/chemins-de-la-transition/semapps/pull/74

J'ai réussi à détecter automatiquement les régions pour les parcours, ce qui permettra d'avoir des parcours multi-région.

Pour finir j'ai utilisé la classe Place, et j'ai mis les régions dans un container à part.

**Comment by GuillaumeAV** [comment]
Aaah génial ! Du coup pas besoin de déclarer une classe région ?

**Comment by srosset81** [comment]
Non
