### ISSUE TITLE
Si un acteur est ajouté à un événement/lieu, lui donner les droits d'écriture

### ISSUE THREAD

**Issue by srosset81** [chemins-de-la-transition/semapps#75]
Pour l'instant les droits d'écriture sont donnés au moment de la création.

Mais si un événement est créé par un administrateur puis assigné à un (ou plusieurs) acteurs, ces acteurs n'ont pas le droit d'écriture.

**Comment by GuillaumeAV** [comment]
En effet ca peut être utile ! 

La bise !

**Comment by srosset81** [comment]
Fait ici https://github.com/assemblee-virtuelle/semapps/pull/830

En attente de la release côté SemApps pour déployer.

**Comment by srosset81** [comment]
Déployé
