### ISSUE TITLE
La photo de profil lieu s'affiche mal ... 

### ISSUE THREAD

**Issue by GuillaumeAV** [chemins-de-la-transition/semapps#77]
Hey ! 
Je crois que vous aviez déja identifié ce bug ;) 
Par exemple sur "Tribu Rouggioli" https://app.lescheminsdelatransition.org/Place/https%3A%2F%2Fdata.lescheminsdelatransition.org%2Fplaces%2Fchez-guitou/show

La photo ne s'affiche pas entier sur la home page ou en vue liste .. 
Par ailleurs, elle s'affiche mal quand sur la page dédiée du lieu en format bandeau ...

**Comment by srosset81** [comment]
Il doit y avoir deux images par page, ce n'est pas terminé.
