### ISSUE TITLE
Pouvoir renseigner plusieurs modalités de voyages 

### ISSUE THREAD

**Issue by GuillaumeAV** [chemins-de-la-transition/semapps#78]
Il s'agit d'un point important : 

En tant que Tribu Rouggioli, on a vocation à accueillir du monde via une diversité de modalités : Voyage découverte, voyage apprenant, voyage immersif et à terme Compagnonage : 

Quand on est un lieu à minima, il faudrait donc pouvoir faire une sélection multiple entre les 4 modalités...

**Comment by srosset81** [comment]
Pour les lieux, événements et parcours, on peut choisir un "type de parcours" qui correspond aux modalités dont tu parles.

**Comment by GuillaumeAV** [comment]
L'issue porte sur la capacité à sélectionner plusieurs modalités plutôt qu'une seule ... Je viens d'essayer à nouveau, et cela ne semble pas possible à l'heure actuelle ... Peut-être que je m'y prend mal ?

**Comment by srosset81** [comment]
C'était pas prévu pour le moment. A discuter mardi.

**Comment by srosset81** [comment]
On le fait pour les Lieux seulement.

**Comment by GuillaumeAV** [comment]
Yop ! Tu l'as fermée parce que tu l'as implémentée j'imagine ?

**Comment by srosset81** [comment]
Yep c'est ça :) En prod d'ici à quelques minutes normalement...
