### ISSUE TITLE
Back-office : Enlever les chemins (Path)

### ISSUE THREAD

**Issue by GuillaumeAV** [chemins-de-la-transition/semapps#79]
Suite à notre décision de simplifier la plateforme en allant à l'essentiel, on a décidé de ne garder que les parcours (Course) et d'enlever les Chemins (Path). 
Il faudrait donc enlever Chemins (Path) du back office ...

**Comment by srosset81** [comment]
C'est pour toujours ou temporairement ? Parce que sinon, mieux vaut les laisser et ne pas les utiliser (de toute façon le back-office ne sera accessible que par l'équipe CDLT)
Il y a aussi les organisations qui ne sont pas utilisées sur le front-office.

**Comment by GuillaumeAV** [comment]
Effectivement, je ne sais pas si c'est pour toujours ou non, on peut donc envisager de les laisser ... Est-il possible de juste ne pas faire apparaître l'item Chemins dans le menu de gauche pour ne pas créer de la confusion dans l'esprit des contributeurs qui utiliseront le back office ?

**Comment by srosset81** [comment]
Done https://github.com/chemins-de-la-transition/semapps/commit/a965c99c2aafa488e6f0a27c47cd0a37fb2c399d
