### ISSUE TITLE
A propos des modalités de voyage : Elles sont communes aux lieux / events / parcours

### ISSUE THREAD

**Issue by GuillaumeAV** [chemins-de-la-transition/semapps#80]
Pour le moment on renseigne les modalités par type d'item : 
* Lieu : PlaceType
* Event : EventType
* Parcours : CourseType

En fait, les modalités sont communes à la diversité items, il faudrait donc renseigner des modalités **communes** aux lieux / events / parcours ... Mais peut-être que c'est pas possible en l'état actuel de l'ontologie ? Il faudrait peut-être créer un "ModalityType" (à mieux formuler naturellement !) ?

**Comment by srosset81** [comment]
Je comprends pas. En tout cas pour la v0 on va rester sur ce qui a été décidé tous ensemble ici: https://docs.google.com/spreadsheets/d/1y8WjrJxVV9i8ji2m2Y2D2HBp1MaYxzSaMSRuji8rwz4/edit#gid=0

**Comment by GuillaumeAV** [comment]
En effet, c'est déja le cas, mea culpa, je ne devais pas  être réveillé, tout va bien !
