### ISSUE TITLE
Sur les pages de lieux, parcours, events, on ne peut pas cliquer sur les types, thèmes, régions ...

### ISSUE THREAD

**Issue by GuillaumeAV** [chemins-de-la-transition/semapps#82]
Sur les pages de lieux, parcours, events, on ne peut pas cliquer sur les types, thèmes, régions ... Compétences dans le corps des pages ...
Rendre cliquable ces items permettrait de créer de nouveaux chemins de navigation !

**Comment by srosset81** [comment]
J'aurai dû le savoir avant. Pas évident à faire ça dans l'état actuel du code. En plus on ne peut pas renvoyer sur une page "Thème", mais il faudrait envoyer sur la page liste, avec le filtre correspondant.

A discuter mardi.

**Comment by GuillaumeAV** [comment]
Ok ca roule !

**Comment by srosset81** [comment]
En fait rediriger vers la page liste avec un filtre est assez simple à faire grâce à une amélioration récente de react-admin.

Je l'ai fait pour la région ici:
https://app.lescheminsdelatransition.org/Course/https%3A%2F%2Fdata.lescheminsdelatransition.org%2Fcourses%2Fchemin-des-tiers-lieux-du-bocage-ornais/show

J'attendrais une confirmation d'Audrey demain avant de le faire partout.
