### ISSUE TITLE
Sur lieux parcours, évenements, les items du bloc de droite sont identiques aux items du premier menu en haut ..

### ISSUE THREAD

**Issue by GuillaumeAV** [chemins-de-la-transition/semapps#83]
[Sur l'impasse du mage par exemple](https://app.lescheminsdelatransition.org/Place/https%3A%2F%2Fdata.lescheminsdelatransition.org%2Fplaces%2Fchez-guitou/show), je mettrais d'autres items dans le bloc de droite :+1: 

Quelques idées ...

## Lieu : Ex de L'impasse du mage : 
* est gérée par : Acteur (operatedBy)
* a besoin de : Compétence (il faudrait appliquer la relation "needs" à Place)
* est proche de : Lieu (il faudrait créer cette relation)

### Événements & parcours : 
* est organisé par : Acteur
* a pour mentor : Acteur
* permet d'apprendre : Compétence

Est-ce que ca vous semble pertinent et faisable @Mathieu-CdlT @AudreyCDLT @srosset81 ?

**Comment by J9rem** [comment]
@GuillaumeAV je ne participe pas à ces discussions. Je te laisse voir avec Sébastien et Audrey

**Comment by srosset81** [comment]
Mettre des items différents demanderait de revoir le code existant. De toute façon je rappelle que sur mobile, seul un de ces deux menus est visible.

Concernant les idées, on a fait une réunion tous ensemble avant les vacances et ces éléments n'ont pas été retenus.
https://docs.google.com/spreadsheets/d/1y8WjrJxVV9i8ji2m2Y2D2HBp1MaYxzSaMSRuji8rwz4/edit#gid=0
Je rappelle que, pour la v1, il a été décidé de ne pas afficher les acteurs (personnes ou organisations) sur le front-office.

**Comment by GuillaumeAV** [comment]
Ok du coup est-ce qu'on laisse le bloc de droite sur version PC ? Je n'en vois pas l'intérêt, ou peut-être juste pour l'aspect graphique @AudreyCDLT ?

**Comment by srosset81** [comment]
Ça permet de continuer à voir les éléments quand on scroll vers le bas...
