### ISSUE TITLE
Suivi des modifications

### ISSUE THREAD

**Issue by bouviermullerp** [chemins-de-la-transition/semapps#9]
En tant qu'utilisateur connecté, je peux consulter l'historique d'une ressource : 
- Quelle modification
- Quand
- Par qui

**Comment by srosset81** [comment]
Travail énorme, et pas encore spécifié du tout du point de vue technique ou UX.

**Comment by bouviermullerp** [comment]
Yeeaahhh - peut être que je doit mentionner pour te rassurer que cette issue n'est affectée à aucune version (à l'instar d'autres)
