### ISSUE TITLE
Sur la création de nouveaux parcours : Erreur de communication avec le serveur

### ISSUE THREAD

**Issue by GuillaumeAV** [chemins-de-la-transition/semapps#91]
Il semble y avoir un problème sur la création de nouveaux parcours : 
Un message s'affiche en rouge en bas de l'écran : "Erreur de communication avec le serveur"

**Comment by GuillaumeAV** [comment]
MàJ : Le message "Erreur de communication avec le serveur" apparait, mais la donnée est néanmoins créée ...

**Comment by srosset81** [comment]
Je reproduis, merci

**Comment by srosset81** [comment]
C'est corrigé, il manquait le droits #DefaultRead pour les superadmins.
