### ISSUE TITLE
Problème à la suppression d'un parcours

### ISSUE THREAD

**Issue by GuillaumeAV** [chemins-de-la-transition/semapps#92]
Lorsque je supprime un parcours, le message apparait : 
"Un problème est survenu
En raison d'une erreur côté navigateur, votre requête n'a pas pu aboutir."

Quand je clique ensuite sur l'élément que j'ai supprimé, le massage apparait : "L'élément n'existe pas", ce qui laisse à penser qu'il a tout de même été supprimé ..

**Comment by srosset81** [comment]
Corrigé en même temps que https://github.com/chemins-de-la-transition/semapps/issues/91
