### ISSUE TITLE
Pas possible d'ajouter plusieurs modalités de voyage depuis le front office 

### ISSUE THREAD

**Issue by GuillaumeAV** [chemins-de-la-transition/semapps#97]
Quand je me connecte depuis app.lcdlt.org, je peux éditer mon profil mais je n'ai pas la possiblité de faire une sélection multiple sur les modalités de voyages. 
C'est en revanche possible depuis admin.lcdlt.org ... 

=> Tu pourrais mettre cette possibilité sur le front office également @srosset81 ?

**Comment by srosset81** [comment]
Par " mon profil" tu veux dire "mon lieu" (il n'y a pas de profil sur app.lcdlt.org).
Effectivement c'est un oubli, je m'en occupe.

**Comment by srosset81** [comment]
Fixé
