### ISSUE TITLE
Toujours un problème sur les images

### ISSUE THREAD

**Issue by GuillaumeAV** [chemins-de-la-transition/semapps#98]
J'ai essayé de charger une nouvelle image sur impasse du mage, mais ca déconne toujours ... 

=> Je crois que c'est lié à un bug d'une lirairie SemApps ? (Je crois avoir vu une issue passer dans ce sens sur le repo SemApps ..

**Comment by srosset81** [comment]
Tu peux m'envoyer l'image par mail pour que j'essaie ?

**Comment by Mathieu-CdlT** [comment]
Indiquer la taille max de l'image à uploader (besoin de compression visiblement) 
Donner la possibilité d'ajuster l'image à la taille du slideware et d'ajuster le positionnement de l'image uploadée

**Comment by srosset81** [comment]
Le problème de la taille d'image a été résolu par Simon, en attente de release et de déploiement.

Pouvoir ajuster et couper une image via une interface, c'est tout un chantier. On l'avait fait dans mon ancienne boîte et on y avait passé une semaine complète ! Il n'y a pas d'outil tout fait. Je propose de créer une autre issue si ça semble important de le faire dans le futur. En attendant, il faut potentiellement préparer l'image à l'avance sur l'ordinateur avant de l'uploader.

**Comment by srosset81** [comment]
Réglé en mettant à jour la dernière version de semapps:
https://github.com/assemblee-virtuelle/semapps/releases/tag/middleware-v0.3.13
